### ISSUE TITLE
Cancel order, remember checkout info

### ISSUE THREAD

**Issue by wdttilburg** [mollie/magento2#110]
When you cancel a order in mollie before the payment, magento doesn't remember de information you just filled in.

**Comment by Frank-Magmodules** [comment]
When the order is canceled during the payment the customer will be redirected back to the restored cart so it can restart the checkout flow.

**Comment by wdttilburg** [comment]
Yes, but is it possible to remember the data that they filled in? Sisow has support for that.

**Comment by Frank-Magmodules** [comment]
I'm not sure if this is possible as after a failed payment the checkout quote is restored. Can you share a link to a store that has this though our [contactform](https://www.magmodules.eu/contact-us.html)?

**Comment by Frank-Magmodules** [comment]
Hi @wdttilburg , any update on this? Thanks!

**Comment by wdttilburg** [comment]
Sorry, i made a mistake!
