### ISSUE TITLE
Issue with partial refunds

### ISSUE THREAD

**Issue by stefanfr** [mollie/magento2#111]
Orders that are refunded partially get fully refunded within Magento. This results in inconsistentie within the sales data. We need the exact data within Magento.

**Comment by stefanfr** [comment]
Hi Frank, Currently we are using v1.3.7. Im not sure about the Orders API or the Payments API?
Is this fixed in a more recent version and would an update be sufficiënt?

**Comment by Frank-Magmodules** [comment]
Hj @stefanfr , Yes this has been fixed, please update to the latest version.

**Comment by stefanfr** [comment]
I've updated the module and now I understand the Orders API or the Payments API. Is there a difference between the APIs in handeling credits within Magento? Or should the partial credits work with both the APIs now?

**Comment by Marvin-Magmodules** [comment]
Great! No there should be no difference in the (partial) refund/credit between the Orders API and Payments API. The only difference is that when using the Payments API it is refunding by amount and when using the Orders API it is refining using Order Lines. But for the customer this will not make any difference. Are you still facing issues?
