### ISSUE TITLE
Add store name to payment description

### ISSUE THREAD

**Issue by jasbroek** [mollie/magento2#112]
Would it be possible to prepend the name of the store to the payment description shown in the Mollie dashboard?
Now it only states 'Order [Order ID]'. 
Having multiple stores using the same Mollie account, it would be nice to see from which store a payment has been made directly in the dashboard overview.
The description could then be '[Storename] : Order [Order ID].

I've been looking into the source code but haven't found the right spot to add this.
Can anyone point me in the right direction (or comment on the feasibility)?

**Comment by Frank-Magmodules** [comment]
Hi @jasbroek. Yes sure, but this is only possible when using the Payments API, edits should be made here: [Payments.php#L95](https://github.com/mollie/magento2/blob/master/Model/Client/Payments.php#L95)
