### ISSUE TITLE
Unable to create partial online refund from Magento

### ISSUE THREAD

**Issue by FreekVandeursen** [mollie/magento2#113]
### Steps to reproduce

1. Create an order in Magento with > 1 order line
2. Pay with Mollie.
3. Create online creditmemo in Magento for 1 of the orderlines.

### Expected result

1. Online refund is processed in Mollie

### Actual result
Error from Mollie API `Line 0 contains invalid data. The 'quantity' field should be a whole number`

See pull request #109

**Comment by Marvin-Magmodules** [comment]
Thank you for the PR and detailed issue report. Fixed in [v1.5.0](https://github.com/mollie/magento2/releases/tag/v1.5.0)
