### ISSUE TITLE
Webhook failed; order state -> cancelled after certain time

### ISSUE THREAD

**Issue by downforce80** [mollie/magento2#123]
Mollie 1.3.8

We came across the following problem. 

1. - Customer chose 'banktransfer' payment at checkout.
2. - Customer payed via link in email -> iDeal
3. - Our webhook failed might due because of downtime on the server
4. - So there was no change in order state
5. - After 14 days (config setting) the order state was changed to 'cancelled'

I've looked into the mollie dashboard and can see the system tried multiple times in a one hour timeframe and then gave up. 

Maybe it's better if the timeframe for the webhook is spread in multiple hours? And check again before the order state is changed to cancelled?

**Comment by ndijkstra** [comment]
Hi @downforce80 

Thank you for your detailed issue. I will create an issue on our backlog to see how we can improve our retry mechanism of the webhooks.
In case of more issues on your side, please let us know!

**Comment by downforce80** [comment]
Thanks!
