### ISSUE TITLE
Cannot filter on order grid anymore because export_status column is missing

### ISSUE THREAD

**Issue by PascalBrouwers** [mollie/magento2#124]
Cannot filter on order grid anymore because export_status column is missing.
See: https://github.com/mollie/magento2/blob/master/view/adminhtml/ui_component/sales_order_grid.xml#L11

**Comment by Frank-Magmodules** [comment]
Hi @PascalBrouwers , thank you for the issue report. Just released a new version that has a fix for this issue. Please see [v1.5.1](https://github.com/mollie/magento2/releases/tag/v1.5.1). Closing this issue now, but please feel free to reopen the issue if this problem still occurs.
