### ISSUE TITLE
500 Internal server error - checkout page- versie 2.1.5

### ISSUE THREAD

**Issue by bastiaan21** [mollie/magento2#13]
Na de installatie van een verse Magento instance versie 2.1.5. en het installeren en activeren van de module. Krijg ik een 500 internal server error in de algemene logs kan ik niets terug vinden waar het hier mis kan gaan. 

Op het moment dat ik de module weer deactiveert kom ik wel op de checkout pagina. 

Weten jullie waar dit kan zitten?

**Comment by Magmodules** [comment]
Welk resultaat geeft de self test in de admin? En zou je de error eens kunnen opzoeken in de server logs?

**Comment by bastiaan21** [comment]
Sorry voor de late reactie. De self test geeft het volgende aan:

Success: PHP version: 7.0.11.
Success: JSON is enabled.
Success: cURL is enabled.
Success: cURL functions are enabled.

Op de checkout/ pagina breekt hij. Ik heb de module ook al geupdate maar zonder succes krijg nog steeds een 500 internal server error.

In de algemene log kwam hier niets uit. Ik zal straks even zoeken en kijken of hier iets in staat.

**Comment by Magmodules** [comment]
Dank voor de reactie, in welke modus draait Magento? Stuur me anders even een mail op marvin-at-magmodules.eu dan kan ik even met je meekijken!
