### ISSUE TITLE
Unable to ship bundle product if marked as 'Ship separately'

### ISSUE THREAD

**Issue by Swahjak** [mollie/magento2#130]
**Steps to reproduce;**
1. Create a bundle product with 1 or more simple options. Mark as 'ship separately' => yes.
2. Create an order using a Mollie payment method
3. Mark the order as paid
4. Try to ship the order using the Magento 2 backend interface

**Expected result:**
Order is shipped

**Actual result:**
Shipment creation fails with the following message `Mollie API: Error executing API call (422: Unprocessable Entity): Line 2 contains invalid data. The 'id' field is missing. Field: lines.2.id. Documentation: https://docs.mollie.com/guides/handling-errors`

I'm not a 100% sure this is the cause of the error, but it only seems to happen for orders with the specifications as described above.

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak , thanks for the detailed issue. Just reproduces this issue. The bundles product is treated as 1 product in the order and orderLines. We need to rewrite this for bundle items that can be shipped separately.

We will update you on this once ready!

**Comment by Swahjak** [comment]
@Frank-Magmodules quick question; are you going to modify the way orders are created, or the way shipments are created? Because if the first thing (orders) is the case we still won't be able to create shipments for the orders that have already been placed. Tough changing the way orders are created would be the only way to make it function correctly compared to the Magento logic.

I'm asking this to decide whether we should proceed with completing the order (I'm not sure how we should do this yet) manually or if we should wait for a fix.

**Comment by Swahjak** [comment]
@Frank-Magmodules could you update on the status of this issue? We've got quite a lot of orders affected by this issue which can't be completed.

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak , Yes we have a tested fix for this now and will sent you the PR today or tomorrow. 
Frank

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak . This is fixed with PR https://github.com/mollie/magento2/pull/133 , can you confirm?

**Comment by Swahjak** [comment]
Hi @Frank-Magmodules this will only fix future orders by the looks of it (correct me if I'm wrong). How are we supposed to deal with orders that are already 'faulty'?

**Comment by michielgerritsen** [comment]
Hi @Swahjak,

There are 2 fixes in this PR:
- 1 for creating enough order lines.
- 1 to calculate if all (remaining) items are shipped.

When shipping all items at once the api is called in a slightly different way and all items within the Mollie dashboard are marked as "shipped". When you pull this fix in this will work for existing orders as well. For existing orders that are shipped in multiple batches there is unfortunately no fix as there are not enough order lines created.

I hope this helps in your case.

**Comment by Swahjak** [comment]
@Frank-Magmodules this has been deployed to production and seems to be working. Closing issue, thank you for the support.
