### ISSUE TITLE
Exception during webhook processing will still return Success message

### ISSUE THREAD

**Issue by FreekVandeursen** [mollie/magento2#142]
If any exception occurs during the processing of a webhook, the controller will catch this exception and still return a success status to Mollie.
Although the core code is not likely to cause any exceptions, it still could happen due to network/infrastructure issues (database/network timeouts, deadlocks etc) or issues with 3rd party modules that perform additional logic on saving orders/invoices etc.

### Example steps to reproduce

1. Add a line `throw new Exception('Simulating temporary exception')` before saving the order in the processTransaction function in `\Mollie\Payment\Model\Client\Orders`
2. Place an order

### Expected result
Error code returned to Mollie, so the webhook will be retried at a later time.

### Actual result
Order has status paid in Mollie, but Pending Payment in Magento, and webhook will not be retried.

**Comment by Frank-Magmodules** [comment]
Thanks @FreekVandeursen , we have a pending Pull Request for this which will be merged in the next release this week (https://github.com/mollie/magento2/pull/137) , feel free to test it out already.

**Comment by FreekVandeursen** [comment]
Thanks @Frank-Magmodules . I did search the Issues but not the Pull Requests. Looking forward to the new release then.

**Comment by Marvin-Magmodules** [comment]
Hi @FreekVandeursen issue has been resolved in the [v1.6.0](https://github.com/mollie/magento2/releases/tag/v1.6.0) release. 
Commit: [3bcb56c3a4f6f33757b00354f79425424b5a0957](https://github.com/mollie/magento2/commit/3bcb56c3a4f6f33757b00354f79425424b5a0957)

Closing this issue now. Feel free to reopen the issue if this still occurs.
