### ISSUE TITLE
Webhook not processed correctly if paid payment is not the last one

### ISSUE THREAD

**Issue by FreekVandeursen** [mollie/magento2#143]
Found this issue from a live example where an order remained in state pending_payment although the order has status paid in Mollie backend.

### Steps to reproduce

1. Create Mollie order with method paymentlink, and send the payment link to customer
2. Customer chooses SEPA bank transfer
3. Customer clicks payment link again and chooses any direct payment method (iDeal, creditcard etc.) but doesn't finish the payment
4. Customer transfers money via bank transfer
5. Mollie receives bank transfer, and calls the webhook

### Expected result
Payment is registered in Magento and order set to state processing.

### Actual result
Webhook returns with success=false and order remains in state pending_payment. The reason for this is that the webhook processing only looks at the last payment in the json result, which is in this case the iDeal / Creditcard etc. method, which will have status=expired by the time the bank transfer is received by Mollie.

**Comment by Frank-Magmodules** [comment]
Hi @FreekVandeursen , we've just tried to reproduce this together with Mollie but it seems we did not succeed. Can you please fill in our [contact form](https://www.magmodules.eu/contact-us.html) and share your payment ID on the order where you have this issue so we can take a look with you?

**Comment by FreekVandeursen** [comment]
Done @Frank-Magmodules

**Comment by Frank-Magmodules** [comment]
Hi @FreekVandeursen. 

We have just released te new version [v1.6.4](https://github.com/mollie/magento2/releases/tag/v1.6.4) that fixes this issue.
Thank you of the input and patience. Closing this issue now, but please feel free to reopen the issue if this problem still occurs.
