### ISSUE TITLE
Add index to 'mollie_transaction_id' column

### ISSUE THREAD

**Issue by Swahjak** [mollie/magento2#149]
The column `mollie_transaction_id` is used to find orders by the mollie reference, but currently there is no index on this column. A growing sales_order table can make this query unnecessary slow.

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak,

Yes absolutely right. This issue has been reproduced and the fix has been tested, see [PR 155](https://github.com/mollie/magento2/pull/155). This will be merged in the upcoming v1.6.2 release. Thank you for reporting this bug.

**Comment by Frank-Magmodules** [comment]
Issue has been resolved and merged into [v1.6.2](https://github.com/mollie/magento2/releases/tag/v1.6.2) release. Closing this issue now. Feel free to reopen the issue if this still occurs.
