### ISSUE TITLE
Unknown module(s): 'Mollie_Payment'

### ISSUE THREAD

**Issue by goingonline** [mollie/magento2#15]
De eerste stap bij het installeren van de module gaat goed (composer require mollie/magento2)

```
Using version ^1.0 for mollie/magento2
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing mollie/mollie-api-php (v1.9.2)
    Downloading: 100%

  - Installing mollie/magento2 (1.0.0)
    Downloading: 100%

mollie/mollie-api-php suggests installing mollie/oauth2-mollie-php (Use OAuth to authenticate with the Mollie API. This is needed for some endpoints. Visit https://mollie.com/en/docs for more information.)
Writing lock file
Generating autoload files
```

Maar bij stap 2 krijg ik de volgende melding:
```
$ php bin/magento module:enable Mollie_Payment
Unknown module(s): 'Mollie_Payment'
```

Mis ik iets of gaat hier iets fout?

**Comment by Magmodules** [comment]
Merkwaardig, welke Magento versie wordt er gebruikt? En wordt hij wel weergegeven bij setup:upgrade?

**Comment by goingonline** [comment]
Wij gebruiken Magento 2.1.2. Ik zie de Mollie module ook niet staan bij setup:upgrade. 

Voor de zekerheid, het is niet nodig om bestanden te uploaden voor het installeren van de module? Klopt dat?

**Comment by Magmodules** [comment]
Nee, is niet nodig, stuur met anders even een email op marvin-at-magmodules.eu dan kan ik even met je meekijken als dat mogelijk is?

**Comment by Magmodules** [comment]
Opgelost, foutmelding lag niet aan de extensie.
