### ISSUE TITLE
Update module to use db_schema.xml

### ISSUE THREAD

**Issue by Swahjak** [mollie/magento2#150]
Starting from Magento 2.3 the preferred way of declaring schema's is to use `db_schema.xml` https://magento-devdocs.github.io/devdocs-for-tests/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html / https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.html

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak ,

Thank you for opening this issue. We are well aware that the `db_schema.xml` exists, as well as [data patches](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/data-patches.html). It would be really great if we could use this features, but as we also have to support the lower versions of Magento (2.1 & 2.2). This gives us a few options:

- Write the same code twice, but with extra checks to see which version we are using so some of the `UpgradeData.php`/`UpgradeSchema.php` code is not run (not an option).
- Maintain multiple versions of the code for each specific Magento version (not an option).
- Drop support for lower Magento versions (not an option).

This means that for now we are going to hold on to our current method, as this is the easiest way for > us. As soon as we can use the new methods we will switch to them.

**Comment by Swahjak** [comment]
Fair enough. Although Magento does provide methods for backward compatibility.

> All released modules that previously used upgrade scripts must support backward compatibility by implementing \Magento\Framework\Setup\Patch\PatchVersionInterface and the getVersion method. This method allows you to skip changes that were applied in previous versions and were done by old scripts. The returned value of the getVersion method in this case should be equal to the value of a version in version_compare function in old scripts. When the InstallData.php script does not have any versions to compare, you can specify the first version of your module. See Develop declarative data and schema patches for more information.
