### ISSUE TITLE
Orders API causes orders to stay in a pending_payment state for 28 days

### ISSUE THREAD

**Issue by Swahjak** [mollie/magento2#161]
There should be a **BIG** warning that the orders API will cause orders to stay in a pending state for 28 days. Currently it's being advertised to use the orders API
> "Use the new Order API Platform and get additional insights in the orders. Read more."

In the module.
> "Using the Orders API is the preferred approach when integrating the Mollie API into e-commerce applications such as webshops."

On the 'Read more' link.

But switching from payment to orders will have a big side effect if you depend on orders being canceled automatically after the transaction fails.

**Comment by Swahjak** [comment]
On a side note; How do others work with this? I can hardly imagine that there are a lot of merchants who would like to have a pending order for 28 days. This also means (especially since Magento 2.3) that there wil be a reservation on the stock, possibly making a product unsalable for 28 days. Is there anything in the extension that I'm missing? I can see the use case if we would actively remind customers to pay for their orders, but as long as there is no such logic I don't see any use for the orders API except for afterpay / Klarna.

**Comment by jorgb90** [comment]
We just use the payments API. We don't need the orders API.

**Comment by Swahjak** [comment]
@jorgb90 We did as well, until we were advised to use the order API since we use Klarna. At that point I we didn't see any reason to start using two different API's and decided to switch to the Orders, not knowing that this would bring a 28 day pending period since it's not that well documented in the obvious places (the module or the page that the 'read more' refers to). There is absolutely no point in enabling the Orders API for 'IDeal' or 'PayPal' so why even give the option to do so. The only reason I can think of is because it's the
> preferred approach

But if the preferred approach is to have products blocked for 28 days I'm not sure if Mollie knows how e-commerce actually works.

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak ,

Sorry for the long wait, we were discussing this internally and also needed to discuss this with Mollie with the result that Mollie released the possibility to set a expiresAt for the Orders API. 
_(See: https://docs.mollie.com/changelog/v2/changelog#wednesday-17th)._ 

We will implement this in the upcoming release where the lifetime of the order is configurable. The plans are to make an option per method and also the ability to set an end date per Magento order when using the Admin Payment link.

**Comment by Swahjak** [comment]
@Frank-Magmodules has this issue been resolved in the latest release(s)?

**Comment by Frank-Magmodules** [comment]
HI @Swahjak , the feature will be added in the next release as Mollie recently added the new `expiresAt` parameter to set the custom date to their API as well. Keep you posted!

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak , we've just released [version 1.7.1](https://github.com/mollie/magento2/releases/tag/v1.7.1) where you can configure the `expiresAt` variable for OrderAPI payments and the PaymentLink. We are closing this issue now.

Thank you for thinking with us on this.
