### ISSUE TITLE
Not handling stock reservations (>= 2.3.0) correctly on uncancel

### ISSUE THREAD

**Issue by Swahjak** [mollie/magento2#164]
I'm not sure if and when this happens (we're not actively monitoring how many order are canceled and re-opened), but I ran into the code and concluded that it was incomplete to properly function with Magento >= 2.3.0.

## Steps to reproduce

1. Place order using Mollie
2. Cancel order
3. Pay order

## What is the current bug behavior?

If an order is uncancelled by the module there are no reservations

Since Magento 2.3.0 there is more to 'simply' uncancelling an order than meets the eye. They introduced a reservation logic that reserves orders as soon as they are placed. When an order is canceled the reservation is canceled as well. So when re-opening an order (uncancelling) there should be new reservations.

## What is the expected correct behavior?

If an order is uncancelled by the module there should be reservations.

## Possible solution

https://github.com/mollie/magento2/pull/160

**Comment by Swahjak** [comment]
I started working on a pull request but due to our high season I might not be able to finish it any time soon. If anybody could test & debug it, great. Otherwise I'll pick this up after things cool down.

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak, thanks again for your patience and the detailed issue report. The issue has been resolved in the [v1.12.0](https://github.com/mollie/magento2/releases/tag/v1.12.0) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.
