### ISSUE TITLE
Too much logic in Success controller

### ISSUE THREAD

**Issue by peterjaap** [mollie/magento2#167]
The [success controller](https://github.com/mollie/magento2/blob/master/Controller/Checkout/Success.php) contains too much logic; it also handles cases where the payment *isn't* a success (cancellation & rejection). This is confusing, since the route says 'success'.

The controller should be split up in actual 'success', 'reject' and 'cancel' controllers, and the domain logic should be moved to a corresponding model so it can be triggered by the webhook/callback instead of being dependent on the customer browsing back to a specific url.

**Comment by Frank-Magmodules** [comment]
HI @peterjaap , Thank you for creating this issue and thinking with us. As Mollie only supports one return url, it is not possible to split this up in different controllers. The status of the transaction needs to be pulled and can not be transferred in the return url. For the headless implementation, we can look into creating a new endpoint in the module to get the status based on OrderID & Payment Token.

**Comment by woutersamaey** [comment]
If there is only 1 return URL, then maybe change the name of the controller to something else than "success"?

**Comment by CompactCodeEU** [comment]
You can do an API call on the success controller (or another controller not named 'succes' but for example 'status') where you fetch the payment status from Mollie and show different notifications to the customer depending on the result. We actually already do this for a PWA system that uses the Mollie API.

**Comment by Frank-Magmodules** [comment]
Hi All! 

Success controller has been renamed to process and API endpoints have been added in the latest release. See [Process.php](https://github.com/mollie/magento2/blob/master/Controller/Checkout/Process.php) for new controller and [PWA integration](https://github.com/mollie/magento2/wiki/PWA-integration) for more information about the new endpoints. At the moment only REST is support, but GraphQL is on the roadmap. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by peterjaap** [comment]
@Frank-Magmodules getting there.... 

The problem is that [here](https://github.com/mollie/magento2/blob/cf78288c5d5b3521598d7e32c0f8a899addbf424/Service/Order/Transaction.php#L46) you're redirecting to the exact URL. You're not appending an order ID or Payment token, which you _are_ doing [here](https://github.com/mollie/magento2/blob/cf78288c5d5b3521598d7e32c0f8a899addbf424/Service/Order/Transaction.php#L51).

My suggestion would be to add the order ID and payment token to the custom success URL as well (or create placeholders for them that _can_ be replaced). When I have the order ID in the success URL on the PWA, I can then call the Mollie API to fetch the correct data (and my shopping system to fetch order data to show on the success page). At this point, I have no idea which order has actually been placed and I don't know either whether it was successful or not.

**Comment by CompactCodeEU** [comment]
@peterjaap If you need a solution for VueStorefront PWA then we already implemented that

**Comment by peterjaap** [comment]
@CompactCodeEU thanks but we're using Deity :)

**Comment by Frank-Magmodules** [comment]
Hi @peterjaap, thanks for the suggestion, we have added this in in the [v1.12.0](https://github.com/mollie/magento2/releases/tag/v1.12.0) release. 
See commit: https://github.com/mollie/magento2/commit/d5da7cafe4994e789216a225b9b34b0eb3a93d46
