### ISSUE TITLE
Manually authorize payment

### ISSUE THREAD

**Issue by jorgb90** [mollie/magento2#168]
When creating an order in the backend for customers with a Mollie betaallink there is no possibility to manually authorize the payment or set the order to paid. When there is no payment done through Mollie the order of course gets cancelled, but sometimes our customers are paying us directly by banktransfer instead, which of course we try to reduce, but it happens. There is no way to uncancel these orders while they are paid. I know we can create a new order for the customer, but the possibility to manually authorize a offline payment would be a much nicer solution.

**Comment by jorgb90** [comment]
Can I upvote this one? We are having more and more orders we can not ship cause of the cancellation through Mollie. These orders are paid (outside Mollie) so should be able to get shipped! Now the extension is preventing it..

**Comment by jorgb90** [comment]
I have for now removed the observers in /etc/events.xml don't know if I am running into other problems then..

**Comment by Frank-Magmodules** [comment]
Hi @jorgb90, sorry for the long wait but feature has been implemented in the [v1.9.0](https://github.com/mollie/magento2/releases/tag/v1.9.0) release. 
We are closing this issue now but please feel free to reopen the issue.
