### ISSUE TITLE
 Could not find package mollie/magento2

### ISSUE THREAD

**Issue by whatsnow** [mollie/magento2#17]
Hello,

Probeer op magento2 jullie package te installeren, draai op dit moment op de versie 7.1.3.0 en krijg de volgende melding:

Could not find package mollie/magento2 at any version matching your PHP version 7.1.3.0

Dit terwijl andere versie van 7 wel beschikbaar is, kan dit aangepast worden?

Groeten,

David

**Comment by Magmodules** [comment]
Hi David, 

PHP 7.1.x wordt momenteel door Magento 2 niet ondersteund, zie:
http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html
https://github.com/magento/magento2/blob/develop/composer.json#L11

Zodra dit wel zo is, zullen we dit uiteraard testen en aanpassen.
