### ISSUE TITLE
Mollie installeren zonder Command Line

### ISSUE THREAD

**Issue by TD-ICT** [mollie/magento2#18]
Beste,

Hoe kan ik de Mollie plug-in installeren in Magento 2.1 zonder Command Line?
Kan de bestanden plaatsen in een map in de Magento folder? En zo ja, welke map?

Ik hoor graag van u.

Met vriendelijke groet,
Tim Dielemans

**Comment by Magmodules** [comment]
Is momenteel enkel mogelijk via composer. Installeren zonder CLI wordt sowieso lastig gezien je na installatie de setup:upgrade moet draaien. Zijn momenteel bezig om hem in de Magento Marketplace te krijgen, dan is dit wel mogelijk.

**Comment by TD-ICT** [comment]
Bedtand voor je reactie.
Is het mogelijk dat iemand dit voor mij doet?
Eventueel tegen betaling?

**Comment by TD-ICT** [comment]
Bedtand voor je reactie.
Is het mogelijk dat iemand dit voor mij doet?
Eventueel tegen betaling?

**Comment by Magmodules** [comment]
Sure, stuur even een request via: https://www.magmodules.eu/contact-us.html
Dan kijken we even met je mee!

**Comment by DHanibals** [comment]
Hallo Tim,

Ik zit met hetzelfde probleem.

Hoe is het uiteindelijk gelukt om Mollie te installeren?

Groeten,

Dennis Hanibals
