### ISSUE TITLE
No payment methods with subtotal €0.00

### ISSUE THREAD

**Issue by GetMagented** [mollie/magento2#186]
In our webshop we sell 'free' products and customers only have  to pay for shipping. So when customers go to checkout, the subtotal will be € 0.00, and only when the customer selects the shipping method, the total will  be refreshed to for example € 6.95.

The issue is that the Mollie extension is not refreshing the payment methods, at least not  in our setup. Therefor, no payment methods are showing. If we refresh the page after selecting the shipping method, the  methods do show up.

In mollie.log we have this, which makes sense:

`[2019-08-03 11:58:28] Mollie.ERROR: error: Function: getActiveMethods: Error executing API call (400: Bad Request): The amount is lower than the minimum. Field: amount. Documentation: https://docs.mollie.com/guides/handling-errors [] []`

Default Magento2 payment methods do  refresh  succesfully, for example The Check/Money  Order method will show up after selecting the shipping method.

Also the payment methods of our other PSP (Pay.nl) do refresh succesfully when we try  that extension:
https://github.com/paynl/magento2-plugin

But when we enable Mollie, it does not work. Is there any way to disable the check of minimum amount, or make the API check again after selecting shipping method?

Our setup:
- Magento 2.3.0
- OneStepCheckout 1.2.034
- Mollie 1.6.5

If you need any information  or a test-envinrment to see  the issue, please let me know. 

<img width="781" alt="Schermafbeelding 2019-08-03 om 14 03 08" src="https://user-images.githubusercontent.com/3934454/62411833-7b33fe80-b5f9-11e9-80b8-ca680f14a38a.png">

After refreshing (f5):
<img width="855" alt="Schermafbeelding 2019-08-03 om 14 21 28" src="https://user-images.githubusercontent.com/3934454/62411859-07462600-b5fa-11e9-986e-9eb87f89cd46.png">

**Comment by Frank-Magmodules** [comment]
HI @GetMagented , Thanks for your message on this, we were able to reproduce this in our own environment and we are getting this fixed a.s.a.p., i will update this issue once we have a fix.

**Comment by Frank-Magmodules** [comment]
Hi @GetMagented, thanks again for detailed issue report. The issue has been resolved in the [v1.7.0](https://github.com/mollie/magento2/releases/tag/v1.7.0) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by GetMagented** [comment]
Thanks it has been fixed when selecting a shipping method. When I change the shipping method, the payment methods of Mollie are refreshed succesfully. However to make things a little bit more complicated, we are using [Amasty Extra Fee extension](https://amasty.com/extra-fee-for-magento-2.html) which makes it possible for us to charge extra fees in checkout. At this moment we still have an issue in this situation:

1. Customer adds our free product to cart
2. Customer selects a free shipping method
3. Customer selects a paid Extra Fee service.

In this case the customer only has to pay for the extra fee. Subtotal will show a positive amount but Mollie does not take this into account. Is there any way that the mollie payment methods can be refreshed based on subtotal instead of shipping method?

**Comment by Marvin-Magmodules** [comment]
Hi @GetMagented can you send me the store url by email so I can check how this is implemented in the checkout, as I'm not 100% sure about this?
