### ISSUE TITLE
Mollie payment gateway installation

### ISSUE THREAD

**Issue by DV2017** [mollie/magento2#19]
I have installed Mollie for Magento 2 from GutHub. But while testing using TestApi I get error message at checkout: 'cannot connect to server. please try again". 

I checked the server and the installation. they are both fine. What seems to be the issue?

**Comment by Magmodules** [comment]
What results are you getting from the selftest?

**Comment by DV2017** [comment]
Hi,
I could not proceed to a full test. At checkout I got the error message. “cannot write to server”
Deepa

**Comment by Magmodules** [comment]
Selftest is a function in the extension, see: Mollie > General > Selftest (button). 
Also please check the debug logs under var/logs/mollie.log

"cannot write to server" looks like a permissions problem, any files in var/log?

**Comment by DV2017** [comment]
Sorry, I can’t locate var/logs/mollie.log
I have a generic var log. do you mean this?

**Comment by DV2017** [comment]
Sorry, but i am not a developer. But I can try if you can take me through it.

**Comment by DV2017** [comment]
Can you please explain where the debug option is? I have installed the extension a week ago.

**Comment by Magmodules** [comment]
Sure, no worries, drop us a request at: https://www.magmodules.eu/contact-us.html and we will guide you through the process!

**Comment by DV2017** [comment]
I have sent the request to this email.

**Comment by Magmodules** [comment]
Wrong installation
