### ISSUE TITLE
URI is not valid and cannot be converted into a string

### ISSUE THREAD

**Issue by kuhnnl** [mollie/magento2#196]
When selecting different storeview and try to pay with mollie i get the following error 

Base URL and Secure URL are correct for the storeviews 

{"0":"URI is not valid and cannot be converted into a string","1":"#0 \/var\/www\/html\/magento-porto\/vendor\/zendframework\/zend-http\/src\/Header\/AbstractLocation.php(102): Zend\\Uri\\Uri->toString()\n#1 \/var\/www\/html\/magento-porto\/vendor\/zendframework\/zend-http\/src\/Header\/AbstractLocation.php(137): Zend\\Http\\Header\\AbstractLocation->getUri()\n#2 \/var\/www\/html\/magento-porto\/vendor\/zendframework\/zend-http\/src\/PhpEnvironment\/Response.php(96): Zend\\Http\\Header\\AbstractLocation->toString()\n#3 \/var\/www\/html\/magento-porto\/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(310): Zend\\Http\\PhpEnvironment\\Response->sendHeaders()\n#4 \/var\/www\/html\/magento-porto\/vendor\/zendframework\/zend-http\/src\/PhpEnvironment\/Response.php(126): Magento\\Framework\\App\\Response\\Http\\Interceptor->sendHeaders()\n#5 \/var\/www\/html\/magento-porto\/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(336): Zend\\Http\\PhpEnvironment\\Response->send()\n#6 \/var\/www\/html\/magento-porto\/vendor\/magento\/framework\/HTTP\/PhpEnvironment\/Response.php(39): Magento\\Framework\\App\\Response\\Http\\Interceptor->send()\n#7 \/var\/www\/html\/magento-porto\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\HTTP\\PhpEnvironment\\Response->sendResponse()\n#8 \/var\/www\/html\/magento-porto\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\Response\\Http\\Interceptor->___callParent('sendResponse', Array)\n#9 \/var\/www\/html\/magento-porto\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\Response\\Http\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#10 \/var\/www\/html\/magento-porto\/generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php(117): Magento\\Framework\\App\\Response\\Http\\Interceptor->___callPlugins('sendResponse', Array, Array)\n#11 \/var\/www\/html\/magento-porto\/vendor\/magento\/framework\/App\/Bootstrap.php(259): Magento\\Framework\\App\\Response\\Http\\Interceptor->sendResponse()\n#12 \/var\/www\/html\/magento-porto\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#13 {main}","url":"\/fr\/mollie\/checkout\/redirect\/","script_name":"\/index.php"}

**Comment by Marvin-Magmodules** [comment]
Hi @kuhnnl, thank you for the issue report. This requires a bit more information. 
Can you please [contact](https://www.magmodules.nl/contact-us.html) us directly with the link of the store and mollie.log so we can look into the issue?

**Comment by Marvin-Magmodules** [comment]
Issue was the result of duplicate Increment IDs in the store. Magento is loading the [last order](https://github.com/magento/magento2/blob/0a92770d2e546a5084fec17d727ab200b3bf18c6/app/code/Magento/Checkout/Model/Session.php#L539) based on Increment ID, which (in this case) resulted in an order being loaded from a different Storeview. Also see same issue here: https://github.com/magento/magento2/issues/17161

Closing issue now, but feel free to reopen if the problem still occurs after fixing the Increment ID-sequence.
