### ISSUE TITLE
Access token parameters and applicationFee parameters

### ISSUE THREAD

**Issue by boban-dj** [mollie/magento2#197]
I could not find in the Model any reference to the applicationFee in Payment class.
Because the mollie dashboard supplies organization access tokens in their dashboard, there is no need to implement Oath for charging a fee to another connected merchant. Only applicationFee with required parameters and profileId for connected merchant(shop) is needed as additional parameter in payment object.
It would be a great additional feature, could someone collaborate on this.
meaning where would I adjust the code?
thanks

**Comment by martinmollie** [comment]
Hi there!

Thanks for your feature request and interest in our extension. It's true that you can use Organisation Access Tokens to access our OAuth API's, but if you want to implement Application Fees you will still need your customers to go through the OAuth flow as explained on the following page: https://docs.mollie.com/oauth/getting-started

To integrate this process in our Magento 2 extension will require some work and it's not on our roadmap at the moment.
