### ISSUE TITLE
Speed 

### ISSUE THREAD

**Issue by kuhnnl** [mollie/magento2#20]
When placing a order it takes 35 seconds to load the payment gateway. is there any improvements or suggestions to make it faster

**Comment by Magmodules** [comment]
Running in production mode with cache enabled?

**Comment by kuhnnl** [comment]
Yes indeed

Verstuurd vanaf mijn iPhone

**Comment by Magmodules** [comment]
Can you send us the store url though our contact form at https://www.magmodules.eu/contact-us.html so we can check this?

**Comment by kuhnnl** [comment]
I send it via the contact form on the website 

Verstuurd vanaf mijn iPhone

**Comment by Magmodules** [comment]
Closing this issue, no response
