### ISSUE TITLE
Invoice quantity of order is wrong after payment successfully

### ISSUE THREAD

**Issue by nnthanh1996** [mollie/magento2#209]
Hi,

I got an issue with my order like this image.
![issues](https://user-images.githubusercontent.com/22760787/69936688-1935c800-150b-11ea-8fc3-c0f153c6db31.PNG)
It's missing invoiced status in Qty column of order item table but invoiced has already created after payment successfully (I've checked mollie.log) so order still has processing status even that I've make a shipment.
It happen rarely for me, but I have 02 orders, which it appear.
Please help me fix it.

My magento platform version: 2.3.3
My mollie payment module version: 1.4.3

Reproduce step:
1. Order product
2. Payment via Ideal
3. Check order in magento backend.

**Comment by Frank-Magmodules** [comment]
Hi @nnthanh1996  ,
From Magento 2.3.2 some validation things has changed so please update your Mollie extension.

**See from 1.6.3;**
_Disable the CSRF validation for the frontend Mollie routes to make the webhooks work in Magento 2.3.2
https://github.com/mollie/magento2/releases_

If you update the extension to the latest version, everything will work like it should again.

**Comment by nnthanh1996** [comment]
@Frank-Magmodules Thank for your answer.
But your bug which you mention above was reported by my team leader and he has already fixed it.
![issues](https://user-images.githubusercontent.com/22760787/69944830-cc59ed80-151a-11ea-9377-05936d0dadf7.PNG)
![issues2](https://user-images.githubusercontent.com/22760787/69944842-d0860b00-151a-11ea-8cf5-f060269d1a5e.PNG)
In my situation, the order invoice was created by mollie successfully and my customer had been processed to create shipment successfully but order status has been not changed to complete. It's still processing now.

**Comment by Frank-Magmodules** [comment]
Hi @nnthanh1996 ,

Thank you for your fast response, good the CSRF issue is solved here. I'm not familiair with the QTY issue that you mention and we can't reproduce this on Magento 2.3.3 with our latest Mollie release, knowing that, i want to ask you to update the extension to the latest version. 

If the issue still occurs after the update, please feel free to drop us a message using our [contact form](https://www.magmodules.eu/contact-us.html) with your store details so we can take a look with you on this.

Frank

**Comment by nnthanh1996** [comment]
Hi @Frank-Magmodules ,
Thank you so much.
