### ISSUE TITLE
mollie and dutch giftcards

### ISSUE THREAD

**Issue by scher200** [mollie/magento2#21]
Dear Mollie Developers,

As we in Holland give a lot of gifts, and so a lot diffirent of e-giftcards.
So we would like to pay by Mollie with these different payment cards. 
The company that arranges these online payments is https://intersolve.nl/
I called them and they are willing to cooperate and reveal the REST-API
Could you please try and implement this in mollie so all customers can pay with they're dutch e-giftcards

**Comment by adriaanmol** [comment]
Hi @scher200 — This is not a specific Magento 2-request. As I can already tel you, Mollie is currently working together with Intersolve to offer all their Giftcards to Mollie customers. Integration of this complex system could still take a few months to be released though.

**Comment by scher200** [comment]
thank you for confirming that, and yes you are right
