### ISSUE TITLE
Improvement: Surcharge for all different payment methods

### ISSUE THREAD

**Issue by tropilex** [mollie/magento2#211]
Hello,

There is a surcharge now for Klarna payments. That's cool. But I would be awesome to have a surcharge for every single payment.

For example: PayPal is more expensive then Klarna these days.

And for B2B transactions you can still surcharge for credit cards (EU law don't let you charge B2C). In our closed dealer portal a surcharge would be helpful to push dealers to a cheaper payment method.

Regards, Kees

**Comment by Frank-Magmodules** [comment]
Hi @tropilex , thank you for creating the issue. We have discussed the feature and we will be adding this in an upcoming release. Please see our [roadmap](https://github.com/mollie/magento2/blob/master/ROADMAP.md) for more information.

**Comment by tropilex** [comment]
Thnx @Frank-Magmodules !

**Comment by Frank-Magmodules** [comment]
Hi @tropilex, this feature has been added to the latest release. 

```
Feature: Surcharge available for all Payment Methods
Feature: Surcharge calculation methods as percentage, fixed or combined
Feature: Surcharge can be limited regardless of the calculation method
```

Thank again for submitting the request. We are closing this issue now but please feel free to reopen the issue if this still occurs.
