### ISSUE TITLE
Send a mail with an iDeal-link to the customer if payment timed out

### ISSUE THREAD

**Issue by gerben86** [mollie/magento2#212]
Sometimes a customer didn't finalize his payment so an order will be cancelled.
It would be a nice feature that the Mollie-plugin could send the customer an email with an iDeal-url so he could still finalize the order via that mail.

This would increase the conversion rate (a little) en give the merchant the opportunity to still receive the money/order without that the customer needs to recreate the order.

Please let me know your opinion about this!
(or give hints how I could create this extension myself)

**Comment by Frank-Magmodules** [comment]
Hi @tropilex , thank you for creating the issue. We have discussed the feature and we will be adding this in an upcoming release. At first we will be adding this option as a manual action from the order overview page. Please see our [roadmap](https://github.com/mollie/magento2/blob/master/ROADMAP.md) for more information.

**Comment by Goeny** [comment]
This would be a great addition.
But would this mean the order will be "un-canceled" and keeps the same ordernumber?

**Comment by Frank-Magmodules** [comment]
It wil create a new order with the same ordernumber followed by -1. So if order 10000000023 was void, this order will be canceled and a new order with order link will be created with IncrementId 10000000023-1.

**Comment by Frank-Magmodules** [comment]
HI @gerben86,

We are happy to tell you that we added the Second Chance Email to one of our latest [releases](https://github.com/mollie/magento2/releases).
With this feature, you make it possible to send an e-mail to customers with a failed or unfinished payment to give them a second chance on finishing the payment through the PaymentLink and revive their order.
You can find the exact explanation of this feature on the [Wiki](https://github.com/mollie/magento2/wiki/Using-The-Second-Chance-Email) Page. In the future we will probably automate this process.

I'm closing this issue now as it's wrapped up.
Have a great day ahead! 

Frank

**Comment by gerben86** [comment]
Great, thanks!

**Comment by gerben86** [comment]
@Frank-Magmodules : for which order statusses does this "second change feature" work?
Because I saw it while the status was "Wachtende op betaling", but the button is gone since the status is "Cancelled".
And I'd like to have it also in the "Cancelled" status.

**Comment by Frank-Magmodules** [comment]
Hi @gerben86 ,

Correct, it's only showing on the following statuses at the moment;

```
STATE_NEW
STATE_PENDING_PAYMENT
```
