### ISSUE TITLE
UpgradeSchema in error

### ISSUE THREAD

**Issue by Toevallig** [mollie/magento2#213]
The upgrade schema to install the new table has an error, it checks on version to be 1.9.0. It either should be check on 1.10.0  or your etc/module.xml should reflect 1.9.0

**Comment by Frank-Magmodules** [comment]
Hi @Toevallig yes, you are right!
We've just pushed the edit to the [1.10.0-pwa-components  banche](https://github.com/mollie/magento2/tree/1.10.0-pwa-components).

Have a good day!
