### ISSUE TITLE
Add Apple Pay shortcut button to cart

### ISSUE THREAD

**Issue by gigadesign1** [mollie/magento2#214]
A great benefit of using Apple Pay is that the customer doesn't have to enter his or her address details when using this payment method, because it will be selected from the Apple account that the customer is paying through.

At this moment I see that Apple Pay through the Mollie plugin is only available in the payment methods section of the checkout, *after* a customer has entered their address details.

It would be great if a shortcut button could be added to the (mini)cart of Magento and a customer doesn't have to enter their address details on the website itself, just like the PayPal Express functionality works that's built into the core of Magento 2.

**Comment by Frank-Magmodules** [comment]
Hi @gigadesign1 , thank you for creating the issue. We have discussed the feature and we will be adding this in an upcoming release. Please see our [roadmap](https://github.com/mollie/magento2/blob/master/ROADMAP.md) for more information.

**Comment by Frank-Magmodules** [comment]
Hi @gigadesign1 ,

Finally, I'm able to share the news that we've just released the new [1.1.5](https://github.com/mollie/magento2/releases/tag/v1.15.0) version with a Direct Apple Pay solution in the checkout. Thank you again for your request and patience. We are closing this issue now but please feel free to reopen the issue if you still have any requests.
