### ISSUE TITLE
Apple pay payment method does not appear on frontend 

### ISSUE THREAD

**Issue by thioz** [mollie/magento2#215]
After installing the 1.9 version of the plugin and enabling Apple Pay as a payment method in the Magento 2 backend, the frontend does not show the ApplePay payment method on the checkout page.

**Comment by Frank-Magmodules** [comment]
Hi @thioz , thank you for creating this issue. Mollie automatically detects whether your customer is paying from an Apple Pay enabled device (e.g. a Macbook with Touch ID or an iPhone with Touch ID) and using Safari. Only then will Apple Pay be shown as a payment method. Also see the Mollie information [page](https://help.mollie.com/hc/en-us/articles/360022855713-How-does-Apple-Pay-work-for-consumers-).

If this is not the issue and you still encounter technical problems on this, please sent us a message using our [contact form.](https://www.magmodules.eu/contact-us.html)

**Comment by Frank-Magmodules** [comment]
Hi @thioz, as we did not get any reply on this issue we presume this issue has been solved. Please feel free to reopen the issue if you still have problems with the visibility of Apple Pay on an Apple Pay enable device.
