### ISSUE TITLE
FEATURE REQUEST: Create payment link with other payment method active

### ISSUE THREAD

**Issue by Goeny** [mollie/magento2#216]
We offer just 2 payment methods to our customers - Mollie and banktransfer.

Sometimes a customer placed an order using the banktransfer method but forgets to pay or simply asks if we can send a payment link.

It would be a great addition if we were able to send that payment link eventhough the order has a different payment method selected.

This is a feature supported by Ingenico/Ogone so i would imagine it would be possible for Mollie aswell.

**Comment by Frank-Magmodules** [comment]
Hi @Goeny. Thank you for opening this feature request. If you enable the Orders API for Banktransfer you will have the payment link available in the admin. Also Mollie is sending these customers an email which includes a payment link so they can also pay with iDeal.

**Comment by Goeny** [comment]
Hi @Frank-Magmodules . I completely missed that. Thanks for bringing it to my attention.

Will close this request since it is already available.
