### ISSUE TITLE
GraphQl support

### ISSUE THREAD

**Issue by tdgroot** [mollie/magento2#218]
We created a module to provide GraphQl support for Mollie orders: https://github.com/mooore-digital/magento2-module-mollie-graph-ql.

If you wish to inherit the functionality, feel free to do so!

**Comment by Frank-Magmodules** [comment]
Hi @tdgroot, thank you very much for sharing your addition regarding the GraphQl support for the Mollie extension. I have shared this with our team, we are definitely going to use it to our advantage. Surely I will share this with you once we've implemented in the extension. Thank you again!

**Comment by DeLuuk** [comment]
hey @Frank-Magmodules,

Great that you introduced this. But since this update the versions 2.2.0, 2.2.1, 2.2.2 and 2.2.3 don't work with the latest version anymore.

Those versions don't have GraphQL implemented.

Can you edit the ReadMe.md with this? Otherwise it's misleading.

**Comment by Frank-Magmodules** [comment]
Hi @DeLuuk , 

Thank you for your comment! I'm sure what you mean exactly, is the module not working on Magento 2.2 or? As GraphQL is only available in Magento since 2.3, so this module does not add any GraphQL support to Magento in 2.2.

**Comment by DeLuuk** [comment]
Hey @Frank-Magmodules,

Yes that's what I mean. GraphQL isn't in Magento 2.2.

But you added a `use` field for Framework/GraphQl in the files.
And that means the latest version of your extension doesn't work anymore on Magento 2.2. Even though your page says "Mollie for Magento 2.2.x and higher".

I just tried to install your extension on a Magento 2.2.3 shop and got errors.

**Comment by Frank-Magmodules** [comment]
Hi @DeLuuk , We have tested this on 2.2.x without any issues. Can you contact us through our [contact form](https://www.magmodules.nl/support-form.html) and share these errors with us? Thank you!

**Comment by DeLuuk** [comment]
Hey @Frank-Magmodules,

I don't think there is any need.
In https://github.com/mollie/magento2/blob/master/GraphQL/Resolver/Cart/AvailableIssuersForCart.php you use "GraphQl" multiple times.
```php
use Magento\Framework\GraphQl\Config\Element\Field;
use Magento\Framework\GraphQl\Schema\Type\ResolveInfo;
use Magento\Framework\GraphQl\Query\ResolverInterface;
```

And if you grab a Magento 2.2 installation you can see that vendor/magento/framework/GraphQl doesn't exist.
See https://github.com/Magestore/devops-magento-2.2.2/tree/master/vendor/magento/framework for instance.
There for setup:di:compile will throw this error: 
```cli
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec 52.0 MiB
PHP Fatal error:  Interface 'Magento\Framework\GraphQl\Query\ResolverInterface' not found in /app/code/Mollie/Payment/GraphQL/Resolver/Cart/AvailableIssuersForCart.php on line 17
```

GraphQL was added in Magento 2.3.
https://devdocs.magento.com/guides/v2.3/release-notes/ReleaseNotes2.3.0OpenSource.html#improved-developer-experience

So this makes your extension only compatible with Magento 2.3.

**Comment by DeLuuk** [comment]
Hey @Frank-Magmodules,

I see that if I installed it with composer it would maybe work.
You have those three files inside of the Mollie extension https://github.com/mollie/magento2/tree/master/LegacySupport/GraphQl.
And in composer.json:
```json
"autoload": {
    "files": [
      "registration.php",
      "LegacySupport/GraphQl/Field.php",
      "LegacySupport/GraphQl/ResolveInfo.php",
      "LegacySupport/GraphQl/ResolverInterface.php"
    ],
```

I have your extension installed in app/code. So it ignores those lines.
Maybe that's why you said that it worked for you guys.

**Comment by Frank-Magmodules** [comment]
Hi @DeLuuk, 

Yes seems like it. The recommend way for installing is using Composer or Magento Marketplace, see [WIKI](https://github.com/mollie/magento2/wiki). 

This is also the only way we implemented it in our testing workflow; https://github.com/mollie/magento2/actions

**Comment by DeLuuk** [comment]
Hey @Frank-Magmodules,

Oke from now on we'll install it with composer only.

Good to know!

**Comment by Frank-Magmodules** [comment]
Hi @tdgroot

Thanks again for sharing the GraphQL code!
Just a small update from our side that since version v1.15.0 we have added support for GraphQL.
More information about the flow can be found at; https://github.com/mollie/magento2/wiki/GraphQL-integration

Closing this issue now, but feel free to reopen.
