### ISSUE TITLE
Payment Fee is not working with Sofort

### ISSUE THREAD

**Issue by mtjweb** [mollie/magento2#219]
I applied a percentage payment fee to most of the payment options. All are working fine, but when selecting Sofort the payment fee is not applied.

**Comment by Frank-Magmodules** [comment]
@mtjweb,  thanks for opening this issue, we will investigate/reproduce this and let you know the outcome on this as soon as possible.

**Comment by Frank-Magmodules** [comment]
Hi @mtjweb, thanks again for the detailed issue report. The issue has been resolved in the [v1.12.0](https://github.com/mollie/magento2/releases/tag/v1.12.0) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.
