### ISSUE TITLE
Problem with installing mollie on magento 2

### ISSUE THREAD

**Issue by dennismorren** [mollie/magento2#22]
Hello Sir,

Please see attachment we have a problem with installing mollie 2 on magento 2.. i hope you can help
Thanks...
![mollieinstallatieprobleem](https://cloud.githubusercontent.com/assets/27417327/25001153/58bfa0d6-2044-11e7-9589-1cb46c0d83fe.png)

**Comment by Magmodules** [comment]
Hi, please run the composer command from the magento root folder (not /bin folder)

**Comment by dennismorren** [comment]
Hello sir thanks for your quick reply, but see image below
![aeef426a37a64fdab3264b57150eaded](https://cloud.githubusercontent.com/assets/27417327/25001930/f6e63fd8-2047-11e7-95bf-57996413f476.png)

**Comment by Magmodules** [comment]
Error message: "You must be using the interactive console to authenticate". 
To generate access keys, see: http://devdocs.magento.com/guides/v2.0/install-gde/prereq/connect-auth.html

**Comment by dennismorren** [comment]
Thanks! we have installed it and put in the live key.. but when we please an order and select ideal and go to proceed we get this fault...
Error executing API call (request): Unauthorized request.
![fault-mollie](https://cloud.githubusercontent.com/assets/27417327/25223191/f87475cc-25ba-11e7-94cc-f1cb370017ad.jpg)

**Comment by Magmodules** [comment]
Modus set to live?

**Comment by dennismorren** [comment]
Yes see
![modus-1](https://cloud.githubusercontent.com/assets/27417327/25224285/378d8944-25be-11e7-8adc-17a800edc672.jpg)

**Comment by Frank-Magmodules** [comment]
Hi Dennis Morren,

Please remove your screenshot with the API key from this discussion as soon as possible as it's not recommend sharing your Live API key publicly. Can you contact Mollie to make sure the API key is correct?

Thanks.

**Comment by ndijkstra** [comment]
Hi Dennis,

I can't find that API-key in our system. Can you check it in your account?
