### ISSUE TITLE
Unable to accept SEPA payments

### ISSUE THREAD

**Issue by StephanStanisic** [mollie/magento2#220]
Hi,

We are unable to fully process SEPA payments trough our magento webshop. When a customer selects the SEPA payment option everything goes all right. Since SEPA payments are processed overnight by most banks they can take some time to complete. The thing is the status of the order gets set to "cancelled" after only a couple of hours, and when the payment arrives magento has already cancelled the Mollie payment. This results in the amount getting refunded because the payment was no longer valid.

We are running the latest stable version of the plugin trough composer, with magento verison 2.2.2.

**Comment by Frank-Magmodules** [comment]
Hi @StephanStanisic, pending payments gets cancelled by Magento after a fixed period, that's why we advise to use a different status for these payments. This should pop-up when running the self test. 
Did you run this test?

**Comment by StephanStanisic** [comment]
I didn't see that pop up in the self test when I did it a long time ago (was this introduced in a newer version?)

I'll add a extra custom status, thank you for this fast response!

**Comment by StephanStanisic** [comment]
Does this warning show even if the bank transfer payment method is disabled? I think that's it's really easy to overlook this point in the self test, because I'd think to use the self test post install, not post configuration.

It might also be a good idea to mention the auto cancel issue on the hint below the select. It currently shows only that it is not visible on the fronted:

![](https://images.stanisic.nl/HYY11Moy/8FlWu51f)

Maybe document somewhere to run the self test after changing config? Maybe auto run it on save, and show the warnings in the magento error alerts?

These are just some idea's on how to make it more clear that you should change the status.

**Comment by Frank-Magmodules** [comment]
Hi @StephanStanisic, the warning is not shown if Bank transfer payment method is disabled. I agree with you that it's a good idea to mention the auto cancellation so the merchant is aware of the "why" of this function. Thank you for your feedback, we will definitely use it.

I'm closing this issue for now.
