### ISSUE TITLE
Magento checkout is broken on IE11

### ISSUE THREAD

**Issue by koenner01** [mollie/magento2#222]
mollie/magento2 payment plugin (using 1.11.0 but lower versions also have the problem) breaks the checkout when browsing in IE11.

The reason for the issue is found in "Mollie_Payment/js/view/checkout/summary/payment-fee" file where the function keyword is omitted from the initialize function (which is not supported by IE11)

```
...

initialize() {
    this._super();
    ...
```

**Comment by Frank-Magmodules** [comment]
Hi @koenner01 , thank you for opening this issue, we will investigate/reproduce this and let you know the outcome on this as soon as possible.

**Comment by Frank-Magmodules** [comment]
Hi @koenner01 , thanks again for the detailed issue report. The issue has been resolved in the [v1.11.1](https://github.com/mollie/magento2/releases/tag/v1.11.1) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.
