### ISSUE TITLE
Payment method mollie does not show up in store

### ISSUE THREAD

**Issue by tvriesde** [mollie/magento2#23]
Hi there,

I've installed the mollie  magento 2 plugin using composer. No errors everything installing as described in documentation. 

After enabling the payment method I can't seem to get the option available to the actual store front-end. (other payment methods like cash on delivery work fine after enabling and disabling them). 

<img width="1084" alt="screen shot 2017-04-17 at 22 56 07" src="https://cloud.githubusercontent.com/assets/14925251/25104631/57ed831e-23c1-11e7-9907-44b38082926d.png">
<img width="1047" alt="screen shot 2017-04-17 at 22 56 20" src="https://cloud.githubusercontent.com/assets/14925251/25104642/6752911e-23c1-11e7-933d-8cd8d0a6e19c.png">
<img width="811" alt="screen shot 2017-04-17 at 22 56 34" src="https://cloud.githubusercontent.com/assets/14925251/25104648/6bc12a58-23c1-11e7-97ab-951877fb512c.png">

<img width="388" alt="screen shot 2017-04-17 at 23 00 25" src="https://cloud.githubusercontent.com/assets/14925251/25104744/cfd0d50c-23c1-11e7-916d-721a00653bc8.png">

Tried flushing cache.

Am i missing some step required to actually get the mollie payment method available in store front-end?

**Comment by Magmodules** [comment]
Can you check for Minimum/Maximum Order Total and Payment from Applicable Countries settings? 
And also please double check the API key, same result when using the test key in test modus?

**Comment by tvriesde** [comment]
The API key is correct, for both test and live mode the plugin is not working.

These are my iDeal Min/Max Order Total settings & Applicable Countries settings.

![idealsettings](https://cloud.githubusercontent.com/assets/14925251/25143582/4db1f8e4-246b-11e7-9f5f-eda37c15c5c5.PNG)

**Comment by Magmodules** [comment]
Can you send me /var/log/mollie.log at info@magmodules.eu so we can check the log?

**Comment by tvriesde** [comment]
The /var/log/ directory only contains the files debug.log, exception.log and system.log.

**Comment by Magmodules** [comment]
Debug option is enabled in the Mollie extension?

**Comment by tvriesde** [comment]
Yes, 
"Debug requests	
When activated the debug file will be located in: var/log/mollie.log"

Is set to Yes all allong.

**Comment by Magmodules** [comment]
Strange, can you send us admin login details through https://www.magmodules.eu/contact-us.html so we can check this issue?
