### ISSUE TITLE
Webhook URL is invalid on local machine. How to test

### ISSUE THREAD

**Issue by falconmedia** [mollie/magento2#230]
I updated Magento v2.3.2 to v2.3.4 on my local machine.
Version 
"mollie/mollie-api-php": "^2.0",
"mollie/magento2": "^1.10",

When I test the API connection, it's seems ok..
[scheenshot](https://nimb.ws/yHtTlA)

When I do test payment with iDEAL I receive the following error inside Magento checkout 

[screenshot](https://nimb.ws/xQtDUT)

Error executing API call (422: Unprocessable Entity): The webhook URL is invalid because it is unreachable from Mollie's point of view.. Field: webhookUrl. Documentation: https://docs.mollie.com/guides/handling-errors

**Comment by Frank-Magmodules** [comment]
HI @falconmedia ,

Mollie requires a webhook URL that is reachable by the outside world, to push the updates on. From the documentation (https://docs.mollie.com/reference/v2/payments-api/create-payment):

> The webhookUrl must be reachable from Mollie's point of view, so you cannot use localhost. If you want to use webhook during development on localhost, you must use a tool like ngrok to have the webhooks delivered to your local machine.

Also, see this page;
https://help.mollie.com/hc/en-us/articles/213470409-My-webhook-URL-is-invalid-or-not-working-What-is-the-problem-

Frank

**Comment by mateuszrusiecki** [comment]
So in docs there stands "The webhookurl is optional" but apparently it's not :/ 
There should be a way to set it manually or whatever jus to make it work locally!

**Comment by Frank-Magmodules** [comment]
Hi @mateuszrusiecki, thank you for the reply. The doc that you seem referring to is the documentation about the Mollie API and not the Mollie Magento 2 module. 

To get this running you need to make your local env accessible form the outside. You can use a service like https://ngrok.com for this. See also the post above your comment: "https://help.mollie.com/hc/en-us/articles/213470409-My-webhook-URL-is-invalid-or-not-working-What-is-the-problem"

**Comment by mateuszrusiecki** [comment]
Using an external service is not a valid solution. If I would need to setup some external service for every single plugin I use, then working this way would be a nightmare! It should be configurable in the plugin settings. At least the error should indicate, that it won't work on localhost without external service

**Comment by evs-xsarus** [comment]
@mateuszrusiecki see #263 to make a workaround.

**Comment by mateuszrusiecki** [comment]
yeah, I saw it. Great job!
