### ISSUE TITLE
BC break 1.11.0

### ISSUE THREAD

**Issue by Swahjak** [mollie/magento2#232]
I think there should be a **big** BC break warning on 1.11.0 since it introduces a `paymentToken` requirement on the redirect url. We've been using Mollie with API since the beginning by simply redirecting customers to `mollie/checkout/redirect` if the payment method was provided by mollie. But now all of a sudden we require a `paymentToken`. There isn't even a mention of this in the release notes. This can (potentially) break custom checkout implementations.

Might be related to #228

Edit: my bad, this seems to be related to 1.11.0 which does have a 'tiny' mention of a 'Improved Checkout flow'.

**Comment by Swahjak** [comment]
On a side note; is there a particular reason why a `paymentToken` is required? Why not use the session like it used to? Or at least fallback to the session if a token is not provided.

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak ,

The reason for this is that we've had issuers where users would place the order and get redirected to the mollie/checkout/redirect, but there the session was empty. 

By using the payment token method this issue is resolved as it doesn't depend on the session anymore. Also, the payment token is used in the REST API and the upcoming GraphQL support. 

https://github.com/mollie/magento2/wiki/PWA-integration

**Comment by Swahjak** [comment]
Hi @Frank-Magmodules,

Ok, but that's a **big** BC for anybody not using the (bloated, opinion) Magento 2 checkout. It would be nice if these kind of BC breaks would be clearly visible in the release notes. PWA is all nice and well, but a long way from being mainstream.

Secondly you kind of fixed 'some issues' by introducing a completely new "dependency". Why not use the order id returned by https://devdocs.magento.com/guides/v2.3/rest/tutorials/orders/order-create-order.html#send-payment

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak ,

The order id isn't used for the same reason Magento uses a masked id for the quote: For security reasons.

Mollie has several merchants running on different PWA systems which we are happy to serve as well, even it's not mainstream we do want to implement this for these Merchants.

**Comment by Swahjak** [comment]
@Frank-Magmodules didn't mean to offend you on the PWA system. I'm just trying to make a point about BC breaks not clearly highlighted. I'm prone to say; Then why not use the masked quote id since by this point it will be mapped to the order. I get why you (or a collegae) did what you did, but to me it seems like an unnecessary extra step in a already complex flow of API calls. Or a combination of order id and (if not logged in) a masked quote id. Both are readily available without any modifications or additions to the existing API.

**Comment by michielgerritsen** [comment]
Hello @Swahjak,

We don't use masked id as it is connected to a quote, and there can be multiple orders connected to a single quote. It doesn't happen much, but this makes sure we are processing the correct order.

About the release notes: I agree with you that adding a backward compatibility warning is a good idea. I will make sure this will get added.
