### ISSUE TITLE
Possible bug banktransfer order status

### ISSUE THREAD

**Issue by Swahjak** [mollie/magento2#233]
So, we've been looking in to a issue we've been having related to banktransfer payments not receiving the correct status and being canceled because of not having the correct status (my collegae has already been in contact over the phone).

## Steps to reproduce
I think I narrowed the issue down to a reproducible issue:
1. Place an order using banktransfer as the payment method
2. Continue to the Mollie page with transfer details
3. Do **not** continue to the webhop

### Expected result
The order has custom `pending_mollie` status

### Actual result:
The order still has the `pending_payment` status

## Cause
This wil cause issues because the payment / order is never processed by the mollie Checkout/Success controller. The controller calls the Client/Payment or Client/Order which has the following (critical bit of) code in it https://github.com/mollie/magento2/blob/master/Model/Client/Orders.php#L459. Without calling this method the order will remain in a `pending_payment` status instead of a custom status `pending_mollie`. Which, as it was explained to us, will cause the order to be canceled after a certain period of time.

## Possible solution
- Set the correct state on the order during placement.
or
- Trigger a webhook which causes the order to be processed

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak , thanks again for the detailed issue report. The issue has been resolved in the [v1.12.1](https://github.com/mollie/magento2/releases/tag/v1.12.1) release. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by Swahjak** [comment]
He @Frank-Magmodules I might be overlooking something, but it seems to me that step 3 would still cause the same issue. Based on the changes in https://github.com/mollie/magento2/pull/238/files one would still need to reach either the Payments or Orders client before the status is applied, which is not the case if you do not proceed to checkout. Unless Mollie has made a change in their webhook triggers.

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak , status is set before the customer is redirected to mollie, so this does not depend on the webhook.

**Comment by Swahjak** [comment]
@Frank-Magmodules my bad, mixed up `processTransaction` with `processResponse`.
