### ISSUE TITLE
Beste manier voor custom functionaliteit na betaling

### ISSUE THREAD

**Issue by PieterCappelle** [mollie/magento2#24]
Hallo,

Wat is volgens jullie de beste manier om custom functionaliteit te ontwikkeling na ontvangen van een betaling. Bv e-mail naar verschillende leveranciers. Je zou in Magento 2 een plugin kunnen ontwikkelen rond de functie `processTransaction` `https://github.com/mollie/magento2/blob/55cc5f262584f7e6dcb1aeb99907819a23aa21d0/Model/Mollie.php#L299` (bv: afterProcessTransation() en daar kijken of de betaling wel is uitgevoerd geweest. Is er een reden waarom jullie geen event triggeren?

Misschien hebben jullie een beter voorstel?

Alvast bedankt!

**Comment by Magmodules** [comment]
Hi Pieter, sales_order_invoice_pay?
