### ISSUE TITLE
Class Mollie\Api\Resources\PaymentFactory does not exist

### ISSUE THREAD

**Issue by sumeetmobiwebtech** [mollie/magento2#241]
i am getting this error when install this extension from magento marketplace

Class Mollie\Api\Resources\PaymentFactory does not exist

**Comment by Frank-Magmodules** [comment]
Hi @sumeet,

It looks like the Mollie API was not installed. This is bundled with the Marketplace Release. Was the installation successful or did it throw an error? Can you try and reinstall it using the Marketplace?

If you need help with this, please contact us through our [contact form](https://www.magmodules.eu/support-form.html) so we can exchange log files/ login details to check and fix this issue.

Frank

**Comment by davidduong90** [comment]
I have downloaded your extension from https://marketplace.magento.com/mollie-magento2.html, And I have same this issue. Do you have any solution for it?

**Comment by Marvin-Magmodules** [comment]
Hi @davidduong90, looks like it did not install the Mollie API. The module can be installed using [composer](https://github.com/mollie/magento2/wiki/Installation-using-Composer) or with the use of the [Magento Extension Manager](https://github.com/mollie/magento2/wiki/Installation-using-Marketplace). If you install it using FTP, you also need to install the Mollie API as this is required.

**Comment by davidduong90** [comment]
Thank you! I have can't install Mollie API use composer. Do you know another way to install it?

**Comment by Frank-Magmodules** [comment]
Hi @davidduong90 ,  If you can't install it through composer you can also use  the [Magento Extension Manager](https://github.com/mollie/magento2/wiki/Installation-using-Marketplace).
