### ISSUE TITLE
Magento 2.3.4 with new mollie version issues ideal

### ISSUE THREAD

**Issue by digikeijs** [mollie/magento2#243]
Issue comes up with composer update to 1.12.1, when I downgrade to v1.11.1 te issue is gone

define(['ko','jquery','Mollie_Payment/js/view/payment/method-renderer/default'],function(ko,$,Component){var checkoutConfig=window.checkoutConfig.payment;'use strict';return Component.extend({defaults:{template:'Mollie_Payment/payment/ideal',selectedIssuer:null},getForm:function(){return $('#'+this.item.method+'-form');},getIssuers:function(){return checkoutConfig.issuers[this.item.method];},getIssuerListType:function(){return checkoutConfig.issuersListType[this.item.method];},getSelectedIssuer:function(){if(this.getIssuerListType()==='radio'){return $('input[name=issuer]:checked',this.getForm()).val();}
if(this.getIssuerListType()==='dropdown'){return this.selectedIssuer;}},getData:function(){return{'method':this.item.method,'additional_data':{"selected_issuer":this.getSelectedIssuer()}};},validate:function(){var $form=this.getForm();if(this.getIssuerListType()==='radio'){return $form.validation()&&$form.validation('isValid');}
return $form.validation();}});});

**Comment by digikeijs** [comment]
![Mollie](https://user-images.githubusercontent.com/34745091/79116247-41bab200-7d88-11ea-97f0-5435e75d088c.PNG)

**Comment by icetexnl** [comment]
Ik heb hetzelfde probleem! Bezoekers kunnen niet meer betalen via iDeal en KBC/CBC!!

![Schermafbeelding 2020-04-15 om 17 07 30](https://user-images.githubusercontent.com/13218640/79353920-0234c700-7f3c-11ea-8297-a6c623a7eb2d.png)
![Schermafbeelding 2020-04-15 om 17 07 39](https://user-images.githubusercontent.com/13218640/79353925-0365f400-7f3c-11ea-8d88-fd8e8390f54a.png)

**Comment by Margero** [comment]
Ik heb hetzelfde probleem met Ideal. Heel veel klanten klachten dat ze niet kunnen betalen.

**Comment by lisabisshops** [comment]
Wij hebben ook hetzelfde probleem (Magento 2.3.4). Bij downgrade naar 1.11.1 is het probleem niet aanwezig.

**Comment by digikeijs** [comment]
@icetexnl @Margero 

ik neem aan dat jullie altijd eerst zelf testen op een development of test omgeving? :-)

**Comment by Frank-Magmodules** [comment]
Hi @digikeijs , @icetexnl , @Margero  en @lisabisshops ,
Thanks for reporting this issue. We just released a new version (v1.12.2) which fixes this issue. This error only occurs when the methods that use issuers (iDeal, KBC and Giftcards) were limited to specific countries. In this new release, this is fixed by always including the issuers when the method is available. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by digikeijs** [comment]
@Frank-Magmodules Thank it's fixed!
