### ISSUE TITLE
Error doing online refund 

### ISSUE THREAD

**Issue by Daniel304** [mollie/magento2#246]
Everything is updated to latest version when i try to do a refund of a memo it will throw the following error.
Error: not possible to create an online refund: Error executing API call (422: Unprocessable Entity): The specified amount cannot be refunded. Field: amount.value. Documentation: https://docs.mollie.com/guides/handling-errors

**Comment by Frank-Magmodules** [comment]
Hi @Daniel304 ,

Seems we can't reproduce this in our test environments. 
Can you please contact us through our [contact form](https://www.magmodules.eu/support-form.html) so we can exchange;

- Mollie Logfile from /var/log/mollie.log
- Order Details

So we can help you out with this. Please share the exact steps on reproducing this issue, the more information the better.
Thanks,

Frank

**Comment by Daniel304** [comment]
Can be closed... somehow someone did an online refund in mollie itself..
