### ISSUE TITLE
No compatiblity with Magento 2.1.x

### ISSUE THREAD

**Issue by DeLuuk** [mollie/magento2#247]
Mollie isn't compatible anymore. Since this commit https://github.com/mollie/magento2/commit/95a6417ef232df3947bfdaa8b9c87ddfb240f42b it's using `Magento\Framework\Api\SearchCriteria\CollectionProcessorInterface;`.

Which isn't present in any 2.1.x version. My client is using 2.1.16 right now and it creates an error while compiling:
```
Compilation was started.
Area configuration aggregation... 5/7 [====================>-------]  71% 29 secs 190.0 MiB
                                                                                          
  [ReflectionException]                                                                   
  Class Magento\Framework\Api\SearchCriteria\CollectionProcessorInterface does not exist  
                                                                                                                                                                      
  [ReflectionException]                                                                   
  Class Magento\Framework\Api\SearchCriteria\CollectionProcessorInterface does not exist  
```

**Comment by DeLuuk** [comment]
Mollie isn't compatible anymore. Since this commit https://github.com/mollie/magento2/commit/95a6417ef232df3947bfdaa8b9c87ddfb240f42b it's not using `use Magento\Framework\Api\SearchCriteria\CollectionProcessorInterface;`.

Which isn't present in any 2.1.x version. My client is using 2.1.16 right now and it creates an error while compiling:
```
Compilation was started.
Area configuration aggregation... 5/7 [====================>-------]  71% 29 secs 190.0 MiB
                                                                                          
  [ReflectionException]                                                                   
  Class Magento\Framework\Api\SearchCriteria\CollectionProcessorInterface does not exist  
                                                                                                                                                                      
  [ReflectionException]                                                                   
  Class Magento\Framework\Api\SearchCriteria\CollectionProcessorInterface does not exist  
```

**Comment by Frank-Magmodules** [comment]
Hello @DeLuuk,

Unfortunately, we are not able to fix this issue and support Magento 2.1, 2.2, and 2.3 at the same time. That's why we decided to drop the support for Magento 2.1 earlier than planned.

You can use [version 1.11.0](https://github.com/mollie/magento2/releases/tag/v1.11.0) which still is compatible with Magento 2.1, but we strongly advise you to update the Magento installation to a newer version as Magento 2.1 has reached its end of life almost a year ago.

I will make sure we will add a warning in the release notes about dropping Magento 2.1 support.

**Comment by DeLuuk** [comment]
Hey @Frank-Magmodules,

That sucks then!

But why does it say `Mollie for Magento 2.x` then on the home page.
In my opinion that needs to be changed to 2.2 and 2.3 to be fair.

**Comment by Frank-Magmodules** [comment]
@DeLuuk ,

Good point, I'll have it adjusted right away!
