### ISSUE TITLE
Mollie not visible as payment on front.

### ISSUE THREAD

**Issue by lucvdbos** [mollie/magento2#25]
Mollie is setup as described. 

On the back-end it's enabled. See:
[Configuration - Settings - Stores - Magento Admin.pdf](https://github.com/mollie/magento2/files/1050741/Configuration.-.Settings.-.Stores.-.Magento.Admin.pdf)

But on front I can't choose Mollie as payment provider. 
[Checkout.pdf](https://github.com/mollie/magento2/files/1050743/Checkout.pdf)

What could be the problem?

Kind regards,

**Comment by magmodules** [comment]
The PDF's are empty, so I'm not able to check the settings. Is the base currency set to Euro (Mollie only accepts EUR) and what are the results of the selftest from the admin?

**Comment by lucvdbos** [comment]
Thank you for your replay. 

Yes the base currency is Euro and the selftest has succeed.See attachment. (I hope you can see it now.
![configuratie settings stores magento admin](https://cloud.githubusercontent.com/assets/680434/26774372/44579d3c-49d0-11e7-9c6d-d309f16aba75.png)

**Comment by magmodules** [comment]
Kan je eens kijken in var/log/mollie.log welke meldingen er staan?

**Comment by lucvdbos** [comment]
Het zegt:

[2017-06-04 18:56:59] Mollie.ERROR: error: Invalid Mollie API key.

Ik zag deze nogmaals kopiëren en kijken of dat het probleem oplost.

**Comment by lucvdbos** [comment]
ik heb de gegevens aangepast, maar ik zie geen verschil. In zowel de test als productie geen betalingsmogelijkheid zichtbaar. Geeft wel weer in productie dat er bepaalde betaalopties niet bruikbaar zijn, omdat deze niet aan staan in bij Mollie. 

Cache ook geupdate.

**Comment by lucvdbos** [comment]
Melding [2017-06-05 07:37:37] Mollie.ERROR: error: Invalid Mollie API key.  blijft overigens.

**Comment by magmodules** [comment]
Beste is om morgen even contact op te nemen met Mollie, zoals de error aangeeft wordt de API key niet geaccepteerd.

**Comment by lucvdbos** [comment]
Wel vreemd, omdat ik ook een nieuwe API key heb aangemaakt waar deze ook niet op werkt. Ik heb hem nog even op een andere site getest en daar werkt deze wel.

**Comment by magmodules** [comment]
Melding geeft echt aan dat hij invalid is, komt terug van de API. Wellicht heb je hem anders ingesteld op storeview of klopt de combinatie met LIVE/TEST niet. Verder even zorgen dat na aanpassingen wel de cache geflushed wordt.

**Comment by hostep** [comment]
(Compleet ongerelateerd, maar @lucvdbos: ik zou sterk aanraden om je screenshot hierboven te verwijderen of te wijzigen, want helemaal onderaan is de url naar je admin backoffice duidelijk zichtbaar. Wat een security risico inhoudt, aangezien dat een url is die je liefst verborgen houdt om brute force login pogingen tegen te gaan. Wou ik gewoon even meegeven... :) )

**Comment by lucvdbos** [comment]
Thanks. Dat was mij niet opgevallen.

**Comment by magmodules** [comment]
Is deze issue inmiddels opgelost?

**Comment by lucvdbos** [comment]
Ik vermoed dat het een cache issue was


Op 9 jun. 2017 3:12 p.m. schreef "Magmodules" <notifications@github.com>:
