### ISSUE TITLE
Enable the Second Change email also for cancelled orders

### ISSUE THREAD

**Issue by gerben86** [mollie/magento2#252]
If the customer cancels the payment (or if it's timedout and cancelled by Mollie) I still want to give him a second change.
Please add the feature to send the customer also in case of a cancelled order a second change mail.
This means that also the ordered products should be available and the payment/checkout url should work.

I did a quick check by updating SecondChange.php and SecondChangeButton.php, that showed the button and send the mail. But there were no products in the mail and also the checkout-url failed...

Could you enable the Second Change button also in case of an order with the Cancelled-status?

Thanks in advance!

Ps. I also saw that I was redirect to the payment method and bank I selected in the initial checkout. Maybe it's better / more customer friendly to let the customer choose from all the available payment methods again. Just like in the checkout.

**Comment by Frank-Magmodules** [comment]
Hi @gerben86, thank you for the feature request! We need some time to look into this and discuss this internally. Hopefully have an outcome by the end of next week.

**Comment by Frank-Magmodules** [comment]
Hi @tdgroot

Thanks again for sharing the GraphQL code! 
Just a small update from our side that since version [v1.15.0](https://github.com/mollie/magento2/releases/tag/v1.15.0) we have added support for GraphQL. 
More information about the flow can be found at; https://github.com/mollie/magento2/wiki/GraphQL-integration

Closing this issue now, but feel free to reopen.

**Comment by Frank-Magmodules** [comment]
Hi @gerben86,
We are happy to share that we've just released the new [1.20.0](https://github.com/mollie/magento2/releases/tag/v1.20.0) version with this feature. Thank you again for the detailed reports and patience.

**Comment by gerben86** [comment]
Super, thanks!

Op ma 14 dec. 2020 om 15:39 schreef Frank Tiggelman <
notifications@github.com>:
