### ISSUE TITLE
Add sortorder Klarna Pay Later

### ISSUE THREAD

**Issue by xsa-svh** [mollie/magento2#255]
Most of the payment methods are able to be placed on various locations on the payment page based on the sortorder. This is not available for the Klarna payment method.

**Comment by Marvin-Magmodules** [comment]
Hi @xsa-svh, what version of the module are you running at this moment? As this was fixed in 1.13.0, see [changelog](https://github.com/mollie/magento2/releases/tag/v1.13.0).

**Comment by xsa-svh** [comment]
We are using, version 1.12, this explains it. Thx for the quick feedback.
