### ISSUE TITLE
Cannot read property 'terms_and_conditions' of undefined

### ISSUE THREAD

**Issue by alberthoekman** [mollie/magento2#26]
When I try to click the 'place order' button. I get the following error in my console. 

![screen shot 2017-06-01 at 11 01 25](https://cloud.githubusercontent.com/assets/6929265/26821495/e49f5790-4aa6-11e7-97b2-de92c3fe0b11.png)

**Comment by magmodules** [comment]
"terms_and_conditions" is not something the Mollie extensions adds/touches. Can you disable all other payment extensions (module disable), flush cache, run static content deployment en try again to see if the problem still exists.

**Comment by alberthoekman** [comment]
Thanks for the answer. I will take a look at it.

**Comment by alberthoekman** [comment]
It's fixed. Thanks for the help.

**Comment by magmodules** [comment]
Can you elaborate how it is fixed?

**Comment by alberthoekman** [comment]
Yes, for some reason the AfterPay payment method was interfering with yours. After turning it off, it worked. I reinstalled the AfterPay plugin and the problem is resolved.
