### ISSUE TITLE
No Mollie payment options visible

### ISSUE THREAD

**Issue by dbroeders** [mollie/magento2#264]
After update to an bigger server (we decided to update to Centos 8)
Updated Magento also to 2.3.5-p1
And therefore Mollie needed to be updated too 1.12.2

Now the Mollie payments are not visible any more on frontend.
We did the normall Mollie update by composer.

Test Api are success 
Self test is ok.
Success: PHP version: 7.3.19.
Success: JSON is enabled.

**Comment by Frank-Magmodules** [comment]
Hi @dbroeders , 

Can you update to the latest version and let us know if this solves the issue? 
If not, please contact us through our [contact form.](https://www.magmodules.nl/support-form.html)

**Comment by dbroeders** [comment]
We have updated to the last Mollie 1.14 and deleted all cache from Chrome explorer.
Now all works fine.
