### ISSUE TITLE
Hash for thankyou page PWA integration

### ISSUE THREAD

**Issue by DaanKouters** [mollie/magento2#265]
# Describe the new feature
a string in the uri of the thankyou page with a hash string of order_id and secretkey
As far as i saw, there is no direct link between order and payment token? When i fetch a backend order by the order_id the payment_token is not in the dataset.

## Describe the solution to be implemented
Now the order_id and payment_token are exposed, there is no acute security risk. But it's nicer if there is a hash. On the thank you page in the PWA of choice this hash can be deciphered to retrieve the order_id and with this id you can fetch the order details and payment status.

In the backend settings of the module i see an input field where you can put in a random secret key for hashing the order id.
And an extra endpoint to decipher this hash and get the order details and payment status.

thank your page url can be: http://pwa-solution.io/thank-you/{{ORDER_ID_HASH}}

**Backend changes**
ideally an input field for a secret key to generate hash
and also a input field for custom thank you page with placeholder for hash (http://pwa-solution.io/thank-you/{{order_id-hash}} 
an extra api endpoint to decipher the hash to get order details

**Frontend changes**
For the PWA of choice a call to the backend layer (pwa api) to decipher the hash and retrieve the order id in order to fetch the order details.
With this information we can notify the current status of the payment to the user / customer.

**Comment by Marvin-Magmodules** [comment]
Hi @DaanKouters, 

Thanks for contacting us and committing this feature request. The order_id and payment_token is indeed automatically appended to the "thankyou "-url. We will look into this to make this dynamic and think of setting up an extra endpoint to load the order using the payment_token so there will be no need to rely on order_id.

Will update this issue report once we have discusses this internally.

**Comment by Frank-Magmodules** [comment]
Hi @DaanKouters, we are happy to share that we've just released the new [1.16.0](https://github.com/mollie/magento2/releases/tag/v1.16.0) version that has improvements for the custom return URL. An order hash can be added to the return URL that can be used to [fetch](https://github.com/mollie/magento2/commit/b268aa0641f957afdf0d3e18cfc7d36f5a79f42b#diff-ad789454fbee3e2ca87c33fcf8577749R15) some basic order details (see: https://github.com/mollie/magento2/commit/b268aa0641f957afdf0d3e18cfc7d36f5a79f42b#diff-6085ef7e6400732a0d53f89725dd53ddR40) to be shown on the success page of the PWA.
