### ISSUE TITLE
Surcharge as total segment

### ISSUE THREAD

**Issue by DaanKouters** [mollie/magento2#266]
# Describe the new feature
Add surcharge as a total segment to shipping information endpoint resultset

## Describe the solution to be implemented
Would like to see the surcharge amount (if any) gets added to the total segments in the shipping information api endpoint resultset for displaying the surcharge in a PWA (api driven).

**Backend changes**
Unknown

**Frontend changes**
In the PWA of choice collect new totals on every payment method switch - (has to be done in the PWA frontend, not in this module)

**Additional context**
-

**Comment by Frank-Magmodules** [comment]
Hello @DaanKouters ,
Thank you for opening this request. 
Could you elaborate on why this is needed? What are you trying to achieve exactly?

Thanks!

**Comment by DaanKouters** [comment]
hi @Frank-Magmodules , sure
we are building a PWA with Vue Storefront and magento 2 as a backend with mollie as payment provider.

In the checkout the totals are being fetched from the magento 2 rest api on some events. Like for instance change for shipping methods (to add shipping costs to total summary) or payment methods. 

I would like to see the surcharge costs for the chosen payment method (if any) as a separate line in the total summary. In the swagger docs of magento rest api it's described that this can be a 'total_segment'. let me know if you need more information about this.

**Comment by Frank-Magmodules** [comment]
Hi @DaanKouters ,

Thank you for the explanation of this. We have created an internal task for this feature request and will try to come back on this as soon as possible.

**Comment by DaanKouters** [comment]
> Hi @DaanKouters ,
> 
> Thank you for the explanation of this. We have created an internal task for this feature request and will try to come back on this as soon as possible.

hi @Frank-Magmodules - is there any update about his feature request?

**Comment by Frank-Magmodules** [comment]
Hi @DaanKouters, thank you for your message but unfortunately, I don't have any update for you at this moment, sorry for that. For now, we have some other features that have been prioritized by Mollie that we are implementing at this moment. Once these are done we have time to look into this feature and sent you an update once there.

**Comment by Frank-Magmodules** [comment]
Hi @DaanKouters,
One of our developers had contact with you through Slack regarding this issue a few months ago but due inactivity regarding that topic we are closing this issue now but please feel free to reopen the issue if this still occurs.
