### ISSUE TITLE
Cannot activate SEPA Direct Debit

### ISSUE THREAD

**Issue by tropilex** [mollie/magento2#270]
Problem: Cannot activate SEPA Direct Debit **"Directdebit: method not enabled in Mollie Dashboard"**

![Screenshot 2020-07-02 at 22 16 41](https://user-images.githubusercontent.com/53861858/86405668-0908e580-bcb2-11ea-9b07-012fb9037ad0.png)

But Direct Debit is activated in the Mollie Dashboard. Even had contact with Mollie to higher the debit amount.

![Screenshot 2020-07-02 at 22 17 22](https://user-images.githubusercontent.com/53861858/86405663-08704f00-bcb2-11ea-80be-68fae498417a.png)

API key and Profile ID are correct. Checked them multiple times, and all other payment methods are working fine with that API. 

I tried everything: added the credentials on website and store view level. Removed credentials, added them again.

The API test in Magento is also not showing SEPA Direct Debit as payment method.

![Screenshot 2020-07-02 at 22 22 28](https://user-images.githubusercontent.com/53861858/86406039-b976e980-bcb2-11ea-8403-02d66a7550eb.png)

I contacted Mollie but they also don't know why it's not working: my Mollie account is ok and the method is activated is what they say to me.

**Magento version: 2.3.5-p1
Mollie plug-in: 1.14**

**Comment by Frank-Magmodules** [comment]
Hi @tropilex 

Thank you for opening this issue. SEPA is a quite manual process to activate from Mollie's side, so I think that some permissions are not set right in your Mollie account. Can you contact us through our [contact form](https://www.magmodules.nl/support-form.html) and share your Mollie details so I can check this for you?

**Comment by tropilex** [comment]
@Frank-Magmodules Done.

**Comment by tropilex** [comment]
It's solved. Error at/by Mollie in the back-end.
