### ISSUE TITLE
Not possible to continue checkout on IE11 using CC Components

### ISSUE THREAD

**Issue by mborkowski** [mollie/magento2#271]
Hello,
We're using 1.15.0 on Magento 2.3.4-p2 currently and during QA we found out that JS error popping up on IE11 will never let customer to finish checkout because of locked overlay loader. 
![IE_mollie](https://user-images.githubusercontent.com/7046321/86451573-64bb8900-bd1b-11ea-936d-9acb4317b06c.png)

It's hard to debug due to minification, but it looks like you're trying to call some method without parameter which is optional for modern browsers but seems to be still required for IE11.
Screenshot comes from out theme, but we were able to reproduce with clean theme too

**Comment by willemstuursma** [comment]
Thanks for opening this issue. We are aware of this IE11 issue with our Mollie Components JS and we are working on a solution.
We have created an internal task for this issue and will try to come back on this as soon as possible. Thank you for your patience!

**Comment by Marinolinderhof** [comment]
Hi @mborkowski We deployed a fix all should be working fine now.
