### ISSUE TITLE
Error executing API call, the 'name' field is missing on German storeview using Klarna Pay After

### ISSUE THREAD

**Issue by LucasMDL** [mollie/magento2#273]
When using Klarna pay after on a German storeview this error shows up after  placing an order. On the Dutch storeview it works fine without error. The only difference I is the name and id of the region field.

>  Error executing API call (442: Unprocessable Entity': Order line 3 is invalid. The 'name' field is missing.

**Used versions**
- Magento 2.3.5 Open Source:
- Mollie Version 1.14.0

**To Reproduce**
1. Enable Klarna Pay After for a German storeview
2. Place an order on a German storeview using Klarna Pay After
3. See error

**Screenshots**
https://www.screencast.com/t/QOuy2BfU

**Comment by Frank-Magmodules** [comment]
Hi @LucasMDL ,
Thank you for opening and reporting this issue. Can you please share the /var/log/mollie.log file through our [contact form.](https://www.magmodules.nl/support-form.html) so we can take a look with you on this and help you solve this issue?
Thanks again!
