### ISSUE TITLE
Add shipping costs to payment fee calculation

### ISSUE THREAD

**Issue by mtjweb** [mollie/magento2#275]
**Describe the bug**
When a payment fee is applied, it is only calculated over the total amount of the products. The payment fee is not applied on the shipping costs.

**Used versions**
- Magento Version 2.3.5-p1
- Community
- Mollie version 1.15.0

**To Reproduce**
Place an order with shipping costs and select a payment option with a payment fee.

**Expected behavior**
Payment fee calculated over subtotal and shipping costs.

**Comment by Frank-Magmodules** [comment]
Hi @mtjweb , 

Thank you for opening this issue. Yes, this is the correct handling, for the calculation of the fee the base total is used. We will discuss this internally to see if we can add an option to also include the shipping into the mix. Thank you for your contribution.

**Comment by Frank-Magmodules** [comment]
Hi @mtjweb 
We are happy to share that we've just released the new [1.15.1](https://github.com/mollie/magento2/releases/tag/v1.15.1) version with a new option for this. See;
<img width="714" alt="Schermafbeelding 2020-07-10 om 15 51 24" src="https://user-images.githubusercontent.com/24823946/87165288-3a913a80-c2ca-11ea-96e3-3f58b7bda525.png">


Thank you again for requesting this feature.
We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by mtjweb** [comment]
Great thanks
