### ISSUE TITLE
Ideal issuer list does not work

### ISSUE THREAD

**Issue by Sil-B** [mollie/magento2#276]
**Describe the bug**
The iDeal issuer list does not work in dropdown or list mode. 

**Used versions**
- *2.3.5-p1*:
- *Open source*:
- *Mollie version number 1.15.0*:
- *Native checkout and Sendcloud 1.3.0*:

**To Reproduce**
1. Set Mollie iDeal settings Issuer list style to dropdown or list mode 
2. Clear Magento cache
3. Go to checkout page 2 native magento checkout (production mode)
4. Choose iDeal
5. The dropdown does not work OR the list is not shown
6. You can still checkout

**Expected behavior**
We expect the list of iDeal issuers in list mode or dropdown

**Actual behavior**
The dropdown does not work OR the list is not shown. But you can still checkout. 

**Screenshots**
![image (2) (2)](https://user-images.githubusercontent.com/15123701/86894567-85ad2100-c103-11ea-8c69-2c6f41228638.png)

**Additional context**
Checked this on Mac with all major browsers. No difference. 
No errors in the Magento error logging.

**Comment by Frank-Magmodules** [comment]
Hi @Sil-B ,
Thanks again for opening the issue. I've been able to reproduce this and have placed this on our backlog. We will work on a solution and release it in an upcoming release. Thank you for your patience.

**Comment by Frank-Magmodules** [comment]
Hi @Sil-B,
We are happy to share that we've just released the new [1.15.1](https://github.com/mollie/magento2/releases/tag/v1.15.1) version with a fix for this issue. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
