### ISSUE TITLE
Install Mollie without command prompt

### ISSUE THREAD

**Issue by DHanibals** [mollie/magento2#28]
Hello,

How can I install Mollie without command prompt (SSH)?

Thank you for your advice.

Kind Regards,

D. Hanibals

**Comment by magmodules** [comment]
Not at this moment, but it will be available on the Magento Marketplace soon.

**Comment by DHanibals** [comment]
What will be soon?

I also read this at the beginning of this year.

**Comment by magmodules** [comment]
Hi @DHanibals ,
I hope just a few weeks but as it's still in "review" on the Magento Marketplace, it's difficult to say as we don't have any influence on this.

**Comment by magmodules** [comment]
Hi @DHanibals, the submission process is taking some time, lots of extensions in the que. You can send us a request at https://www.magmodules.eu/contact-us.html for installation.
