### ISSUE TITLE
[IE11] Cannot switch payment method when using CC Components

### ISSUE THREAD

**Issue by mborkowski** [mollie/magento2#280]
**Used versions**
Magento 2.3.5-p (EE)
Mollie 1.15.1

**Describe the bug**
Cannot switch payment method due to JS error.
Your script is actually not compatible with IE11, you're using methods that are not supported. 

**To Reproduce**
1. Go to Checkout
2. Fill address or use your account
3. While being on the Payment  step and having multiple payment methods available, selec Mollie CC method and then switch  to any other
4. Content of selected payment method stays invisible, because of error: 
![image](https://user-images.githubusercontent.com/7046321/87763199-b03e5e80-c814-11ea-9886-87f79ca7e478.png)

Childnode.remove() is not supported in IE11, please see reference: https://developer.mozilla.org/pl/docs/Web/API/ChildNode/remove

**Expected behavior**
Payment methods are switched correctly, its contents are visible on every payment method switch, error does not pop up on any browser.

**Comment by Marvin-Magmodules** [comment]
Hi @mborkowski, 

Thank you for the issue report. This JS is hosted by Mollie so we have asked them to look into this. In the meantime you can disable the use of Mollie Components, this will redirect the customers to Mollie to enter their CC data and will fix the issue. Will notify you when this has been fixed.

**Comment by Marinolinderhof** [comment]
Hi @mborkowski, yes we recognise this. Sorry for the inconvenience it causes you. We will take a look at it right a way.

**Comment by Marinolinderhof** [comment]
We deployed a fix. Thanks again for reporting.
