### ISSUE TITLE
Multistore admin payment link not shown

### ISSUE THREAD

**Issue by downforce80** [mollie/magento2#281]
**Describe the bug**
In multi webshop magento envoirement the admin mollie payment link is not shown in transactional sales order email.

**Used versions**
- Magento 2.3.5p
- Community
- Mollie version 1.1.13 ~1.1.15
- Multi store config

**To Reproduce**
1. Go to stores > configuration > sales > payment methods > mollie
2. Make sure you've selected default scope in the top of the screen
3. Set: Payment Link / Admin Payment enabled value to no
4. Save config
5. Switch to second website scope in top of screen
6. Set: Payment Link / Admin Payment enabled value to yes
7. Set Add Link to Payment Details to vaule Yes 
8. Save config

**Expected behavior**
Mollie payment is shown in transactional sales order email to customer

**Additional context**
Problem is solved when setting default config scope enabled to yes and set Add Link to Payment Detailt to value: Yes

**Comment by Frank-Magmodules** [comment]
Hi @downforce80, thank you for the detailed issue report! We are happy to share that we've just released the new [1.16.0](https://github.com/mollie/magento2/releases/tag/v1.16.0) version with a fix for this issue. We are closing this issue now but please feel free to reopen the issue if this still occurs.
