### ISSUE TITLE
Klarna after pay Refund / Creditmemo

### ISSUE THREAD

**Issue by Margero** [mollie/magento2#283]
**Describe the bug**
When you do a refund and the costumer used klarna after pay the order status will get stuck in "pending" and will not got to complete even after the order has been shipped.

**Used versions**
- *Magento Version number 2.3.5*:
- *Open source*
- *Mollie version number: 1.15.1

**To Reproduce**
1. Place an order with Klarna as payment method
2. Create shipment (from the backend)
3. Create creditmemo, / refund for this order
4. See the order status will stay in pending instead of complete

**Expected behavior**
Once the order has been shipped the order status should go to complete.
![pending](https://user-images.githubusercontent.com/31563367/89387340-a2d50f80-d702-11ea-989e-eb1fabfd0fa2.PNG)
![credit2](https://user-images.githubusercontent.com/31563367/89387350-a5d00000-d702-11ea-8445-6b7dfe341821.PNG)
![Credit memo](https://user-images.githubusercontent.com/31563367/89387353-a7012d00-d702-11ea-98c9-ed8dfba06696.PNG)

**Comment by Frank-Magmodules** [comment]
Hi @Margero, thank you for the detailed issue report! We are happy to share that we've just released the new [1.16.0](https://github.com/mollie/magento2/releases/tag/v1.16.0) version with a fix for this issue. We are closing this issue now but please feel free to reopen the issue if this still occurs.
