### ISSUE TITLE
V1.16.0 API error

### ISSUE THREAD

**Issue by JelleGe** [mollie/magento2#285]
Running version V1.16.0 on Magento 2.3.5p1 causes a API error;

`The "array" class doesn't exist and the namespace must be specified. Verify and try again.
`
Downgrading tot V1.15.1 solves the issue and API is working fine again.

**Comment by niels-hubs** [comment]
This problem exists in the file: vendor/mollie/magento2/Api/Webapi/GetCustomerOrderInterface.php
The @return has to be mixed or a api/data interface.
Please fix this issue.

Temporary fix is: @return mixed

**Comment by Frank-Magmodules** [comment]
Hi @JelleGe  , thank you for the detailed issue! We are happy to share that we've just released the new [1.16.1](https://github.com/mollie/magento2/releases/tag/v1.16.1) version with a fix for this issue. We are closing this issue now but please feel free to reopen the issue if this still occurs.
