### ISSUE TITLE
Error Magento 2.4

### ISSUE THREAD

**Issue by mtjweb** [mollie/magento2#289]
**Describe the bug**
I tried to install it on Magento 2.4, but got the following error when executing bin/magento setup:upgrade

SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**Used versions**
- Magento 2.4
- Open source
- Mollie version number 1.16.0

**To Reproduce**
1. composer require mollie/magento2
2. php bin/magento module:enable Mollie_Payment
3. php bin/magento setup:upgrade

**Expected behavior**
No error

**Actual behavior**
Stop with the following error:

**Screenshots**

**Additional context**
SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**Comment by Frank-Magmodules** [comment]
Hi @mtjweb  ,

Thank you for opening and reporting this issue. I'm not 100% sure this has to do with the Mollie extension, but we are happy to help you out. Can you please share more details of your log file and your thoughts through our [contact form](https://www.magmodules.nl/support-form.html) so we can take a look with you on this and help you solve this issue?

Thanks again!

**Comment by mtjweb** [comment]
Problem was solved by adding the following code to my.cnf and restarting MySQL-server:

```
[mysqld]
innodb_log_file_size=512M
innodb_strict_mode=0
```
