### ISSUE TITLE
Loading https://js.mollie.com/v1/mollie.min.js doesn't work and stops checkout

### ISSUE THREAD

**Issue by hostep** [mollie/magento2#291]
**Describe the bug**

Hi guys

When you enable "Use Mollie Components" for creditcards and have minifying of javascript enabled in Magento, then on the checkout, the mollie plugin will try to load https://js.mollie.com/v1/mollie.min.js instead of https://js.mollie.com/v1/mollie.js
This will crash the checkout and prevent you from checking out.

Magento will add `.min` to all javascripts it tries to load when minifying js is enabled, even for external requests.
They have a mechanism to disable this where you can specify a regular expressions of strings which match with for example `js.mollie.com` to prevent this from happening.

Since your module supports Magento 2.2.x, 2.3.x and 2.4.x there is no simple way to do this because the "easy" mechanism to do this in xml has changed significantly between 2.2.x and 2.3.x, since it was more or less broken in 2.2.x (https://github.com/magento/magento2/pull/13687 changed that)

I strongly suggest you use an after plugin to prevent that automatic `.min` addition in the external request to be appended, that will work in both 2.2.x and 2.3.x (I assume it should work in 2.4.x as well, but haven't tested that), see here how to do this: https://magento.stackexchange.com/a/198480/2911

This can be quite an important bug to fix, a lot of shops have minifying of javascript enabled.

Thanks!

**Used versions**
- *Magento Version number(eg 2.3.5)*: seen on 2.2.3
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: seen on 1.14.0, 1.16.0 and 1.16.1

**To Reproduce**
1. Enable minifying javascript in Magento (`bin/magento config:set dev/js/minify_files 1`)
2. Put Magento in production mode and recompile static assets if needed
3. Enable "Use Mollie Components" in the creditcards section
4. Create an account or login to an existing account
5. Put some product in your cart
6. Go the the second step of the checkout

**Expected behavior**
Seeing request to non-existing https://js.mollie.com/v1/mollie.min.js file in your inspector which breaks the checkout

**Actual behavior**
Seeing request to https://js.mollie.com/v1/mollie.js and checkout keeps working

**Screenshots**
<img width="591" alt="Screenshot 2020-08-19 at 14 59 51" src="https://user-images.githubusercontent.com/85479/90637737-a8674500-e22c-11ea-9555-054c35a4bac0.png">

**Additional context**

**Comment by Frank-Magmodules** [comment]
Hi @hostep,

We are happy to share that we've just released the new [1.17.0](https://github.com/mollie/magento2/releases/tag/v1.17.0) version with a fix for this issue. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by hostep** [comment]
@Frank-Magmodules & @michielgerritsen: [this](https://github.com/mollie/magento2/commit/7a3ba34ca29047aee6345f7f23945c2ccc4e1ec0) was implemented incorrectly. It doesn't work in production mode at least because the plugin was defined in `etc/frontend/di.xml` instead of `etc/di.xml`. In production mode, the static content deployment is executed via `bin/magento setup:static-content:deploy ...` which doesn't run in the frontend context from what I can tell (tested on Magento OS 2.2.3).

Can you verify this and correct please?

Thanks!

**Comment by michielgerritsen** [comment]
Hi @hostep,

Thanks for pointing this out, it looks like you are right. This will be fixed in the next release.
