### ISSUE TITLE
Cannot run integration tests because of invalid method declaration

### ISSUE THREAD

**Issue by oneserv-heuser** [mollie/magento2#292]
**Describe the bug**
When running integration tests with the default phpunit.xml.dist file PHPUnit exits with an fatal error:
``
Declaration of Mollie\Payment\Test\Integration\IntegrationTestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void
``

**Used versions**
- *Magento Version number*: 2.4.0
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 1.16.0 (Bug is not fixed in 1.16.1)

**To Reproduce**
1. Run integration tests with the config file dev/tests/integration/phpunit.xml.dist

**Expected behavior**
Integration tests are executed

**Actual behavior**
An fatal error occurs (see above)

Magento 2.4.0 uses PhpUnit 9 which has a typed return type in it's setUp() method.
Fixing this problem is very easy as all setUp() functions need to be refactored to setUp(): void to fix it.

**Comment by Frank-Magmodules** [comment]
Hi @oneserv-heuser ,

We are happy to share that we've just released the new [1.17.0](https://github.com/mollie/magento2/releases/tag/v1.17.0) version with a fix for this issue.

 Also, thank you for the PR, unfortunately, we could not use it, as this is breaking backward compatibility. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by oneserv-heuser** [comment]
@Frank-Magmodules thank you, everything is working as expected now!

**Comment by oneserv-heuser** [comment]
@Frank-Magmodules Just beeing curious, if youre sticking to semantic versioning and saying that it's breaking backwards compatibility shouldn't it be version 2.0.0 then?

**Comment by Frank-Magmodules** [comment]
Hi @oneserv-heuser, the current implementation is not breaking backward compatibility.
