### ISSUE TITLE
Compatible Issue with module firegento/magesetup2

### ISSUE THREAD

**Issue by ecentral-mk** [mollie/magento2#294]
The module firegento/magesetup2 change the json structure for the variable "window.checkoutConfig.checkoutAgreements"
See screenshot
![Screenshot_1](https://user-images.githubusercontent.com/6725620/91318263-5473d780-e7bb-11ea-8315-7a84c62704c0.jpg)

This cause an javascript error in the following file within the checkout procedure.
https://github.com/mollie/magento2/blob/master/view/frontend/web/js/view/checkout/save-payment-method.js
Line 76

For this special case we add the following line for our customer
`
var ids = config.agreements.checkout_form.map( function (agreement) {
 return agreement.agreementId;
});
`

You may want to add an exception to your code.

Best regards

**Comment by michielgerritsen** [comment]
Hallo @ecentral-mk,

Thanks for opening this issue. I've just installed the `firegento/magesetup2` package and ran the steps as described in the readme, but I can't seem to reproduce this specific error. Could you give me some more info about how to reproduce this error?

**Comment by Frank-Magmodules** [comment]
HI @ecentral-mk ,

Do you have any update on this issue and/or are you able to answer the question from Michiel?
Thank you!

**Comment by Frank-Magmodules** [comment]
Hi @ecentral-mk ,

Due inactivity we are closing this issue now but please feel free to reopen the issue or contact us [directly](https://www.magmodules.eu/support-form.html) if this still occurs.
