### ISSUE TITLE
Mollie seems to break swagger

### ISSUE THREAD

**Issue by Daniel304** [mollie/magento2#296]
Known issue in other extension:
Change the interface doc from array (Magento unsupported) to mixed[] for swagger API doc.

curl -X GET "https://stage.brickfever.nl/rest/all/schema?apiKey=xxxxxxxxxxxxxxxxxx" \                                                                                                                      
     -H "Content-Type:application/json"
{"message":"The \"array\" class doesn't exist and the namespace must be specified. Verify and try again.","trace":"#0 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/module-webapi\/Model\/Config\/ClassReflector.php(103): Magento\\Framework\\Reflection\\TypeProcessor->register('array')\n#1 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/module-webapi\/Model\/Config\/ClassReflector.php(72): Magento\\Webapi\\Model\\Config\\ClassReflector->extractMethodData(Object(Laminas\\Code\\Reflection\\MethodReflection))\n#2 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/module-webapi\/Model\/ServiceMetadata.php(134): Magento\\Webapi\\Model\\Config\\ClassReflector->reflectClassMethods('Mollie\\\\Payment\\\\...', Array)\n#3 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/module-webapi\/Model\/ServiceMetadata.php(166): Magento\\Webapi\\Model\\ServiceMetadata->initServicesMetadata()\n#4 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Model\\ServiceMetadata->getServicesConfig()\n#5 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Model\\ServiceMetadata\\Interceptor->___callParent('getServicesConf...', Array)\n#6 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Model\\ServiceMetadata\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#7 \/export\/www\/stage.brickfever.nl\/generated\/code\/Magento\/Webapi\/Model\/ServiceMetadata\/Interceptor.php(26): Magento\\Webapi\\Model\\ServiceMetadata\\Interceptor->___callPlugins('getServicesConf...', Array, Array)\n#8 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/module-webapi\/Model\/Rest\/Swagger\/Generator.php(969): Magento\\Webapi\\Model\\ServiceMetadata\\Interceptor->getServicesConfig()\n#9 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/module-webapi\/Controller\/Rest\/SchemaRequestProcessor.php(53): Magento\\Webapi\\Model\\Rest\\Swagger\\Generator->getListOfServices()\n#10 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/module-webapi\/Controller\/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SchemaRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#11 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#13 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#14 \/export\/www\/stage.brickfever.nl\/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#15 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/framework\/App\/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#16 \/export\/www\/stage.brickfever.nl\/vendor\/magento\/framework\/App\/Bootstrap.php(261): Magento\\Framework\\App\\Http->launch()\n#17 \/export\/www\/stage.brickfever.nl\/pub\/index.php(40): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#18 {main}"}#

**Comment by Daniel304** [comment]
when disabling mollie from our staging environment swagger starts working again.

**Comment by Frank-Magmodules** [comment]
@Daniel304, As you are not using the issue template we don't know the Magento2 and Mollie extension versions you are running on. Can you please let me know if you are running the latest version?

**Comment by Daniel304** [comment]
Hi
Sorry we are using magento 2.3.5 and the latest mollie extension. However i
think this issue is going on for a while since they made this change is
swagger documentation generator

Op ma 31 aug. 2020 om 09:03 schreef Frank Tiggelman <
notifications@github.com>

**Comment by Frank-Magmodules** [comment]
Hi @Daniel304, the suggestion you have was implemented in the latest version, so could you please provide us the version number you are running at this moment?

**Comment by Daniel304** [comment]
Hi Frank
We are using the up-to-date version available on composer
tig/postnl-magento2                                               1.9.4.1

with kind regards
Daniel van den Oord

Op ma 31 aug. 2020 om 10:37 schreef Frank Tiggelman <
notifications@github.com>:

**Comment by Frank-Magmodules** [comment]
Hi @Daniel304, ok, but we are talking about the Mollie module, can you let me know about that version?

**Comment by Daniel304** [comment]
sorry long days... You are right:
mollie/magento2                                   1.16.0     1.16.1     Mollie Payment Module for Magento 2
mollie/mollie-api-php                             v2.22.0    v2.22.3    Mollie API client library for PHP. Mollie is a Euro...

Will update to the latest version in next release cycle
Thank you!
