### ISSUE TITLE
Autoload error

### ISSUE THREAD

**Issue by wonderlancer** [mollie/magento2#297]
**Describe the bug**

**Used versions**
- *Magento Version number(eg 2.2.6)*:
- *Open source
- *Mollie version number (latest)*:

**To Reproduce**
I got after install module error 
**Autoload error**
`Module 'Mollie_Payment' from '/home/427182.cloudwaysapps.com/gravqhssbb/public_html/app/code/Mollie/Payment' has been already defined in '/home/427182.cloudwaysapps.com/gravqhssbb/public_html/vendor/mollie/magento2'.`

**Comment by Frank-Magmodules** [comment]
@wonderlancer , Thank you for opening and reporting this issue. It seems that you have tried to install the extension through Composer as well as by uploading it at app/code, if you remove one of these and run the install scripts again, this issue will be solved. We are closing this issue now but please feel free to reopen the issue if this still occurs.
