### ISSUE TITLE
Incorrecte composer.json autoload config

### ISSUE THREAD

**Issue by pascaladriaansen** [mollie/magento2#3]
Hey,

Zojuist geprobeerd met composer de module te installeren. Deze haalt netjes mollie/magento2 en de mollie/mollie-api-php binnen.

Zodra ik hierna echter`bin/magento module:status` uitvoer krijg ik de volgende error:
```
PHP Warning:  require(/data/web/framework/src/vendor/composer/../mollie/magento2/registration.php): failed to open stream: No such file or directory in /data/web/framework/src/vendor/composer/autoload_real.php on line 71
PHP Fatal error:  require(): Failed opening required '/data/web/framework/src/vendor/composer/../mollie/magento2/registration.php' (include_path='/data/web/framework/src/vendor/magento/zendframework1/library:.:/usr/share/php') in /data/web/framework/src/vendor/composer/autoload_real.php on line 71
```

Zo te zien zou het autoload pad dat nu naar `registration.php` verwijst in `composer.json` eigenlijk naar `src/registration.php` moeten verwijzen.

**Comment by ThomasVaRo** [comment]
Ik had gisteren hetzelfde probleem.
De registration.php file staat inderdaad in de src map, je moet deze verplaatsen naar de directory eronder, dan zou het path wel moeten kloppen

**Comment by Magmodules** [comment]
Dank! Aangepast en versie bump naar 0.9.6
