### ISSUE TITLE
Bank transfer does not send confirmation email

### ISSUE THREAD

**Issue by janssensjelle** [mollie/magento2#301]
**Describe the bug**
When the customer selects the bank transfer payment method, goes to Mollie and does not return to Magento, no confirmation email will be sent. This results in frustrations with the merchant and the customer. This also results in missed conversion in analytics

**Used versions**
- 2.3.4
- Open Source
- 1.12.1

**To Reproduce**

1. Place an order using Bank Transfer
2. Go to Mollie
3. Close the tab without returning to Magento

**Expected behavior**
Customer is either automatically redirected or a confirmation email is being sent.

**Actual behavior**
Nothing happens. When you go back to the merchant, the success page is shown and a confirmation is sent.

**Comment by Frank-Magmodules** [comment]
HI @janssensjelle , thank you for opening this issue. It seems that you are using a quite outdated version of the Mollie plugin and as I can't reproduce this issue on the latest version, can you please update the extension and let me know if this solves your issue?

**Comment by Frank-Magmodules** [comment]
HI @janssensjelle , 

Do you have any update on this issue?
Thank you!

**Comment by janssensjelle** [comment]
hi @Frank-Magmodules , not yet. I am waiting for customer approval to update the extension

**Comment by Frank-Magmodules** [comment]
Hi @janssensjelle , any update on this?
Thanks!

**Comment by janssensjelle** [comment]
Closing it for the time being.
