### ISSUE TITLE
Klarna and DPD Shipments

### ISSUE THREAD

**Issue by mikehenze** [mollie/magento2#302]
Cannot create a DPD shipment (label) when order was placed using Klarna pay layer.
Error message: `Notice: Undefined offset: 62850 in /data/web/magento2/vendor/mollie/magento2/Model/Client/Orders.php on line 987`

- Magento 2.3.5-p2
- Open source
- Mollie 1.17.0
- DPD 1.1.2 (https://github.com/dpdconnect/magento2-shipping)

Edit 16/9:
DPD says:
The DPD extension tries to create a DPD shipment but the Mollie extension won't allow this.

**Comment by Frank-Magmodules** [comment]
Hi @mikehenze ,

We are happy to share that we've just released the new [1.7.1](https://github.com/mollie/magento2/releases/tag/v1.17.1) version with a fix for this issue. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
