### ISSUE TITLE
Invalid Locale Credit Card Components

### ISSUE THREAD

**Issue by Quazz** [mollie/magento2#303]
**Describe the bug**
When you attempt to checkout using payment method Credit Cards when Components is enabled, an error will occur "Invalid Locale" and payment can not proceed.

Checkout works as expected when Components are disabled.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4
- *Open source/Enterprise/B2b*: Open Souce
- *Mollie version number (Check configuration)*: 1.17

**To Reproduce**
1. Enable  Credit Cards payment method at Mollie dashboard
2. Enable Credit Cards payment method at Magento 2 admin
3. Enable Use Mollie Components at Magento 2 admin
4. Try to use credit card as payment method in checkout (we used Visa in test)

**Expected behavior**
Payment proceeds to get forwarded to Mollie API and order gets placed successfully.

**Actual behavior**
An error occurs "Invalid Locale" blocking checkout.

**Additional context
Given the error message, it's worth noting that Language Payment Page is set to "Store Locale". (Autodetect gave the same error as well)

**Comment by Quazz** [comment]
https://github.com/mollie/magento2/blob/e32eece0a885b414061f0548d4954c80d03b36b5/Config.php#L379 

Passes it on as a string. Logical, when a locale is explicitily defined. 

This info then gets stored into an array here:

https://github.com/mollie/magento2/blob/e32eece0a885b414061f0548d4954c80d03b36b5/Model/MollieConfigProvider.php#L164

That array is then accessed here:
https://github.com/mollie/magento2/blob/e32eece0a885b414061f0548d4954c80d03b36b5/view/frontend/web/js/view/payment/method-renderer/creditcard-with-components.js#L55

Since that file is only loaded when components are enabled, the error won't be encountered when it's disabled. 

So for now, the workaround is to either:

Disable components

Explicitily define Locale per store view (this one is likely not appealing when you have tons of store views/locales!)

**Comment by Frank-Magmodules** [comment]
Hi @Quazz ,

We are happy to share that we've just released the new [1.7.1](https://github.com/mollie/magento2/releases/tag/v1.17.1) version with a fix for this issue. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
