### ISSUE TITLE
Print receipt on order success page link not working.

### ISSUE THREAD

**Issue by FloriaanTickles** [mollie/magento2#308]
**Describe the bug**
After successful order with status paid the "Print receipt" button on the success page does not contain the correct parameters in the url which in turn leads to a 404 when the customer tries to click the Print receipt button.

This problem seems to originate from the Magento\Checkout\Block\Onepage\Success::prepareBlockData() method.
In this method the block class is trying to set the print_url variable using the getUrl method on line 91.
This fails due to $order->getEntityId() returning null. 

It seems that whenever the payment is done through Mollie $this->_checkoutSession->getLastRealOrder() in the above class returns an order instance without any data set.

**Used versions**
- Magento CE 2.3.2
- mollie/magento2: 1.6.3, 1.17.1

**To Reproduce**
1. As a logged in customer with a product in the cart, go to the checkout, and do a successful checkout with a Mollie payment method (for example iDeal) afterwards returning to the magento2 success page.

2. Click on the "Print receipt" button in the top right corner of the success page

**Expected behavior**
A sales order print to be opened with an example path of: example.test/sales/order/print/order_id/12345

**Actual behavior**
A 404 page shown due to the wrong (incomplete) path in the link: example.test/sales/order/print/

**Additional**
As additional this issue also seems to cause the cart not to be emptied after successful checkout.

**Comment by Frank-Magmodules** [comment]
Hi @FloriaanTickles ,

Thank you for opening and reporting this issue. Can you confirm this is working like it should on a non-Mollie order? As we can't reproduce this issue please share your further details through our [contact form](https://www.magmodules.nl/support-form.html) in case this is only happening on Mollie orders so we can take a look with you on this and help you solve this issue?

Thanks!

**Comment by FloriaanTickles** [comment]
This is working fine when using an offline non-mollie payment method such as Check / Money order, Please let me know what additional details you want me to provide.

**Comment by Frank-Magmodules** [comment]
HI @FloriaanTickles , strange that we can't reproduce this. Can you please sent further details, if possible of a staging/development environment with this issue through our  [contact form](https://www.magmodules.nl/support-form.html)  form so we can take a look with you on this?

**Comment by Frank-Magmodules** [comment]
Hi @FloriaanTickles ,

Do you have any update on this issue?
Please let me know if you need any further assistance so we can help you out with this issue.

**Comment by Frank-Magmodules** [comment]
Hi @FloriaanTickles,
Due to inactivity we are closing this issue now but please feel free to reopen the issue if this still occurs.
