### ISSUE TITLE
Ideal Magento

### ISSUE THREAD

**Issue by subcolors** [mollie/magento2#31]
Hoi,

Ik heb de bestanden in de root geüpload en heb de command ingevoerd zoals aangegeven in punt 2 van de readme maar er is niks veranderd. Putty geeft de volgende melding aan: -bash composer: command not found ?

Ik verneem graag van jullie.

Met vriendelijke groet,

 Linda

**Comment by magmodules** [comment]
Hi Linda, de files uit de repo dienen niet geupload te worden, maar geïnstalleerd te worden middels composer. De melding geeft aan dat composer niet beschikbaar is op je omgeving. Stuur anders even een request via https://www.magmodules.eu/contact-us.html dan kunnen we de installatie voor je uitvoeren.
