### ISSUE TITLE
Not able to Cancel an order which is paid with Klarna

### ISSUE THREAD

**Issue by gerben86** [mollie/magento2#310]
I have an order which I want to cancel, but the customer selected Klarna as payment method.

When I try to cancel the order I get this message:
![image](https://user-images.githubusercontent.com/17478858/95557261-d4c16580-0a14-11eb-872c-5430e8c60de1.png)

How could I cancel this order in a proper way without deleting the complete order?

**Steps to reproduce**
- Create an order, use Klarna as payment method
- Try to cancel the order in the adminpanel via this button:
![image](https://user-images.githubusercontent.com/17478858/95580844-4e1e7f80-0a38-11eb-9d54-9e5bc244bb71.png)

**Expectation:**
Order will get status cancelled and the Klarna-payment will also be cancelled

**Actual result**
Order isn't cancelled and I receive this message:
![image](https://user-images.githubusercontent.com/17478858/95557261-d4c16580-0a14-11eb-872c-5430e8c60de1.png)
Also the payment in the Mollie Dashboard still has the same status "Geautoriseerd".

**Used versions**
Magento Version number(eg 2.3.5): 2.3.3
Open source/Enterprise/B2b: Open Source
Mollie version number (Check configuration): v1.17.0

**Comment by Frank-Magmodules** [comment]
Hi @gerben86 ,

Thank you for opening and reporting this issue, seems I can't reproduce this in Magento 2.4.0 with the latest Mollie version, can you please fill in the bug-issue report so we can get more information on this issue with a detailed steps-to-reproduce report? It seems that we now have too little information to help you out.

Frank

**Comment by gerben86** [comment]
Hi @Frank-Magmodules ,

I updated the report.
But could you provide me a way to cancel the order and the payment?
Because upgrading to 2.4.0 is a little bit too much for only cancelling 1 order ;)

Thanks!

**Comment by Frank-Magmodules** [comment]
Hi @gerben86,

What is the state of this order that you are trying to cancel and is there an invoiced created?
- If the order state is Processing and an invoice is available, you cannot cancel the invoice but you need to create a credit memo. 
- If the order state is Processing and there is no invoice yet, you are able to cancel the order.

See; https://docs.magento.com/user-guide/sales/order-status-workflow.html
Otherwise, feel free to share more details  through our [contact form.](https://www.magmodules.nl/support-form.html) So we can take a look with you on this.

**Comment by gerben86** [comment]
Hi @Frank-Magmodules ,

The order status is "Gaande", the status of the factuur is "In afwachting".
There's no possibility to create a creditinvoice at this moment:
![image](https://user-images.githubusercontent.com/17478858/95591997-5383c600-0a48-11eb-8813-49639fd18863.png)

Also in the order itself is it not possible to create a creditinvoice.

**Comment by Frank-Magmodules** [comment]
Seems that _Gaande_ is a custom order status. Which order state is this?

Please see:
https://docs.magento.com/user-guide/sales/order-status.html

**Comment by gerben86** [comment]
Gaande means processing:
![image](https://user-images.githubusercontent.com/17478858/95597700-44544680-0a4f-11eb-8376-1af8e26d781e.png)

Which makes sense, because the Klarna-payment is done, but the order isn't shipped yet.

**Comment by Frank-Magmodules** [comment]
Alright, I couldn't make this up as it is a non-default title.

Is there an invoice created in this state? And can you try to reproduce this with a non-Mollie payment method? Is that canceling in the right way? As the error seems to be coming from Magento instead of the Mollie extension.

**Comment by gerben86** [comment]
I'm not able to test that right now. And I also suspect that that isn't important, because the fact is that I'm not able to cancel this Klarna-order, and in my opinion that should be possible :)

Is there another way to cancel the Klarna-payment in the Mollie dashboard?

**Comment by Frank-Magmodules** [comment]
HI @gerben86 , ok, for me it's relevant to distinguish whether this is a Magento or Mollie issue, from there we can make a plan of action. It's also relevant if there is an invoice created.

**Comment by gerben86** [comment]
Hi Frank,

There's indeed an invoice created, that's done immediatly after the payment (for iDeal, CreditCard, Klarna etc.).

I checked another order, which is paid with Mollie iDeal, and has the same status (Gaande), but for that order a CreditInvoice can be created (on both order- and invoicelevel):
![image](https://user-images.githubusercontent.com/17478858/95600776-e6296280-0a52-11eb-8330-14d2f67d9ef5.png)

**Comment by Frank-Magmodules** [comment]
HI @gerben86 ,

The way of generating the invoice depends on the configuration for Klarna within the Mollie extension but please share your store details through our [contact form](https://www.magmodules.nl/support-form.html) so we can take a look at you on this.

**Comment by Frank-Magmodules** [comment]
Hi @gerben86 , 

Do you have any update on this issue?
Please let me know if you need any further assistance so we can help you out with this issue.

**Comment by gerben86** [comment]
Thanks for mentioning this!
Finally it was possible to cancel the order. I don't know how I did it. So I'll close this issue.

**Comment by gerben86** [comment]
Found the solution:
- First cancel the Invoice
- Then cancel the Order itself

**Comment by gerben86** [comment]
I'm still struggling with this each time a Klarna order needs to be cancelled.
What are the correct steps to cancel an 'unpaid' Klarna order after the invoice has been created?
Because that's still not clear for me, creating a credit-invoice results in an error.
