### ISSUE TITLE
Limit payment methods based on currency

### ISSUE THREAD

**Issue by Esteraa** [mollie/magento2#311]
**Describe the bug**
When placing an error in the checkout with shipping country Netherlands and pay with Ideal/Bankstranfer you get this error.

`Error executing API call (422: Unprocessable Entity): The currency is not supported by this payment method. Field: amount.currency. Documentation: https://docs.mollie.com/guides/handling-errors
`

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.3.5-p1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: v1.15.1

**To Reproduce**
1. Add product to cart
2. Proceed to checkout
3. Fill in Dutch address with country Netherlands
4. Proceed to payment and choose Ideal

**Expected behavior**
Continuing payment with Ideal.

**Actual behavior**
Sent back to the cart and shown an error.

**Comment by downforce80** [comment]
It's not possible to pay an invoice in GBP via method iDeal.
Ideal will only let you pay in EURO.
Configure Magento to use EUR then it should work.

**Comment by tropilex** [comment]
Ideally iDeal should not be shown if the currency is not €. Because now we need to exclude countries. Excluding currencies is better.

**Comment by Frank-Magmodules** [comment]
HI @downforce80 , @tropilex, and @Esteraa , thank you for opening this issue. We are in the process of running a currency check through the Mollie API so only the available payment methods for the used currency will be listed on the checkout. This will be implemented in the next release. Thank you for your patience and contribution to this.

**Comment by tropilex** [comment]
@Frank-Magmodules Great! Good work.

**Comment by Frank-Magmodules** [comment]
Hi @Esteraa ,
We are happy to share that we've just released the new [1.18.0](https://github.com/mollie/magento2/releases/tag/v1.18.0) version with a fix for this issue. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
