### ISSUE TITLE
Mollie don't update status to processing

### ISSUE THREAD

**Issue by onopko81** [mollie/magento2#315]
Hi, the order has not been updated for a few days when we pay with mollie. it remains pending and the status: processing is not assigned. in addition, the email to the customer is not sent. 

from Log mollie returns this error: Mollie.ERROR: error: Failed to create label, missing shipper street [] []

thanks

**Comment by onopko81** [comment]
Version | v1.13.0
PHP version: 7.3.24.

**Comment by Frank-Magmodules** [comment]
Hi @onopko81, Thank you for opening this issue. Just did a quick search on the thrown exception and looks like this is from the DHLParcel module, see: https://github.com/dhlparcel/plugin-magento2-release/blob/544af50a91ee14e97554475465a3aad7b741418c/Model/Service/Shipment.php#L94 , can you check either confirm this?

**Comment by onopko81** [comment]
yes, this module is active. Let's check and update you.

**Comment by onopko81** [comment]
hi, i resolve it. the problem is dhl parcel module, thanks.

**Comment by Frank-Magmodules** [comment]
HI @onopko81 ,

Clear! Thanks for your confirmation on this, I will close this issue for now.
