### ISSUE TITLE
The second chance email is send thousands of times to same customer

### ISSUE THREAD

**Issue by Sil-B** [mollie/magento2#320]
**Describe the bug**
The second chance email is send thousands of times to the same customer. Even though the orders were paid with minutes. 

**Used versions**
- Magento Version number: 2.3.6
- Open source
- Mollie version number: 1.18.0

**To Reproduce**

**Expected behavior**
Second chance email is only send once 

**Actual behavior**
Second chance email is send to the same customer thousands of times. 

**Screenshots**

**Additional context**
mollie.log adds a new line for every second chance email. One order is mentioned over 45k. 

There are multiple orders that have a couple thousand emails send. All orders were placed and paid within a couple of minutes. Orders were paid with ideal or paypal. 

These orders only have one record in the Mollie Pending Payment Reminders grid. 

Let me know if you need specific order numbers and Client details.

**Comment by Frank-Magmodules** [comment]
hi @Sil-B , 

Thank you for opening and reporting this. Can you please share the details through our [contact form.](https://www.magmodules.nl/support-form.html) so we can take a look with you on this and help you solve this issue? The more information the better.

Thanks again!

**Comment by bamboekeizer** [comment]
I had the same issue. An order that was created Nov-4, with an email address that did not exist. The user made a typo in the email address. On Nov-19, over 21K emails were sent. I disabled the Payment Reminder option.
![Screenshot 2020-11-19 093352](https://user-images.githubusercontent.com/28304222/99641349-6d9ec400-2a4a-11eb-9b9a-be4542bf7747.png)

**Comment by Frank-Magmodules** [comment]
hi @bamboekeizer ,

Thank you for opening and reporting this. Can you also please share the details through our [contact form](https://www.magmodules.nl/support-form.html) so we can take a look with you on this and help you solve this issue? The more information the better.

Thanks to you as well!

**Comment by Frank-Magmodules** [comment]
Hi @bamboekeizer  & @Sil-B ,

Thank you again for the detailed reports and patience. The issue could happen when there is an exception with mail sending that resulted in the item being placed back into the queue that was looped for sending. This part has been refactored and the record is now deleted before the email has been sent. 

This fix has been added to a new release with version [1.18.1](https://github.com/mollie/magento2/releases/tag/v1.18.1)
We are closing this issue now but please feel free to reopen the issue if this still occurs.

Have a good weekend ahead!

**Comment by Sil-B** [comment]
Thanks @Frank-Magmodules!
