### ISSUE TITLE
mollie payments are not displayed when creating a new order or reordering through the admin panel

### ISSUE THREAD

**Issue by Iamwade** [mollie/magento2#321]
**Describe the bug**

mollie payments are not displayed when creating a new order or reordering through the admin panel

**Used versions**
- Magento Version number: 2.3.3
- Open-source
- Mollie version number: 1.12.2 or 1.18.0

**To Reproduce**
1. Go to 'Admin -> Sales -> Orders'
2. Click on 'Any order.'
2. Click on 'reorder'
3. Scroll down to 'Payment & Shipping Information'
4. See 'No Payment Methods'

**Expected behavior**
we see all included mollie payment methods

**Actual behavior**
No Payment Methods

**Screenshots**
![bug](https://user-images.githubusercontent.com/33068778/99104105-37e08200-25e9-11eb-90d2-816133eba772.png)

**Comment by Frank-Magmodules** [comment]
HI @Iamwade , thank you for opening this issue. Do you have enabled the  `Payment Link / Admin Payment` Payment method in the configuration of the Mollie extension? Only with this option enabled it's possible to use Mollie payments through a back-end order.

**Comment by Frank-Magmodules** [comment]
Hi @Iamwade ,
Do you have any update on this issue?
Please let me know if you need any further assistance so we can help you out with this issue.

**Comment by Frank-Magmodules** [comment]
HI @Iamwade ,
Due to inactivity, we are closing this issue now but please feel free to reopen the issue if this still occurs.
