### ISSUE TITLE
Order status never changes on a successful payment.

### ISSUE THREAD

**Issue by thebma** [mollie/magento2#327]
**Describe the bug**
After creating an order and paying using Mollie with the payment method iDeal, the order that is created is stuck on "Payment Pending". I've waited about ~30 minutes for the status to change, to no avail. 

Peculiar that this does not happen in test mode, this will assign the correct status almost instantly.

Another side note is, when I press the "Fetch status" button it will change the status to "Processing".
I am under the assumption that it should fetch the status automatically, without intervention from a store owner.

Some pointers that might help debugging:
- Cron jobs are running every minute (observed from the logs in `$MAGE_ROOT/var/log/debug.log`).
- The payment from the API seems successful. (https://gist.github.com/thebma/00d2726665dcc8fabf7700b8f34d3a82)
- Mollie Dashboard says the payment was successful and completed (see screenshot 1)

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: v1.18.0

**To Reproduce**
1. Order a product from your store
2. Sit through the payment process steps

**Expected behavior**
When I create an order via my webshop, I expect the following flow:
1) customer order an item
2) customer pays for the item via Mollie
3) store owner checks new orders
4) store owner expects paid orders to be of "Processing" status.
5) store owner proceeds to shipping steps.

**Actual behavior**
What actually happens is that the order will stay in the "Pending Payment" status.
See screenshot how it's depicted on our backend.

**Screenshots**
1: ![image](https://user-images.githubusercontent.com/50952472/100366047-9ef63180-3000-11eb-9fea-323526106f27.png)
2: ![image](https://user-images.githubusercontent.com/50952472/100366867-ae29af00-3001-11eb-89ff-902b0421e32f.png)

Settings under General:
![image](https://user-images.githubusercontent.com/50952472/100374355-6d836300-300c-11eb-8d16-af424125c649.png)

Settings for Payment Methods -> iDeal
![image](https://user-images.githubusercontent.com/50952472/100374421-8be95e80-300c-11eb-9608-7bb84ddba6e6.png)
![image](https://user-images.githubusercontent.com/50952472/100374436-93106c80-300c-11eb-87a1-71d38a2ee634.png)

Settings under Advanced:
![image](https://user-images.githubusercontent.com/50952472/100374470-a6233c80-300c-11eb-800e-1d779d034675.png)
![image](https://user-images.githubusercontent.com/50952472/100374494-af140e00-300c-11eb-8a6d-bca6f52796b2.png)

**Additional context**

**Comment by Frank-Magmodules** [comment]
Hi @thebma ,
Thank you for opening and reporting this issue. We don't have any similar known issues and we are not able to reproduce this. Can you check what the response code is from the webhook? You can find this through the Mollie dashboard and open the specified order.

**Comment by thebma** [comment]
I seem unable to find anything resembling "Response Code" under the available payment:
![image](https://user-images.githubusercontent.com/50952472/100458306-d843a580-30c3-11eb-93ef-33ee07365020.png)

I also noticed you said under the "specified order", In our Mollie Dashboard there seems to be no orders listed (only payments) and I'm presented with introduction screen asking me to "View API keys".

I assume this has to do with the type of API we configured under the "Payment Methods -> iDeal", from my understanding we want to use Payments API here since it fits our use case (i.e. order managed via the Magento System).

**Comment by Frank-Magmodules** [comment]
HI @thebma , as we can't reproduce this, please fill in our [support form](https://www.magmodules.eu/support-form.html) and login details with us so we can take a look with you on this. Thank you!

**Comment by thebma** [comment]
@Frank-Magmodules has debugged the issue and resolved it. The store-front was not accessible at that time (due to a waiting screen to fence off customers). Remove the protection, making a new order almost instantly went through and worked like a charm.
