### ISSUE TITLE
Config problem

### ISSUE THREAD

**Issue by ekomurz** [mollie/magento2#331]
**Describe the bug**
Backend configuration runs into an error, caused by a Mollie plugin
Error messages like 
"Fatal error: Uncaught ArgumentCountError: Too few arguments to function Mollie\Payment\Plugin\Config\LoadCorrectGroup::beforeGetConfigByPath(), 4 passed in /usr/local/www/berebene/vendor/magento/framework/Interception/Interceptor.php on line 121 and exactly 5 expected in /usr/local/www/berebene/vendor/mollie/magento2/Plugin/Config/LoadCorrectGroup.php:13 Stack trace: #0 /usr/local/www/berebene/vendor/magento/framework/Interception/Interceptor.php(121): Mollie\Payment\Plugin\Config\LoadCorrectGroup->beforeGetConfigByPath(Object(Magento\Config\Model\Config\Loader\Interceptor), 'xretail/pos', 'default', 0) 

**Used versions**
- Magento 2.3.6
- Open source
- Mollie version number: latest from composer/repository

**To Reproduce**
1. Go to catalog grid in backend, error appears
2. Login on frontend with existing customer account, error appears also

**Expected behavior**
No errors...

**Actual behavior**
See error message above

**Additional context**
I fixed this problem by adding '$full = true' for the last argument into Mollie\Payment\Plugin\Config\LoadCorrectGroup class

**Comment by Frank-Magmodules** [comment]
Hi @ekomurz ,
We are happy to share that we've just released the new [1.20.0](https://github.com/mollie/magento2/releases/tag/v1.20.0) version with a fix for this issue. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
