### ISSUE TITLE
Problems with understanding of mollie_available_issuers

### ISSUE THREAD

**Issue by oneserv-heuser** [mollie/magento2#333]
Hey,

I'm trying to place some test orders with mollie via the graphql api. 
I'm having issues when trying to understand the available issuers. They can be fetched in the type Cart. The problem is that the list is always empty, doesn't matter in which state my order is (email set, shipping method set, addresses set, payment method set). What exactly is the use of available issuers and how can i achieve to actually get some results?

I've enabled several payment methods in magento (bankpayment, creditcard, Sofort, etc.) and there are also enabled in my Mollie account. I'm able to retrieve them if I fetch the field "available_payment_methods" with the sub selection of "code" and "title" (mollie_available_issuers is also here empty).
I'm also able to place an order without setting an issuer, but then I cannot update the Payment status in the magento backend as I get the error "Transaction ID not found". Also the orders do not show up in my Mollie Dashboard.
So I guess I need to call "createMollieTransaction" which I need an issuer for?

What am I missing here?

**Comment by Frank-Magmodules** [comment]
HI @oneserv-heuser , 

Thank you for opening this issue. The `mollie_available_issuers` attribute is meant for retrieving the issuers for the different payment methods. Only a few support those: iDeal, KBC, and gift cards. Are you sure you are retrieving those methods?

**Comment by oneserv-heuser** [comment]
@Frank-Magmodules No, I'm not retrieving any of those methods. But where is this documented? If I look at https://github.com/mollie/magento2/wiki/GraphQL-integration it seems like it's mandatory. Could it maybe be made clear that the issuer is only needed for certain methods?

And is it normal that payment methods like banktransfer don't show up in the mollie dashboard?

**Comment by michielgerritsen** [comment]
Hi @oneserv-heuser,

It looks like that there is an error in the GraphQL documentation. The example shows this:

```
query {
  cart(cart_id: "{{cart_token}}") {
    available_payment_methods {
      code
      title
    }
    mollie_available_issuers {
      name
      code
      image
      svg
    }
  }
}
```

But the `mollie_available_issuers` should be within the `available_payment_methods` like this:
```
query {
  cart(cart_id: "{{cart_token}}") {
    available_payment_methods {
      code
      title
      mollie_available_issuers {
        name
        code
        image
        svg
      }
    }
  }
}
```

I will make sure the documentation gets updated with this information.

About showing/not showing payment methods: That depends on the settings in the Magento backend but also in the Mollie dashboard. If payment methods are not enabled in the Mollie dashboard, they will not be shown in the list of payment methods.

If methods are missing in the Mollie dashboard it's best to contact them [directly](https://www.mollie.com/contactdirectly).

**Comment by michielgerritsen** [comment]
@oneserv-heuser,

After double-checking, I see where the confusion is coming from: There are 2 ways to get the available issuers:
- Together with the list of available payment methods.
- When checking the current cart, after a payment method is selected.

The example in the documentation has both options combined: It retrieves the list of available payment methods but tries to get the issuers for the currently selected payment method, which does not make sense. I will make sure this comes in the documentation, please let me know if there are still issues that are not clear for you:

## Request the _available payment methods_ with issuers
```
query {
  cart(cart_id: "{{cart_token}}") {
    available_payment_methods {
      code
      title
      mollie_available_issuers {
        name
        code
        image
        svg
      }
    }
  }
}
```

## Request the available issuers _for the current cart_
```
query {
  cart(cart_id: "{{cart_token}}") {
    selected_payment_method {
      code
    }
    mollie_available_issuers {
      name
      code
      image
      svg
    }
  }
}
```

**Comment by Frank-Magmodules** [comment]
HI @oneserv-heuser ,  

We are happy to share that also updated the [WIKI](https://github.com/mollie/magento2/wiki/GraphQL-integration) page with these improved instructions GraphQL Integration instructions. Please let us know if this is all clear for you so we can close this issue.

**Comment by oneserv-heuser** [comment]
Yes, thank you for your help!
