### ISSUE TITLE
voucher payment method remains available despite of correct custom attribute

### ISSUE THREAD

**Issue by akosglue** [mollie/magento2#335]
**Describe the bug**

We have created a custom product attribute and we have set it to 'none', just like the module requires: Please create a custom product attribute of the type 'Dropdown'. This dropdown can contain 4 options. The Admin value of these options must be 'meal', 'eco', 'gift' or 'none'.

We expect that the voucher payment method disappears on the checkout, but it remains in the payment method list. However, the only product in the cart has the custom attribute value 'none'. When you want to pay the payment fails:
Error executing API call (422: Unprocessable Entity): Order line 1 is invalid. Invalid order line category, valid categories are "eco", "gift", "meal", and null. Field: lines.1.category. Documentation: https://docs.mollie.com/guides/handling-errors

**Used versions**
- M2 2.2.9
- Open source
- 1.19.0

**To Reproduce**
create custom attribute for eco, none, gift ... options, and select this attribute for the voucher method in the mollie config. (category -> custom attribute)

**Expected behavior**
voucher method disappears on checkout.

**Actual behavior**
voucher method remains available on checkout, but when you want to pay, the payment fails. (product has its custom value 'none')

**Comment by akosglue** [comment]
we tested the api calls as well, when we have this in the orderline
"category":"null"
we get: unprocessable entity: Order line 1 is invalid.
but if we try: "category":null
in the orderline, the api call succeeds.
If I am right, it should happen here:
https://github.com/mollie/magento2/blob/e32eece0a885b414061f0548d4954c80d03b36b5/Service/Order/Lines/Processor/VoucherCategory.php#L51

**Comment by Frank-Magmodules** [comment]
Hi @akosglue ,
Thank you for opening and reporting this issue. We have created an internal task for this issue and will try to come back to you as soon as possible. Thank you for your patience!

**Comment by Frank-Magmodules** [comment]
Hi akosglue,
We are happy to share that we've just released the new [1.20.1](https://github.com/mollie/magento2/releases/tag/v1.20.1) version with a fix for this issue. Thank you again f or the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
