### ISSUE TITLE
Missing ACL list entry for Payment reminders

### ISSUE THREAD

**Issue by oneserv-heuser** [mollie/magento2#336]
**Describe the bug**
There are no entries in the ACL list for the Payment reminders.
There are 2 entries added to the menu via the [menu.xml](https://github.com/mollie/magento2/blob/d2f9bd1d51a1d3b8bd14888a293f407a6fc85de2/etc/adminhtml/menu.xml#L1) but the resources for this are not present in the [acl.xml](https://github.com/mollie/magento2/blob/d2f9bd1d51a1d3b8bd14888a293f407a6fc85de2/etc/acl.xml#L1) which results in the problem that any user which doesn't have all rights assigned is unable to access the Payment reminders via the menu.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 1.19 (issue not resolved in 1.20)

I don't think that more information is needed on this one as it's pretty straight forward.

**Comment by Frank-Magmodules** [comment]
Hi @oneserv-heuser,
We are happy to share that we've just released the new [1.20.1](https://github.com/mollie/magento2/releases/tag/v1.20.1) version with a fix for this issue. Thank you for the detailed report and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by oneserv-heuser** [comment]
@Frank-Magmodules It's working but another problem occured:
In the [acl.xml](https://github.com/mollie/magento2/blob/9fd94604051354c4d20e1e1435b306477e4289fe/etc/acl.xml#L14) the labels for the entries are written in lowercase but in the i18n csv files they're written in uppercase at every new word so they don't get translated.
