### ISSUE TITLE
Spaces are not allowed in the Mollie API but valid for Magento 2

### ISSUE THREAD

**Issue by JeroenBoersma** [mollie/magento2#337]
**Describe the bug**
In Magento 2 you can have spaces in the url's but the Mollie API will deny the order with spaces in the url

**Used versions**
- *Magento Version number(eg 2.3.5)*:
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: v1.20.0

**To Reproduce**
1. Go to Magento admin
2. Click on Create a product with spaces in the url
3. Try to place an order with Molie
4. A error will be raised, `Error executing API call (422: Unprocessable Entity): Order line 2 is invalid. The field 'productUrl' should be a valid URL.. Field: lines.2.productUrl. Documentation: https://docs.mollie.com/guides/handling-errors`

**Expected behavior**
This order should be accepted by Mollie

**Actual behavior**
See reproduce section

**Screenshots**
![image](https://user-images.githubusercontent.com/1163348/102610418-13665100-4125-11eb-96df-bb0c017398d3.png)
![image](https://user-images.githubusercontent.com/1163348/102610650-7821ab80-4125-11eb-9f93-068c5f3e1cce.png)

**Additional context**
Either the API at Mollie should accept or the module must escape the URL.

**Comment by Frank-Magmodules** [comment]
Hi @JeroenBoersma,
We are happy to share that we've just released the new [1.20.1](https://github.com/mollie/magento2/releases/tag/v1.20.1) version with a fix for this issue. Thank you for the detailed report and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
