### ISSUE TITLE
In-shop credit card data entering blocks payment - locale is invalid

### ISSUE THREAD

**Issue by bamboekeizer** [mollie/magento2#338]
When Mollie Components are enable for credit card payments, the user cannot complete a purchase because a  Locale is invalid message is displayed.

**Used versions**
- *Magento Version : 2.3.6
- *Open source
- *Mollie version number: 1.20.0
- Onestepcheckout: 4.0.0

**To Reproduce**
1. In admin: Enable Mollie Components for credit card
2. In admin: Enter the profile ID , required for credit card mollie components
3. In the front end, as buyer, put a product in the card and go to checkout
2. Select Credit Card payment
3. Enter credit card details
4. Hit Purchase button
5. See error message "Locale is invalid" 

**Expected behavior**
Order created

**Actual behavior**
Error message displayed "Invalid locale"

**Screenshots**
![image](https://user-images.githubusercontent.com/28304222/103020615-07c1c280-4549-11eb-8fbf-9ee0d3c38d8c.png)

![image](https://user-images.githubusercontent.com/28304222/103020683-23c56400-4549-11eb-900f-2dd333bded2e.png)

**Additional context**
The workaround is to disable Mollie components

**Comment by Frank-Magmodules** [comment]
Hi @bamboekeizer,
We are happy to share that we've just released the new [1.20.1](https://github.com/mollie/magento2/releases/tag/v1.20.1) version with a fix for this issue. Thank you for the detailed report and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
