### ISSUE TITLE
order import fails when second chance email enabled and other payment gateway is used.

### ISSUE THREAD

**Issue by awglaat** [mollie/magento2#339]
**Describe the bug**
When "Second Chance Email" is enabled and orders are imported using a different gateway (e.g. platforms that have external payment gateway) some platform imports have difficulties creating orders.

**Used versions**
- *Magento Version number(eg 2.3.5)*:
- *Open source/Enterprise/B2b*:
- *Mollie version number (Check configuration)*:
magento 2.4 (LATEST from composer)
mollie 1.20 (LATEST from composer)

**To Reproduce**
1. enable second chance email
2. create an order using framework/api using a different payment gateway.

**Expected behavior**
No error generation during order creation e.g.
extending the observer function in
vendor/mollie/magento2/Observer/SalesOrderPlaceBefore/RemovePendingPaymentReminders.php 

to check if mollie was used as payment gateway.

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Additional context**

TypeError: Argument 1 passed to Mollie\Payment\Service\Order\DeletePaymentReminder::byEmail() must be of the type string, null given, called in /home/sabe/domains/anything.com/public_html/vendor/mollie/magento2/Observer/SalesOrderPlaceBefore/RemovePendingPaymentReminders.php on line 51 and defined in /home/sabe/domains/anything.com/public_html/vendor/mollie/magento2/Service/Order/DeletePaymentReminder.php:58 Stack trace: #0 /home/sabe/domains/anything.com/public_html/vendor/mollie/magento2/Observer/SalesOrderPlaceBefore/RemovePendingPaymentReminders.php(51): Mollie\Payment\Service\Order\DeletePaymentReminder->byEmail() #1 /home/sabe/domains/anything.com/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Mollie\Payment\Observer\SalesOrderPlaceBefore\RemovePendingPaymentReminders->execute() #2 /home/sabe/domains/anything.com/public_html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() #3 /home/sabe/domains/anything.com/public_html/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch() #4 /home/sabe/domains/anything.com/public_html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch() #5 /home/sabe/domains/anything.com/public_html/vendor/magento/module-sales/Model/Order.php(1189): Magento\Framework\Event\Manager\Proxy->dispatch() #6 /home/sabe/domains/anything.com/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place() #7 /home/sabe/domains/anything.com/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent() #8 /home/sabe/domains/anything.com/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}() #9 /home/sabe/domains/anything.com/public_html/generated/code/Magento/Sales/Model/Order/Interceptor.php(507): Magento\Sales\Model\Order\Interceptor->___callPlugins() #10 /home/sabe/domains/anything.com/public_html/vendor/magento/module-sales/Model/Service/OrderService.php(209): Magento\Sales\Model\Order\Interceptor->place() #11 /home/sabe/domains/anything.com/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place() #12 /home/sabe/domains/anything.com/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent() #13 /home/sabe/domains/anything.com/public_html/vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php(195): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}() #14 /home/sabe/domains/anything.com/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin->aroundPlace() #15 /home/sabe/domains/anything.com/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}() #16 /home/sabe/domains/anything.com/public_html/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(117): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins() #17 /home/sabe/domains/anything.com/public_html/vendor/magento/module-

**Comment by Frank-Magmodules** [comment]
Hi @awglaat,
We are happy to share that we've just released the new [1.20.1](https://github.com/mollie/magento2/releases/tag/v1.20.1) version with a fix for this issue. Thank you for the detailed report and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs
