### ISSUE TITLE
Add images for payment methods in graphql api

### ISSUE THREAD

**Issue by oneserv-heuser** [mollie/magento2#343]
# Describe the new feature
Via the graphql api the field mollie_available_issuers has the fields image and svg. I'd like to request that those fields are added to the AvailablePaymentMethod type to make it easier to show an image for the payment methods.
## Describe the solution to be implemented
The graphql type AvailablePaymentMethod gets extended with the fields image and svg if the payment method is one of mollies payment methods.

**Comment by Frank-Magmodules** [comment]
Another good idea, thank you! We are happy to share that we've just released the new [1.21.0](https://github.com/mollie/magento2/releases/tag/v1.21.0) version with this feature. 
Thank you again for sharing this improvement! We are closing this issue for now.

**Comment by oneserv-heuser** [comment]
@Frank-Magmodules Thank you for implementing the feature!

But I've got the following error: The field for the images returns something like the following: 
https://domain.de/pub/static/version1611149040/graphql/_view/de_DE/Mollie_Payment/images/methods/klarnapaylater.svg

But the problem is that there is no namespace graphql for static files.
If you have a look [here](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-static-view.html#config-cli-subcommands-staticview) it says that valid area codes for deploying static files are either frontend or adminhtml.

I think the images should be placed inside the frontend directory, like Magento is doing it for all images, even if used via graphql. The images of the payment methods are already placed there so just the returned path from the query must be adjusted to return (in my example) https://domain.de/pub/static/version1611149301/frontend/Magento/luma/de_DE/Mollie_Payment/images/methods/klarnapaylater.svg

Thanks!

**Comment by oneserv-heuser** [comment]
@Frank-Magmodules  I openend an extra ticket for that: https://github.com/mollie/magento2/issues/349
