### ISSUE TITLE
Add parsing of PWA Storefront Integration Custom return url

### ISSUE THREAD

**Issue by oneserv-heuser** [mollie/magento2#346]
# Describe the new feature
I'd like to be able to not be required to hardcode the Custom return url for the PWA Storefront Integration in the magento adminhtml.
There is a note below which says: "This URL is not being parsed. You need to enter the complete url.".
This field should be parsed like and it should be possible to add placeholders like "{{secure_base_url}}" the same way it's possible in the Web Section of the General Tab where we can store all urls.

Also the field should be stored in the app/etc/config.php if it's not required to hardcode it anymore.

## Describe the solution to be implemented
The field "mollie_advanced_pwa_storefront_integration_custom_redirect_url" in the backend should accept placeholders like  "{{secure_base_url}}" and It's content should be parsed and saved to app/etc/config.php.

**Backend changes**
See above.

**Comment by Frank-Magmodules** [comment]
Good idea @oneserv-heuser ! We are happy to share that we've just released the new [1.21.0](https://github.com/mollie/magento2/releases/tag/v1.21.0) version with this feature. 
Thank you again for sharing this improvement! We are closing this issue for now.
