### ISSUE TITLE
Images for payment methods in graphql api return wrong path

### ISSUE THREAD

**Issue by oneserv-heuser** [mollie/magento2#349]
**Describe the bug**
The field for image (in MolliePaymentMethodMeta) returns something like the following:
https://domain.de/pub/static/version1611149040/graphql/_view/de_DE/Mollie_Payment/images/methods/klarnapaylater.svg

But the problem is that there is no namespace graphql for static files.
If you have a look [here](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-static-view.html#config-cli-subcommands-staticview) it says that valid area codes for deploying static files are either frontend or adminhtml.

I think the images should be placed inside the frontend directory, like Magento is doing it for all images, even if used via graphql. The images of the payment methods are already placed there so just the returned path from the query must be adjusted to return (as example) the following:
https://domain.de/pub/static/version1611149301/frontend/Magento/luma/de_DE/Mollie_Payment/images/methods/klarnapaylater.svg

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.1
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 1.21.0

**To Reproduce**
1. Add products to a cart via graphql
2. Get the available payment methods for the cart and request the field image from the field mollie_meta.
3. Copy the answer for the image and try to access it in your browser.
3. You'll get an 404.

**Expected behavior**
The field image in MolliePaymentMethodMeta should return something like the following:
https://domain.de/pub/static/version1611149301/frontend/Magento/luma/de_DE/Mollie_Payment/images/methods/klarnapaylater.svg

**Actual behavior**
The field image in MolliePaymentMethodMeta returns something like the following:
https://domain.de/pub/static/version1611149040/graphql/_view/de_DE/Mollie_Payment/images/methods/klarnapaylater.svg

Original ticket for adding the image field: https://github.com/mollie/magento2/issues/343

**Comment by Frank-Magmodules** [comment]
HI @oneserv-heuser , Thank you for opening and reporting this issue. 
We have created an internal task for this issue and will try to come back to you as soon as possible. 
Again, thank you for your patience and clear issue-description(s)!

**Comment by oneserv-heuser** [comment]
@Frank-Magmodules 

Thank you! I think it would be nice to always inform creators of issues if you're working on it.

Besides that I have to say that you guys are doing an awesome job of clearing issues and implementing features. Huge shoutout to you guys! I'm very happy that you're the ones maintaining this repo.

**Comment by Frank-Magmodules** [comment]
HI @oneserv-heuser  ,

We are happy to share that we've just released the new [1.22.0](https://github.com/mollie/magento2/releases/tag/v1.22.0) version with a fix for this issue. Thank you again for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
