### ISSUE TITLE
Recurrent payments in Magento?

### ISSUE THREAD

**Issue by aqdennis** [mollie/magento2#350]
According to the website ecurrent will soon be available for Magento....but can anybody give an indication what is soon? Within months? Still more than a year?
We're selling monthly subscriptions that we would love to automate through Mollie.

**Comment by Frank-Magmodules** [comment]
Hi @aqdennis ,

Thank you for opening this issue!
We have planned the implementation of a subscription functionality based on the Mollie API for Q2 2021.

**Comment by MerijnMollie** [comment]
Hi @aqdennis,

I would like to get a better understanding of what you're exactly looking for!
Could you please send an email to: merijn@mollie.com with a short intro of your needs? Then I'll followup on that:)

Thanks!
Merijn
(Technical Partner Manager mollie)

**Comment by breakerh** [comment]
@MerijnMollie better late then never. But maybe integrate it as a Amasty Recurring Payment extension?

**Comment by MerijnMollie** [comment]
Hi @breakerh ,

We are almost done with building our own separate addition to our plugin!
So, keep an eye on the next couple of releases.

**Comment by Frank-Magmodules** [comment]
HI @breakerh ,

We are excited to share that we've just launched that allows you to create subscription products with Mollie and have recurring payments within Magento! See;

[https://github.com/mollie/magento2-subscriptions/releases](https://github.com/mollie/magento2-subscriptions/releases)  
  
Thank you for your patience on this!

**Comment by LucasVollebergh** [comment]
Hi @Frank-Magmodules, 
Looking in to recurring payments for multiple customers. 
How does this exactly work? Is this compatible with https://amasty.com/subscriptions-recurring-payments-for-magento-2.html ?

**Comment by Frank-Magmodules** [comment]
Hi @LucasVollebergh,

Thank you for your question! I’m not familiar with Amasty Subscriptions, so I can’t provide specific insights on that. However, I can explain how the Mollie subscriptions module works.

With Mollie, merchants can mark specific products as “recurring” by defining an interval, which is fully configurable. When a customer orders one of these products, a subscription is created. Based on the specified interval, transactions are then automatically generated by Mollie. Each transaction also results in an order being created within Magento.

For example, you could configure a product with a 2-week interval. Every 2 weeks, Mollie will generate a transaction, which will then create an order in Magento. Customers always have the option to cancel their subscriptions through their account.

I hope this helps clarify things! Let me know if you have any additional questions.
