### ISSUE TITLE
How to add a Mollie payment method to admin create order?

### ISSUE THREAD

**Issue by onopko81** [mollie/magento2#351]
Hi,
On our site, only mollie is active as a payment method. If we want to create an order from the backend, it appears that there is no information regarding payment methods

how resolve it?

**Comment by Frank-Magmodules** [comment]
HI @onopko81 , thank you for opening this issue. 

To use Mollie Payment methods in a back-end order you have to enable the payment option **Payment Link / Admin Payment** in the configuration of the Mollie extension. 

Do you enable this?

**Comment by onopko81** [comment]
yes, it's enabled.

https://ibb.co/6X72Nk0

**Comment by onopko81** [comment]
We solved, a payment forms management module was active that was blocking. now it is OK. thanks

**Comment by Frank-Magmodules** [comment]
Perfect @onopko81.
We are closing this issue now.

Frank
