### ISSUE TITLE
Error in all payment methods

### ISSUE THREAD

**Issue by phagens** [mollie/magento2#353]
I updated the api version to the latest and also the magento 2 to 1.21.0
Now whatever payment methoid I use I get an error:

[2021-02-04T16:27:46+0000] Error executing API call (422: Unprocessable Entity): A card token must start with tkn_. Field: cardToken. Documentation: https://docs.mollie.com/reference/v2/payments-api/create-payment

in the log I see:

Mollie.INFO: request: {"amount":{"currency":"EUR","value":"99.20"},"description":"500041921","billingAddress":{"streetAndNumber":"Florijnstraat 6 C","postalCode":"4879AH","city":"Etten-Leur","region":null,"country":"NL"},"redirectUrl":"https://www.staging.jukebox-revival.eu/mollie/checkout/process/?order_id=454929&payment_token=gkE0r9qnAtMh3DDl7VQNgvd0ZtQeUFJm&utm_nooverride=1","webhookUrl":"https://www.staging.jukebox-revival.eu/mollie/checkout/webhook/?isAjax=1","method":"ideal","metadata":{"order_id":"454929","store_id":"6","payment_token":"gkE0r9qnAtMh3DDl7VQNgvd0ZtQeUFJm"},"locale":null,"shippingAddress":{"streetAndNumber":"Florijnstraat 6 C","postalCode":"4879AH","city":"Etten-Leur","region":null,"country":"NL"},"cardToken":"","issuer":"ideal_ABNANL2A"} [] []
[2021-02-04 15:58:22] Mollie.ERROR: error: [2021-02-04T15:58:22+0000] Error executing API call (422: Unprocessable Entity): A card token must start with tkn_. Field: cardToken. Documentation: https://docs.mollie.com/reference/v2/payments-api/create-payment [] []
...

**Comment by Frank-Magmodules** [comment]
Hi @phagens , 

Can you please contact us directly through our [support form](https://www.magmodules.eu/support-form.html) so we can exchange login details? 
As we are not able to reproduce this issue on our end.

**Comment by phagens** [comment]
Hallo,

Heb ik gedaan

Inmiddels ben ik er achter dat het fout gaat met mijn account met daaraan gekoppeld meerdere adressen.
Als ik als gast uitcheck werkt het wel.


m.vr.gr. – with best regards


Piet Hagens
Jukebox Revival
Florijnstraat 6 C
4879 AH  Etten-Leur

Website: www.jukebox-revival.nl
Webshop: www.jukebox-revival.eu

[logo]
P Please consider the environment before printing this e-mail

The information sent with this e-mail message is only for the strict use of the intended recipient. In the event that this e-mail message is incomplete in any way, the recipient is kindly requested to contact the sender of this message. It is not permitted to publish, copy, circulate and/or disclose any of this information to third parties without the permission of Jukebox Revival. If you are not the intended recipient of and are in possession of this e-mail message, please notify us immediately, delete the e-mail message from your inbox, and do not use it for any purpose or disclose the contents of this message to third parties, or publish, copy or store this information on an information carrier.



Van: Frank Tiggelman <notifications@github.com>
Verzonden: donderdag 4 februari 2021 19:40
Aan: mollie/magento2 <magento2@noreply.github.com>
CC: Jukebox Revival <info@jukebox-revival.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [mollie/magento2] Error in all payment methods (#353)


Hi @phagens<https://github.com/phagens> ,

Can you please contact us directly through our support form<https://www.magmodules.eu/support-form.html> so we can exchange login details?
As we are not able to reproduce this issue on our end.

**Comment by phagens** [comment]
After cleaning the shopping cart it was not possible to reproduce

**Comment by BergMedia** [comment]
Hi there Magmodules, the same here:

`Mollie.ERROR: error: [2021-02-23T16:34:55+0000] Error executing API call (422: Unprocessable Entity): A card token must start with tkn_. Field: cardToken. Documentation: https://docs.mollie.com/reference/v2/payments-api/create-payment [] []`

It is impossible to place an order when the user creates a new account or uses a customer address from the address book.
The card token is empty. We use now the 1.22.0, but we have investigated the failure with 1.19 / 1.20 / 1.21 – all tests under the sandbox. 

Any hints? Best regards.
