### ISSUE TITLE
Can not update to latest version when performing setup:upgrade Uncaught TypeError

### ISSUE THREAD

**Issue by ginos87** [mollie/magento2#355]
When trying to update to the latest version I get the following error: 

`PHP Fatal error:  Uncaught TypeError: Argument 3 passed to Mollie\Payment\Setup\UpgradeData::updateCustomerReturnUrlForScope() must be of the type string, null given`

In the code of the UpgradeData I see this:

`  $collection = $this->configReaderFactory->create()->addFieldToFilter('path', [
            'eq' => 'payment/mollie_general/custom_redirect_url'
        ]);
`

But in our admin, we don't use a custom redirect url. Could this be related? (see screenshot)

Our Mollie Magento 2 plugin is on version 1.12.2

![Screenshot 2021-02-10 at 21 06 21](https://user-images.githubusercontent.com/16663890/107565309-d62db500-6be3-11eb-9b35-aca11199c7b4.png)

**Comment by Frank-Magmodules** [comment]
HI @ginos87 ,

We are happy to share that we've just released the new [1.22.0](https://github.com/mollie/magento2/releases/tag/v1.22.0) version with a fix for this issue. Thank you for the detailed reports and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by ginos87** [comment]
@Frank-Magmodules just a quick question? I was updating via composer the plugin but it doesnt go above 1.18.1
![Screenshot 2021-02-15 at 19 24 01](https://user-images.githubusercontent.com/16663890/107981918-63498300-6fc3-11eb-99aa-a554d265950f.png)
