### ISSUE TITLE
"no payment methods" problem

### ISSUE THREAD

**Issue by xepthia** [mollie/magento2#36]
I'm currently using Magento 2.2 and I cant test credit card payment

This is checout section, as you can see it says "no payment methods"
![screen](https://user-images.githubusercontent.com/9076959/31407692-0a530596-ae06-11e7-9a2f-31da67ce87c8.PNG)

Currecy setting (euro)
![currency setup](https://user-images.githubusercontent.com/9076959/31407694-0a9ec60c-ae06-11e7-8c78-a35fcb86a618.PNG)

Mollie Settings
![general_settings](https://user-images.githubusercontent.com/9076959/31407695-0acd5472-ae06-11e7-9111-160ff2b923d9.PNG)

Credit Card settings
![credit card settings](https://user-images.githubusercontent.com/9076959/31407693-0a7731dc-ae06-11e7-8f4a-e20de58a871d.PNG)

My mollie logs
![logs](https://user-images.githubusercontent.com/9076959/31407690-0a2ae3e0-ae06-11e7-9ba7-d9138c0e0c3a.PNG)
this errors from yesterday, before entering test-api key. No new error log.

Mollie Test results.
![test2](https://user-images.githubusercontent.com/9076959/31407824-a0aa182c-ae06-11e7-8b7f-6d4cc68db8d0.PNG)
![test 1](https://user-images.githubusercontent.com/9076959/31407825-a0cf4304-ae06-11e7-9a8d-68cad2858798.PNG)

and yes I tried these commands.
bin/magento setup:di:compile
bin/magento setup:upgrade

**Comment by magmodules** [comment]
Hi, did you enable the creditcard method under your test account at https://www.mollie.com/dashboard/

**Comment by magmodules** [comment]
Hi @xepthia , are you still having this problem? 
Please make sure that you are running on the latest/new release of this extension. 

If the problems still remains, please re-open this issue.
Frank
