### ISSUE TITLE
Class PaymentFactory does not exist

### ISSUE THREAD

**Issue by devboys2keer** [mollie/magento2#364]
Testing the apikeys and it got stuck loading found an 500 error in the console log:
POST https://example.com/shopadmin/mollie/action/apikey/key/xxxxxxx/?isAjax=true 500 error
Went to that url and found the following error
Class Mollie\Payment\Service\Mollie\Order\PaymentFactory does not exist

This is used in Payment\Service\Mollie\Order\RefundUsingPayment.php

Magento 2.3.6
Mollie Payment v1.23.0
Mollie API v2.29.0

I don't have any terminal access so I downloaded the zip file of version 2.29.0
Any solutions perhaps?

**Comment by Frank-Magmodules** [comment]
Hi @devboys2keer, the module can not be installed using only FTP.

There are two methods of installation:
https://github.com/mollie/magento2/wiki/Installation-using-Composer
https://github.com/mollie/magento2/wiki/Installation-using-Marketplace

If you don't have terminal access, you can use the Magento Marketplace to install the module. We are closing this issue now, but feel free to reopen if you got stuck with installing the module using the Marketplace.
