### ISSUE TITLE
MultiShipping;  PlaceOrderInterface not found

### ISSUE THREAD

**Issue by JelleGe** [mollie/magento2#375]
We fetch the following error with the latest version (1.25.0) when we run the php bin/magento setup:di:compile command;

PHP Fatal error:  Uncaught Error: Interface 'Magento\Multishipping\Model\Checkout\Type\Multishipping\PlaceOrderInterface' not found in /vendor/mollie/magento2/Multishipping/PlaceOrder.php:19
Stack trace:
#0 /vendor/composer/ClassLoader.php(444): include()
#1 /vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/d...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Mollie\\Payment\\...')
#3 [internal function]: spl_autoload_call('Mollie\\Payment\\...')
#4 /setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Mollie\\Payment\\...')
#5 /setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Mollie\\Payment\\...', 'd...')
#6  in /vendor/mollie/magento2/Multishipping/PlaceOrder.php on line 19

**Comment by Frank-Magmodules** [comment]
HI @JelleGe ,

Thank you for opening the issues, as you didn't use our issue template, I don't have any information about your Magento version and/or if you may be removed MultiShipping from your Magento Core? 

We captured most situations regarding the case if the MultiShipping is not used or removed but it seems in your case this is still happening somehow. Please contact us through our [contact form](https://www.magmodules.eu/support-form.html) with more information about your environment so we can help you out.

_I've updated the issue title as well._
Thanks!

**Comment by JelleGe** [comment]
Hi Frank,

Thanks! We use M2.4.2 and indeed we also disabled the MSI module of Magento.

**Comment by Frank-Magmodules** [comment]
Hi @JelleGe and @peterjaap , we've just released  [1.25.1 ](https://github.com/mollie/magento2/releases/tag/v1.25.1) where we removed the Multishipping code as we are moving this to its own sub-module later this week. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by peterjaap** [comment]
Thanks!!
