### ISSUE TITLE
incorrect notification for second shipment

### ISSUE THREAD

**Issue by bamboekeizer** [mollie/magento2#377]
**Describe the bug**
Mollie reports a notification "Alle items uit deze bestelling zijn al gemarkeerd als verzonden in het Mollie Dashboard." when you create a second shipment for an order.

**Used versions**
- *Magento Version 2.3.6-p1
- *Open source
- *Mollie version number *: v1.24.0

**To Reproduce**
1. Order with two items
2. Create a shipment for the first item
3. Create a shipment for the second item
4. See notification "Alle items uit deze bestelling zijn al gemarkeerd als verzonden in het Mollie Dashboard."
5. Shipment is created

**Expected behavior**
Second shipment create without notification

**Actual behavior**
Notification message displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/28304222/114274826-866f3c80-9a20-11eb-93f8-ea1e91da703f.png)
![image](https://user-images.githubusercontent.com/28304222/114274848-96871c00-9a20-11eb-951c-8dd52047afd4.png)

**Comment by Frank-Magmodules** [comment]
Hi @bamboekeizer , 

Thank you for your message. It seems we can't reproduce this issue in our environments. 
Can you maybe [share](https://www.magmodules.eu/support-form.html) your environment details with us so we can take a look at this?

Frank

**Comment by Frank-Magmodules** [comment]
Hi @bamboekeizer,
Any update on this issue? As we didn't received any further details on this issue.

**Comment by Frank-Magmodules** [comment]
Hi @bamboekeizer , 

We didn't receive any further details on this issue, can we close this issue or can you share the status?

**Comment by bamboekeizer** [comment]
I'm now on v1.25.2 and the issue has vanished, luckily.
