### ISSUE TITLE
Banktransfer method is not visible in frontend in mollie magento 2

### ISSUE THREAD

**Issue by ManishRaghani** [mollie/magento2#38]
Please help me with the code as Bank transfer method is not visible in checkout page during payment.
![capture](https://user-images.githubusercontent.com/21340937/32889795-4359639a-caf2-11e7-9797-4e5d5b86cf1f.PNG)

**Comment by magmodules** [comment]
Hi @ManishRaghani , Thanks for your comment, 2 questions;

1. Did you also activated the Banktransfer payment method in your Mollie account?
2. Is the selftest and API check showing all positive results?

Thanks, 
Frank

**Comment by ManishRaghani** [comment]
Yes sir, I activated banktransfer method and my API keys gave positive
result.

**Comment by magmodules** [comment]
Hi @ManishRaghani , also in your Mollie Account?
If so, please sent me some temporary login details to frank@magmodules.eu so we can help you out with this.

Frank
