### ISSUE TITLE
Request to support more (if not all) accelerated payment methods both on PDP + CART + Checkout

### ISSUE THREAD

**Issue by seansan** [mollie/magento2#380]
Note. Some or parts may be implemented already, however this is an integral ticket to support all accelerated payment methods both on PDP + CART + Checkout using the native Mollie M2 extension.

## Describe the solution to be implemented

- Implement all accelerated payment methods using on/off switches in the backend, for
- [ ] Apple Pay
- [ ] Google Pay
- [ ] Paypal Express
- [ ] iDIN icw iDeal
 
Note. Accelerated payment methods are payment methods that use a 1-click payment where the user does not have to enter billing and shipping details, the checkout is just 1-click. Methods exist for _both_ mobile and desktop. Read more about it here and maybe use this as a reference https://help.shopify.com/en/manual/payments/accelerated-checkouts

Note. By implementing iDIN icw iDeal one can access shipping details and finishing the payment in 1 or 2 sweeps making it also an accelerated payment method.

- Implement the above payment methods on all locations
- [ ] Product page / PDP
- [ ] Cart (most important)
- [ ] Checkout

Note. All methods should be available via config in the Checkout (using the 1 click variant, so not pointing at the normal flow here). All methods should be available via config in the Cart (this is important because siome shops are not made for 1 item sales, rather multisales where there is always a cart). All methods should be available via config on the product PDP.

Note. Setup and flow is known, however not native in the Mollie M2 extension. Seeing the enormous increase in 1-click payment methods and the new capabilities it brings it should be covered as part of the "mollie future payment roadmap/vision". Some parts are already described but not easily accessible preventing easy adoption and a true distinguisher from other payment providers (PSPs). https://docs.mollie.com/orders/paypal-express-checkout-button and https://docs.mollie.com/guides/applepay-direct-integration.

**Backend changes**
- All 4 accelerated payment methods ((or more payment methods) schould exist and can be enabled using yes/no
- All 4 accelerated payment methods should have options to enable it on any or all of the following 3 *) PDP *)Cart *Checkout
- Controller/Methods to process the payment

**Frontend changes**
- Addif/else routines for *) PDP *)Cart *Checkout templates
- Provide graphQL access for the same (so it supports [Hyva](https://demo.hyva.io/) and other PWA's)
 
**Additional context**
Also reported at Mollie Tech and Account managers. In addition I would like to ask all merchants and implementation parties to do the same and send this request to your account manager at Mollie /w a reference to this ticket. It is the future.

**Additional references**
- https://docs.withreach.com/docs/accelerated-checkout
- https://help.shopify.com/en/manual/payments/accelerated-checkouts
- https://forum.hearingtracker.com/uploads/default/original/2X/1/1631e8d47abe340110942822bb36296c19effc51.jpg
- https://outofthesandbox.com/blogs/shopify-theme-blog/customize-shopify-checkout-pages
- https://cdn.shopify.com/s/files/1/0200/7466/files/express-checkout-or_d7530793-3905-4317-b0fa-3d6d1d029b68.png?v=1594125540

![image](https://user-images.githubusercontent.com/652395/114723975-6bac0900-9d3b-11eb-9c64-8207b087f133.png)

![image](https://user-images.githubusercontent.com/652395/114724214-9eee9800-9d3b-11eb-97ba-b751dec82751.png)

**Comment by Frank-Magmodules** [comment]
Hi @seansan ,

Thank you for opening this issue a while ago. Some good ideas were shared here, thanks for that but most of the requests or currently not on the schedule for Mollie and/or the Magento plugin to implement.

GraphQL support is already available and Apple Pay is there as well for product pages. The other named methods and features are not on the roadmap for the short term, for this reason, we will close this issue and ask you to keep an eye on the [roadmap](https://github.com/mollie/magento2/blob/master/ROADMAP.md) to check out what we are working on for the upcoming releases.

Thanks again!
