### ISSUE TITLE
Bancontact outdated logo

### ISSUE THREAD

**Issue by watista** [mollie/magento2#382]
**Describe the bug**
Bancontact changed their logo on January 26, 2021. The old logo is still used for the payment icon.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.3.5-p1
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: v.1.24.0

**To Reproduce**
Check payment methods on the frontend

**Expected behavior**
New icon displayed

**Actual behavior**
[Old icon displayed](https://github.com/mollie/magento2/blob/master/view/frontend/web/images/methods/bancontact.svg)

**Screenshots**
![image](https://user-images.githubusercontent.com/37804556/116160377-336cd900-a6f2-11eb-8fc8-e78a6624bbbd.png)

**Additional context**
The new logo can be found at : https://www.bancontact.com/en/promotion-material/guidelines-logo

**Comment by Frank-Magmodules** [comment]
HI @watista ,

Thank you for opening this issue, we will renew the Bancontact image in the next release.
We will update this ticket once released.

**Comment by Frank-Magmodules** [comment]
HI @watista ,
We are happy to share that we've just released version [1.25.2](https://github.com/mollie/magento2/releases/tag/v1.25.2
) with the updated Bancontact icon. 
Thank you for the detailed report and patience. We are closing this issue now but please feel free to reopen if it doesn't fit your needs.
