### ISSUE TITLE
PWA Storefront Integration custom return url validation

### ISSUE THREAD

**Issue by niklaswolf** [mollie/magento2#384]
**Describe the bug**
When trying to use the feature described in #346 I get the following validation error (see screenshot) when trying to enter the custom return url with placeholders. The placeholder "secure_base_url" already contains the protocol, so it would be wrong to specify it again.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.1
- *Open source/Enterprise/B2b*: Enterprise
- *Mollie version number (Check configuration)*: 1.25.1

**Expected behavior**
No validation error when using placeholders für base_url

**Actual behavior**
Validation error for missing protocol

**Screenshots**
<img width="923" alt="Bildschirmfoto 2021-04-30 um 10 00 26" src="https://user-images.githubusercontent.com/16021919/116666330-1f97d000-a99b-11eb-8103-0ec6790447be.png">

**Additional context**
related to #346

**Comment by Frank-Magmodules** [comment]
HI @niklaswolf ,

Thank you for opening and reporting this issue.
We have created an internal task for this issue and will try to come back to you as soon as possible.

**Comment by Frank-Magmodules** [comment]
Hi @niklaswolf,
We are happy to share that we've just released version [1.25.2](https://github.com/mollie/magento2/releases/tag/v1.25.2
) with a fix for this issue. 
Thank you for the detailed report and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
