### ISSUE TITLE
Payment surcharge not displayed correctly

### ISSUE THREAD

**Issue by tropilex** [mollie/magento2#389]
**Describe the bug**

The payment surcharge is not displayed correctly in the back-end, transactional emails and invoice (PDF).

In the order below, a 2% payment fee has been added.

**Order overview:**

Grand total is correct. But total paid is not correct.

![Screenshot 2021-05-14 at 12 24 28](https://user-images.githubusercontent.com/53861858/118258125-c908b680-b4af-11eb-9046-3573c0c0f41c.png)

**Invoice overview:**

Grand total is not correct.

![Screenshot 2021-05-14 at 12 29 35](https://user-images.githubusercontent.com/53861858/118258377-0ec57f00-b4b0-11eb-9aac-6dba265fd927.png)

**Used versions**
- *Magento Version number*: 2.4.2
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number*: 1.22.0

**Comment by Frank-Magmodules** [comment]
Hi @tropilex,

Seems this issue is also relevant to your other issue https://github.com/mollie/magento2/issues/381 and for this i want to ask the same; please update to the latest version to let me know if this fixes your issue.

**Comment by Frank-Magmodules** [comment]
HI @tropilex , can you let me know if you still have this issue with the latest version of the Mollie plugin?

**Comment by tropilex** [comment]
@Frank-Magmodules We updated to the latest version. We still got this issue.

Screenshots in first post are also apply to orders / payments after the update.

**Comment by Frank-Magmodules** [comment]
HI @tropilex ,

Strange, we can't reproduce this in our own environments and we don't have any known issues with this, therefore, can you please share your environment details through our [contact form](https://www.magmodules.eu/support-form.html) so we can take a look with you on this?
