### ISSUE TITLE
Problem with payment not showing up?

### ISSUE THREAD

**Issue by flexxus** [mollie/magento2#39]
Somehow the payment methods are not showing up and mollie not making a log file? I am using a test key since the domain is the making our test site 

my website is directled.nl 

I hope you can help me out.

**Comment by magmodules** [comment]
Please check: https://github.com/mollie/magento2/wiki/Troubleshooting 
Any methods enabled in the Mollie Dashboard: https://www.mollie.com/dashboard/? (these are disabled by default).

**Comment by magmodules** [comment]
Hi @flexxus ,

Did you check check latest question/answer  _"Why there are no payment methods visible in front-end?"_ on https://github.com/mollie/magento2/wiki/Troubleshooting ?

Can you check those 8 points and let me know if it's working for you now?

Thanks,
Frank

**Comment by magmodules** [comment]
HI @flexxus any update on this issue?

**Comment by magmodules** [comment]
Closing this issue, no response. If this issue is still present, please reopen of send us an email:  https://www.magmodules.eu/contact-us.html
