### ISSUE TITLE
"Check for latest versions" button showing earlier version

### ISSUE THREAD

**Issue by alphaLeporis** [mollie/magento2#390]
**Describe the bug**
When pushing the "Check for latest versions" button in the backend, the latest version is a lower version (1.19.0).

**Used versions**
- Magento open source 2.4.1
- Mollie 1.25.2:

**To Reproduce**
1. Go to the backend
2. Click on "Mollie - General"
3. Scroll down to version
4. Click on "Check for latest versions"

**Expected behavior**
"You are running the latest version" or an actual later version.

**Actual behavior**
Shows a previous version.

**Screenshots**
![image](https://user-images.githubusercontent.com/13415729/119223113-e95ff300-baf7-11eb-8a65-5777a2e8ffe4.png)

**Comment by Frank-Magmodules** [comment]
Hi @alphaLeporis ,

Thank you for opening this issue, we've just updated the version so the checks should be showing the latest version now.  We are closing this issue now but please feel free to reopen the issue if this still occurs.
