### ISSUE TITLE
WMS used wrong order statuses when using the Payment Reminder

### ISSUE THREAD

**Issue by downforce80** [mollie/magento2#393]
**Describe the bug**
Not sure if this is a bug but it does affect other systems.

**Used versions**
- Magento 2.2.4 open source
- mollie module v1.25.2

**To Reproduce**
1. Go to 'admin'
2. Select a cancelled order
2. Click on ' Send Payment Reminder'

**Expected behavior**
order state 'pending payment'

**Actual behavior**
we noticed that our WMS picks up this order as ready to process while payment is not yet done and pending.
The WMS picks up any orders which have the state 'processing' so we figured that this module changed order state to 'processing' anywhere in the process.

**Comment by Frank-Magmodules** [comment]
Hi @downforce80 ,

The order status is not going to change from canceled after sending the payment reminder. If a customer does pay the order through the payment link within the payment reminder, a new order will be created with a -1 addition on the current order number.

What order is picked up by the WMS, the -1 order, or the canceled order?

**Comment by downforce80** [comment]
hi @Frank-Magmodules 

Yes i've noticed there has been made a new order with -1.
This specific order gets picked up by our WMS as being paid/processing (maybe for a short time).
Does that make sense?

**Comment by Frank-Magmodules** [comment]
Hi @downforce80 ,

Strange, we don't do anything with the statuses in this flow so I'm not sure if this is the result of the Mollie plugin or another plugin that hooks into this process. Anyway, to debug this, please share details, using our [support form](https://www.magmodules.eu/support-form.html
), the details of your development environment so we can take a look with you on this.

**Comment by downforce80** [comment]
thanks!

**Comment by Frank-Magmodules** [comment]
HI @downforce80 ,

We are happy to share that we've just released the new [1.27.1](https://github.com/mollie/magento2/releases/tag/v1.27.1) version with a fix for this issue. 
Thank you for the detailed issue report and for sharing the exact details through our contact form. 

We are closing this issue now but please feel free to reopen the issue if this still occurs.
