### ISSUE TITLE
Module can not be update higher then 1.23 using composer 2

### ISSUE THREAD

**Issue by JelleGe** [mollie/magento2#394]
**Describe the bug**
The composer 2 installation off the module is locked at 1.23. Newer version can not be installed using composer 2.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.2p1
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 1.23

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Additional context**

**Comment by Frank-Magmodules** [comment]
Hi @JelleGe, in Composer 2 repositories are treated as canonical. 
Once the Mollie package is found in a repository, it will stop looking further. 

We have just submitted the latest version to the Magento Marketplace, but this takes some time. 
To fix this, you can add  "canonical": false to repo.magento.com in your composer.json so it will also search for Mollie versions outside of the Magento repo.

We are closing this issue now but please feel free to reopen if you have any further questions that are related to this.
