### ISSUE TITLE
Error in latest version 1.26 - Compile

### ISSUE THREAD

**Issue by JelleGe** [mollie/magento2#396]
**Describe the bug**
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 72.0 MiBPHP Fatal error:  Uncaught Error: Interface 'Magento\QuoteGraphQl\Model\Cart\Payment\AdditionalDataProviderInterface' not found in /vendor/mollie/magento2/GraphQL/DataProvider.php:10
Stack trace:
#0 /vendor/composer/ClassLoader.php(480): include()
#1 /vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile('/home/d...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Mollie\\Payment\\...')
#3 [internal function]: spl_autoload_call('Mollie\\Payment\\...')
#4 /setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('Mollie\\Payment\\...')
#5 /setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('Mollie\\Payment\\...', '/home/d...')
#6 /home//re in /vendor/mollie/magento2/GraphQL/DataProvider.php on line 10

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.2
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*:

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Additional context**

**Comment by michielgerritsen** [comment]
Hello @JelleGe,

Thanks for opening this issue. Do you happen to have "composer replaced" the GraphQL modules one way or another? This class should be present in 2.4.2:
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/QuoteGraphQl/Model/Cart/Payment/AdditionalDataProviderInterface.php

**Comment by JelleGe** [comment]
Hello @michielgerritsen,

Yes, we did entirely remove the GraphQL modules, to speed up Magento 2, because we do not use it.
Is there a way to update the module and skip this part, if GraphQL is not installed?

**Comment by Frank-Magmodules** [comment]
HI @JelleGe ,

Ah, that makes sense then. We will discuss this internally to find the best way on how to solve this issue in your case. I will get back to you in the short term.

**Comment by MrGekko** [comment]
I have the same issue & reasoning of not using GraphQL

**Comment by Frank-Magmodules** [comment]
Hi @JelleGe,

We are happy to share that we've just released the new [1.26.1](https://github.com/mollie/magento2/releases/tag/v1.26.1) version with a fix for this issue. Thank you again for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by JelleGe** [comment]
Error is back in version 1.27

**Comment by Frank-Magmodules** [comment]
@JelleGe: What is the exact error? Is this the same as in the first post, or is there a different one? The fix for this has a change in the composer.json, did you install the Mollie extension using Composer or did you use a different method?
