### ISSUE TITLE
iDeal thumbnails not showing in checkout Magento 2.4.1

### ISSUE THREAD

**Issue by i6media** [mollie/magento2#397]
**Describe the bug**
iDeal thumbnails not showing in checkout Magento 2.4.1

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.2
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 1.26.0

**To Reproduce**
1. Go to checkout
2. Click on iDeal
3. Scroll down to Issuer List

**Expected behavior**
Show thumbnails

**Actual behavior**
Images are being blocked by CSP

**Additional context**
Add csp_whitelist.xml in /etc folder with the following:

```
<?xml version="1.0"?>
<csp_whitelist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Csp:etc/csp_whitelist.xsd">
    <policies>
        <policy id="img-src">
            <values>
                <value id="mollie" type="host">https://www.mollie.com</value>
            </values>
        </policy>
    </policies>
</csp_whitelist>
```

**Comment by Frank-Magmodules** [comment]
HI @i6media,

We are happy to share that we've just released the new [1.26.1](https://github.com/mollie/magento2/releases/tag/v1.26.1) version with a fix for this issue. Thank you again for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.
