### ISSUE TITLE
Get available payment methods and images

### ISSUE THREAD

**Issue by joggienl** [mollie/magento2#399]
# Describe the new feature

_As a customer I would like to know the payment options of a webshop before I start collecting and ordering items so that I know upfront whether I am able to pay on the website or not._

## Describe the solution to be implemented

I'm using the mollie plugin from a GrapQL context. Currently it is possible to get all available payment options through executing a query on the Cart object. For that to work you will have to know customers cart_id, which is not always the case (not instantiated yet or when doing server side rendering).

It would be nice to have a query that allows getting the configured mollie payment options (with meta data like images) so that you can display them. In the footer of the website as an example.

Query example:

```graphql
query {
   getMolliePaymentMethods {
      code
      title
      mollie_available_issuers {
         code
         image
         name
         svg
      }
      mollie_meta {
         image
      }
   }
}
```

example result:

```json
{
  "available_payment_methods": [
        {
          "code": "mollie_methods_ideal",
          "title": "iDeal",
          "mollie_available_issuers": [
            {
              "code": "ideal_ABNANL2A",
              "image": "https://www.mollie.com/external/icons/ideal-issuers/ABNANL2A%402x.png",
              "name": "ABN AMRO",
              "svg": "https://www.mollie.com/external/icons/ideal-issuers/ABNANL2A.svg"
            }
            // etc....
          ],
          "mollie_meta": {
            "image": "https://....../en_US/Mollie_Payment/images/methods/ideal.svg"
          },
        },
        {
          "code": "mollie_methods_paypal",
          "title": "Paypal",
          "mollie_available_issuers": null,
          "mollie_meta": {
            "image": "https://........./en_US/Mollie_Payment/images/methods/paypal.svg"
          }
        }
        // etc...
      ]
}
```

**Backend changes**

I am mainly focussed on frontend development but I can imagine something like this to be implemented:

```graphql
type Query {
    getMolliePaymentMethods: GetMolliePaymentMethodsOutput
}

type GetMolliePaymentMethodsOutput {
  available_payment_methods: [AvailablePaymentMethod]
}

# AvailablePaymentMethod type is assumed to be the same as is used now within Magento, if it would become a 
# different object, it should obviously be better described
```

**Frontend changes**

Just a new query available to use!

**Additional context**

Just like above, I'm using the mollie plugin from a GrapQL context. Currently it is possible to get all available payment options through executing a query on the Cart object. For that to work you will have to know customers cart_id, which is not always the case. The cart is not always "ready" and if you are doing server side rendering with a headless solution you most often don't have a cart on the server side part (not needed).

I am also not sure how this would affect or even if it should affect the REST part of this module.

Curious to find out the teams thought on this one!

**Comment by Frank-Magmodules** [comment]
Hi @joggienl ,

Thank you for opening this feature request. 
I have created an internal task for your feature request and will try to come back to this as soon as possible.

**Comment by joggienl** [comment]
Thanks for the update @Frank-Magmodules!

**Comment by Frank-Magmodules** [comment]
Hello @joggienl ,

We have implemented a new GraphQL query within the new \[1.27.0 \](https://github.com/mollie/magento2/releases/tag/v1.27.0)release to retrieve the available Mollie payment methods:

  
\`\`\`  
query {   
 molliePaymentMethods(input:{amount:20, currency:“EUR”}) {  
   methods {  
     code  
     image  
     name  
   }  
 }  
}  
\`\`\`

Mollie will return the available methods depending on the amount and currency, that’s why they are configurable.   
We will update the wiki with this information soon.  We are closing this issue now but please feel free to reopen if you still have any thoughts on this feature request.

**Comment by joggienl** [comment]
Hi @Frank-Magmodules,

Awesome, thanks for the work and the update!

Just a question because I can't test it out yet. If i wanted to display all the available methods in the footer of my webshop and I am not having a cart and amount (yet), does that give me all available methods?

Thanks

**Comment by Frank-Magmodules** [comment]
@joggienl ,

Yes, it contacts Mollie directly and asks for the available payment methods depending on the provided currency and/or amount. It does not use the session or cart.
