### ISSUE TITLE
Klarna Pay Later payment status not updated

### ISSUE THREAD

**Issue by akosglue** [mollie/magento2#403]
**Describe the bug**
When we fetch the payment status (or when previously it was automatically fetched) the payment status is not updated, no inovice created, no 'sales_order_payment_pay' event fired.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.2.9
- *Open source/Enterprise/B2b*: os
- *Mollie version number (Check configuration)*: 1.25.2

**To Reproduce**
1. pay with klarna
2. fetch status via button on the admin panel of the order
3. payment remains authorized, not paid
4. event sales_order_payment_pay not fired

**Expected behavior**
payment goes to paid

**Actual behavior**
payment remains authorized

**Screenshots**
you see authorized status, we get paid method via webhook, but to no avail.

<img width="299" alt="Screenshot 2021-06-18 at 11 33 44" src="https://user-images.githubusercontent.com/17706334/122541455-f0f8b600-d029-11eb-82a7-986ce5eb1298.png">
<img width="478" alt="Screenshot 2021-06-18 at 11 32 27" src="https://user-images.githubusercontent.com/17706334/122541464-f229e300-d029-11eb-8909-b4dbd16800de.png">

**Comment by Timollie** [comment]
Hi Akosglue,

thank you for reaching out. I have a quick question, has the order in question been shipped? For Klarna payment methods the order status only becomes completed once the product have been shipped.

Kind regards,
Tim

**Comment by akosglue** [comment]
Hi, in mollie dashboard, the concerning order status is completed and the klarna payment status is paid.
We fetch status in magento backoffice: The latest status from Mollie has been retrieved.
However, the payment status remains Authorized and the order status is Processing. No shipment is made.

**Comment by akosglue** [comment]
Shipment is now created manually in magento admin, so order status is complete in magento. We fetch the payment status again and it remains authorized, shouldn't it be paid just like in mollie?

**Comment by Frank-Magmodules** [comment]
It seems that the Magento version that you are using is not supported by the Mollie plugin anymore but hopefully this comment is a question to your answer.

In case of a Klarna Order, which uses the [OrderAPI](https://docs.mollie.com/reference/v2/orders-api/create-order), first, the successfully placed order will be in _authorized_ state at Mollie with a _pending invoice_ state for the invoice in Magento and a _processing_ state of the order in Magento*.  After the shipment, the status will be _completed_ in Mollie as well in Magento.

Please also see the status changes flow from the [Mollie docs](https://docs.mollie.com/orders/status-changes).

*Depends on the option _When to create the invoice?_ in the _Triggers & Languages_ section under the _Advanced configuration_  within the config of the Mollie plugin.

We are closing this issue now but please feel free to reopen the issue if you still have questions regarding this flow.

**Comment by akosglue** [comment]
well, thanks, however it doesn't clarify why the payment status is still authorized in magento while the payment status is paid in mollie. (after the order status becomes 'complete' by shipping in magento as well as in mollie)

**Comment by Frank-Magmodules** [comment]
Hi @akosglue, I think this is expected behavior in this case but to make sure, we need to debug this in your environment to make sure if this works as it should. Unfortunately, we don't support Magento 2.2.x anymore so please make sure this is a version that is officially supported by Mollie, also, as we don't have any known issues on the support Magento versions. If the issue still exists on the newer Magento version, please [contact us](https://www.magmodules.eu/support-form.html) directly so we can help you to debug this.
