### ISSUE TITLE
PWA Storefront Integration: Custom return url - order_hash description

### ISSUE THREAD

**Issue by SikoraWojciech** [mollie/magento2#404]
Hi!

I've got a problem with using **order_hash** in the custom return url. I want to redirect user to my order confirmation page after the payment, but I don't want to use **order_id** in the url. According to the Note from PWA Storefront Integration section, order_hash contains the entity ID encrypted and base64 encoded, so it would do the trick, but I don't know how retrieve order id from the hash or order by the hash.

Can you help me with explanation how can I decode the order_hash or how can I retrieve order information with it?

I'm creating a feature request because it might be good to have this information in the Wiki.

Thanks.

**Comment by michielgerritsen** [comment]
Hello @SikoraWojciech,

Thanks for opening this issue. There is a GraphQL query available to retrieve order information using the `order_hash`:

```graphql
type Query {
    mollieCustomerOrder (
        hash: "{{order_hash}}"
    ) {
        id
        increment_id
        created_at
        grand_total
        status
    }
}
```

If you want to retrieve the order ID from the hash yourself then you can do the same as here:
https://github.com/mollie/magento2/blob/master/GraphQL/Resolver/Checkout/MollieCustomerOrder.php#L37-L41

Does this anwsers you question?

**Comment by SikoraWojciech** [comment]
Thanks for the fast response @michielgerritsen,

Is there any way to do it with REST API?

**Comment by Frank-Magmodules** [comment]
HI @SikoraWojciech ,

Yes, it is! 
You can call `/V1/mollie/get-order/:hash` which returns the same data.

Please let me know if this fitting your needs and if we can close this issue.
Thank you!

**Comment by SikoraWojciech** [comment]
Hi @Frank-Magmodules 

Great, that exactly what I wanted.
Thanks a lot ;)
