### ISSUE TITLE
Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/vendor/mollie/magento2/Plugin/Quote/Api/PaymentMethodManagementPlugin.php on line 67

### ISSUE THREAD

**Issue by studiocodeur** [mollie/magento2#407]
**Describe the bug**
After installing the module and configuring it in the magento 2 backend. 

**Used versions**
- *Magento Version number(eg 2.4.2):
- *Open source*:
- *Mollie version number v1.27.0:

1. add product to cart
2. choose shipping method
3. error 'Internal Error. Details are available in Magento log file. Report ID: webapi-60d832be57971'

The page needs to go the the actual payment options. But it just hangs..

![Screenshot 2021-06-27 at 10 13 08](https://user-images.githubusercontent.com/24894030/123537554-4de22380-d730-11eb-8ebf-60f07b5920e2.png)

Log files show this error. 

Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/vendor/mollie/magento2/Plugin/Quote/Api/PaymentMethodManagementPlugin.php on line 67

**Comment by Frank-Magmodules** [comment]
Hi @studiocodeur ,

Thanks for opening this issue. The variable should never be null, so it’s weird that you get this error. The only reason for this we come up with is that all methods in the Mollie dashboard are disabled. Is that the case here?  
  
We will implement a fallback to prevent this error in the next release.

**Comment by Frank-Magmodules** [comment]
HI @studiocodeur ,

We are happy to share that we've just released the new [1.27.1](https://github.com/mollie/magento2/releases/tag/v1.27.1) version with a fallback on this error. Thank you for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.
