### ISSUE TITLE
Mollie error after new install

### ISSUE THREAD

**Issue by dbroeders** [mollie/magento2#408]
As we updated our webshop to 2.4.2-p1 we choose to install completley new. (comming from 2.3.5-p1)
Mollie module installed is 1.27.0
Php version : 7.4.20

After installation of the Mollie module we can not : bin/magento setup:di:compile

** error **
In ClassReader.php line 45:
  Impossible to process constructor argument Parameter #0 [ <required> Magento\QuoteGraphQl\Model\Cart\GetCartForUser $cartForUser ] of Mollie\Payment\GraphQL\Resolver\Cart\ResetCart class

In ClassReader.php line 34:
  Class Magento\QuoteGraphQl\Model\Cart\GetCartForUser does not exist

Disabled and composer remove Mollie -- all is ok 
bin/magento setup:di:compile (everything works ok)

Installed Mollie again and we have the same error:

**Comment by Frank-Magmodules** [comment]
Hi @dbroeders ,

We are happy to share that we've just released the new [1.27.1](https://github.com/mollie/magento2/releases/tag/v1.27.1) version with a fix in case that GraphQL is uninstalled in the Magento environment. Thank you for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.
