### ISSUE TITLE
Could not save Order Lines. Error: order line not found

### ISSUE THREAD

**Issue by akosglue** [mollie/magento2#409]
**Describe the bug**
when placing an order with voucher payment we get this error:
Mollie.ERROR: error: Kan Orderregels niet opslaan. Fout: orderregel niet gevonden
It seems that `public function getOrderLinesByOrderId` returns an empty array for a legit order id.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.2.9
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: 1.25.2

**To Reproduce**
1. Go to checkout and place order with payment: voucher
2. page redirects to cart saying: Could not save Order Lines. Error: order line not found
3. See error in mollie log: Mollie.ERROR: error: Kan Orderregels niet opslaan. Fout: orderregel niet gevonden
just after Mollie.INFO: response: ....

**Expected behavior**
redirect to paymant page

**Actual behavior**
redirect to cart page with error message

**Additional context**
in `Model/Client/Orders.php` this line fails `$this->orderLines->linkOrderLines($mollieOrder->lines, $order);`
in `linkOrderLines()` there is a call to `getOrderLinesByOrderId` which returns empty collection.

**Comment by Frank-Magmodules** [comment]
Hi @akosglue, 

Thank you for opening this issue. This issue sometimes occurs when we are debugging certain parts.   
Usually, placing a new order solves the problem for us. 

I see you are using Magento 2.2.9. Unfortunately, we don’t support this version anymore. Therefore I’m closing this issue now. If you upgrade to the latest Mollie version and this issue still occurs, please reopen this issue.
