### ISSUE TITLE
Orders with total of 0 don't work

### ISSUE THREAD

**Issue by oneserv-heuser** [mollie/magento2#415]
**Describe the bug**
When trying to submit an order with the "placeOrder" graphql mutation when it's total is 0 and the selected payment method is the "No payment information required" method it's not possible to submit the order.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.2
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*:  1.28.0

**To Reproduce**
1. Create a product with a price of 0
2. Create an quote via graphql with the product
3. Try to place the order

**Expected behavior**
The order is placed.

**Actual behavior**
The following error occurs:
```JSON
[
  {
    "debugMessage": "[2021-07-13T08:35:55+0000] Error executing API call (422: Unprocessable Entity): The payment method is invalid. Field: method. Documentation: https://docs.mollie.com/guides/handling-errors",
    "message": "Internal server error",
    "extensions": {
      "category": "internal"
    },
    "locations": [
      {
        "line": 6,
        "column": 7
      }
    ],
    "path": [
      "placeOrder",
      "order",
      "mollie_redirect_url"
    ]
  }
]
```

**Comment by Frank-Magmodules** [comment]
HI @oneserv-heuser ,

We are happy to share that we've just released the new [1.29.0](https://github.com/mollie/magento2/releases/tag/v1.29.0) version with a fix for your issue. Thank you for the detailed issue report. We are closing this issue now but please feel free to reopen the issue if this still occurs.
