### ISSUE TITLE
Email adreess word on redirect page

### ISSUE THREAD

**Issue by Krupaly2k** [mollie/magento2#42]
Hi Support,

At the time of redirect, it is showing Email Address above redirect message. How can I remove that. Please help me to fix this.

Thanks

**Comment by magmodules** [comment]
Hi, there is no such thing in the redirect page. The page is using the empty layout handle, can you check the source of this in your theme?

**Comment by Krupaly2k** [comment]
Ok, Thanks

**Comment by magmodules** [comment]
If you need us to check this for you, please drop us a message with the frontend url of the store at:  https://www.magmodules.eu/contact-us.html
