### ISSUE TITLE
Magento Vault / Payment Gateway upgrade 

### ISSUE THREAD

**Issue by Frank-Magmodules** [mollie/magento2#421]
## **Mollie Magento - Magento Payment Gateway upgrade**

Magento has a module called Magento Vault.   
We want to integrate this into the Mollie extension, but what is it, and why should we add - and how?

## **Magento Vault**

The Vault module offers end-user the ability to save and re-use their credit card data. Magento does not protect the data itself: It requires that the data is sent to the PSP, and the returning token is then being saved, including some metadata like the card issuer and the last digits of the number.

## **Why should we add this?**

The benefits for end-users are clear, but it takes a lot of time to complete this upgrade. 

**Why is that?**  
To understand this, we have to go back to the history of Magento 2. Magento 2 was released in November 2015. At that moment, Magento shipped with only one way of implementing payment methods: By extending from the AbstractMethod.   
A few versions later, Magento introduced another method: Magento Payment Gateway. This way of adding payment methods introduced a way where a payment method could be added by mainly adding configuration and only a little bit of code.

**The downside of this method?**  
It is incompatible with the AbstractMethod. It requires quite some effort of the end-user. Now, why should we stop the AbstractMethod route and go to the “new” Payment Gateway route? Mainly because it’s [deprecated](https://github.com/magento/architecture/blob/master/design-documents/abstract-method-removal.md) and probably will be removed somewhere in a future version. 

Next to that: It adds some extra features which we can offer to end-users.

## **How do we upgrade?**

We started migrating from the old to the new method. It turns out that although there are a lot of changes, a lot did stay the same. This means that a lot of the logic in the application can be reused. How long it will take is hard to say, but the total estimated time of release will be September 2021. 

The devil is in the details, which means that this needs a thorough test before releasing it to the public.   
As this is a big refactor, we are probably releasing this as a major release and going from a 1.X tag to a 2.X tag.

**Comment by oneserv-heuser** [comment]
Hey @Frank-Magmodules, very nice!
I recently wrote a custom payment method with the new Gateway and stumbled upon this issue: https://github.com/magento/magento2/issues/33869
JFYI as you will definitly stumble across this issue. I also added a temporary fix there.

**Comment by Frank-Magmodules** [comment]
Thanks, @oneserv-heuser, I've just shared this with our development team and we will definitely take a look into it!

**Comment by Frank-Magmodules** [comment]
We are happy to share that we've just released the all-new [2.0.0](https://github.com/mollie/magento2/releases/tag/v2.0.0) version with the Magento Vault integration!  
Therefore, we are closing this issue for now.
