### ISSUE TITLE
Version check displays a new version to be available, even though it's an old version

### ISSUE THREAD

**Issue by dehaan-jeroen** [mollie/magento2#423]
**Describe the bug**
The button to check for a newer version of the module in the Magento backend displays a new version to be available, while the "new" version is an older version.

![image](https://user-images.githubusercontent.com/80255844/130914467-d78e8ed8-7180-4f07-ae3f-af1e3940cb22.png)

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.2-p1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 1.29.0

**To Reproduce**
1. Go to Stores > Configuration > Mollie > General
2. Click the button to check for a new version
3. See version 1.28.0 to be displayed as a newer version than 1.29.0

**Expected behavior**
A message that no newer version is available should be shown

**Actual behavior**
Version 1.28.0 is being displayed as a version newer than 1.29.0

**Screenshots**
![image](https://user-images.githubusercontent.com/80255844/130914698-ff55952a-b9d8-4903-98f1-72af1400c41e.png)

**Comment by Frank-Magmodules** [comment]
HI @dehaan-jeroen,

Thank you for opening this issue, it seems this was an issue with version data from our side, we've just fixed that and it should show the right version from now on. Thank you for reporting this. We are closing this issue now but please feel free to reopen the issue if this still occurs.
