### ISSUE TITLE
New order email en factuur worden niet verstuurd bij afgerond bedrag 3 digits

### ISSUE THREAD

**Issue by Jilco** [mollie/magento2#43]
Ik heb sinds versie 1.1.2 een probleem met de new order email, deze wordt in sommige gevallen niet verstuurd bij een nieuwe order betaald via Mollie. De factuur wordt ook niet gemaakt en dus niet verstuurd. Ik krijg wel de normale betaal email van mollie en daaraan kan ik zien dan er een bestelling is, ik moet dan in de backend de factuur met de daarvoor bestemde knop maken en daarna de bestelbevestiging met de knop versturen (dat gaat wel goed, maar dus niet automatisch).

Na lang (heel lang) zoeken ben ik erachter wanneer het misgaat. Als iemand een halve meter (of 1,5 of 2,5, etc) besteld dan moet hij 0,5 x 9,95 berekenen en dat komt uit op 3 digits. En dan gaat het mis zodra er met mollie betaald wordt, als ik met de magento default paypall express betaal is er geen probleem.

Het zal dus ergens in de afronding zitten en de manier waarop dat in de db geplaatst wordt, daar zal Magento (2.2.2 inmiddels) zich in verslikken....

Ik heb het ook kunnen reproduceren in mijn test omgeving

Gegevens:
www.tricotstoffen.nl
Magento 2.2.2
Php 7.1.12
Mariadb 10.1
Mollie 1.1.3

**Comment by Marvin-Magmodules** [comment]
Hi Jilco, zou je contact met ons op kunnen nemen via: https://www.magmodules.eu/contact-us.html Dan kunnen we buiten Github om even wat data uitwisselen om het probleem te lokaliseren.

**Comment by Jilco** [comment]
Done :-)

**Comment by Marvin-Magmodules** [comment]
Fixed in a new release: https://github.com/mollie/magento2/releases/tag/v1.1.4

**Comment by Jilco** [comment]
Ik heb hem geinstalleerd en getest en ein-de-lijk is het probleem opgelost 😊


Thanks!


________________________________
Van: Marvin Besselsen <notifications@github.com>
Verzonden: maandag 18 december 2017 11:41
Aan: mollie/magento2
CC: Jilco; Author
Onderwerp: Re: [mollie/magento2] New order email en factuur worden niet verstuurd bij afgerond bedrag 3 digits (#43)


Fixed in a new release: https://github.com/mollie/magento2/releases/tag/v1.1.4<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmollie%2Fmagento2%2Freleases%2Ftag%2Fv1.1.4&data=02%7C01%7C%7Ca072f832a11347e892c308d54603e866%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636491904953257361&sdata=7tL%2Fv3btz6rH%2B2gWcu2U3kF%2F748Gjb7CZzxDfDs37SY%3D&reserved=0>
