### ISSUE TITLE
Be able to pass the return URL from GraphQL so we remove the need to configure it in the backend.

### ISSUE THREAD

**Issue by paales** [mollie/magento2#431]
# Describe the new feature
Be able to pass the return URL from GraphQL so we remove the need to configure it in the backend.

## Describe the solution to be implemented

```graphql
mutation MolliePlaceOrder($cartId: String!, $returnUrl: String!) {
  placeOrder(input: { cart_id: $cartId, mollie_return_url: $returnUrl }) {
    order {
      order_number
      mollie_payment_token
      mollie_redirect_url
    }
  }
}
```

**Backend changes**
Minimal I think :)

**Frontend changes**
This allowed for way easier local development, with the headless frontends I want to be able to talk to the live/rc/staging environment without having to change any configuration in the backend to do so.

**Comment by Frank-Magmodules** [comment]
Hi @paales 

We are happy to share that we've just released the all-new [2.0.0](https://github.com/mollie/magento2/releases/tag/v2.0.0) version where we've implemented your feature request. Thank you for this request, we are closing this issue now.
