### ISSUE TITLE
Order status wrongly set to processing after outage in store

### ISSUE THREAD

**Issue by Daniel304** [mollie/magento2#439]
We had a small outage last week and had an user who was in process of payment.
The order never got to mollie as it is not in the list but in magento the rorder is stated as completed paid with ideal and the order is set to processing. Fetching the payment status will result in an error as the transaction id does not exist.
In my opinion this order should never get to the status processing?

**Comment by Frank-Magmodules** [comment]
HI @Daniel304 ,

Thank you for opening this issue, it's is strange, this indeed shouldn't be possible as there isn't any payment and no invoice is created. Can you please share more information with store details as logs and version numbers of Magento/Mollie through our [contact form](https://www.magmodules.eu/support-form.html) so we can check out what happened here and help you debugging where needed?

Thank you!
