### ISSUE TITLE
Duplicate creditcards GraphQl checkout

### ISSUE THREAD

**Issue by arko-betersport** [mollie/magento2#453]
**Describe the bug**
When retrieving the available Payment methods using GraphQl, Credit cards are shown twice. One of them has the code `mollie_methods_creditcard` and the other has code `mollie_methods_creditcard_vault`.
They both have the exact same title.
However the `mollie_methods_creditcard_vault` method results in an error, while the `mollie_methods_creditcard` works fine.

**Used versions**
- Magento 2.4.3 (Open source)
- Mollie module v2.1.2

**To Reproduce**
1. Create an order
2. Retrieve available payment methods

**Expected behavior**
A list of payment methods without "duplicate" entries.

**Actual behavior**
Credit card is shown twice in the list of available payment methods.

**Screenshots**
![image](https://user-images.githubusercontent.com/78349099/139217321-00570cab-d8e5-41de-91da-71240750840f.png)

**Additional context**
When changing the title for Credit cards the title changes for both entries.
Disabling "Enable Magento Vault" still shows both entries.

**Comment by Frank-Magmodules** [comment]
HI @arko-betersport ,

Thank you for opening this issue.  We are happy to share that we've just released the new \[2.3.0\](https://github.com/mollie/magento2/releases/tag/v2.3.0) version where we have fixed this issue.

We are closing this issue now but please feel free to reopen the issue if this still occurs.
