### ISSUE TITLE
Uncaught Type Error in creditcard-with-components.js

### ISSUE THREAD

**Issue by Sental** [mollie/magento2#455]
**Describe the bug**
Uncaught TypeError: Cannot read properties of undefined (reading 'visitAdditionalData') creditcard-with-components.js:83
`this.vaultEnabler` is undefined.

**Used versions**
- Magento 2.4.2-p1:
- Open source:
- 2.2:

**To Reproduce**
1. Enable Module & setup mollie test
2. enable credit card payment method and use mollie components
3. proceed to checkout and try to select the credit card method.
4. Nothing happens on the frontend. Javascript error in console output.

**Expected behavior**
credit card method is selected and mollie components appear.

**Actual behavior**
nothing appears for the customer & an error appears in the console.

**Screenshots**
Error:
<domain>/static/version1635504665/frontend/<theme>L/Mollie_Payment/js/view/payment/method-renderer/creditcard-with-components.js
Uncaught TypeError: Cannot read properties of undefined (reading 'visitAdditionalData')
    at UiClass.getData (creditcard-with-components.js:83)
    at UiClass.selectPaymentMethod (default.js:191)
    at HTMLInputElement.<anonymous> (knockout.js:4245)
    at HTMLInputElement.dispatch (jquery.js:5232)
    at HTMLInputElement.elemData.handle (jquery.js:4884)

**Comment by Frank-Magmodules** [comment]
Hi @Sental ,

Thank you for opening this issue.  We are happy to share that we've just released the new [2.3.0](https://github.com/mollie/magento2/releases/tag/v2.3.0) version where we have fixed this issue. 

We are closing this issue now but please feel free to reopen the issue if this still occurs.
