### ISSUE TITLE
Add dependencies to composer.json and module.xml

### ISSUE THREAD

**Issue by oneserv-heuser** [mollie/magento2#459]
# Describe the new feature
I'd like to have ALL dependencies on modules listed in the module.xml and the composer.json.
## Describe the solution to be implemented
All modules of used magento classes are listed in the module.xml and the composer.json.

## Why this should be done
We have a heavily customized magento shop and are using mollie. I just upgraded from 1.29.0 to 2.3.0 and ran the build process. It failed as the interface `\Magento\InstantPurchase\PaymentMethodIntegration\AvailabilityCheckerInterface` wasn't found which gets implemented by the class [AvailabilityCheck](https://github.com/mollie/magento2/blob/master/Service/InstantPurchase/AvailabilityCheck.php).
We've removed the module where the interface comes from so the build process fails as we don't need the module.

If the dependency was declared in the composer.json, composer itself would've already failed on the update of mollie. Magento should've also failed before when upgrading the database, but it didn't as the module is not listed in the module.xml.
In the module.xml some dependencies are already listed, but some are missing, e.g. 'Magento_InstantPurchase'.

**Comment by Frank-Magmodules** [comment]
HI @oneserv-heuser ,

Thank you for opening this issue, happy to share with you that we will add the dependencies to composer.json and module.xml, as you suggest, to our next release!

**Comment by Frank-Magmodules** [comment]
HI @oneserv-heuser ,

Happy to share that we've now included this in our [2.4.0](https://github.com/mollie/magento2/releases/tag/v2.4.0) release.
We are closing this issue now but please feel free to reopen the issue if you have any other comments or questions regarding this request. Have a good day!

**Comment by hostep** [comment]
@oneserv-heuser: the real fix for your issue was fixed in scope of https://github.com/mollie/magento2/issues/470 I believe, in version 2.5.0, just FYI
