### ISSUE TITLE
Record not removed in DeletePaymentReminder because of CUSTOMER_ID NULL => true

### ISSUE THREAD

**Issue by 6Ways** [mollie/magento2#467]
**Describe the bug**
On guest orders the record in de pending payment reminders is not removed because of the line
`$criteria->addFilter(Order::CUSTOMER_ID, [NULL => true]);`
in Mollie\Payment\Service\Order\DeletePaymentReminder

Even if the customer id in the database is really NULL there is no match with this filter applied.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.3.0

**Expected behavior**
The customer / order record should be removed when an order is paid

**Actual behavior**
The customer / order record is not removed when an order is paid

**Additional context**
Commenting the line 
`$criteria->addFilter(Order::CUSTOMER_ID, [NULL => true]);`
fixes the problem. I do not really see why the customer ID specifically has to be null anyway. We can delete the record if the e-mailadress matches.

**Comment by Frank-Magmodules** [comment]
Hi @6Ways ,

Thank you for opening this issue and your input on this, we are happy to share that we've just released the new [2.4.0](https://github.com/mollie/magento2/releases/tag/v2.4.0) version where we implemented a fix based on your suggestsion.

We are closing this issue now but please feel free to reopen the issue if this still occurs.
