### ISSUE TITLE
Please add screenshots

### ISSUE THREAD

**Issue by Eddcapone** [mollie/magento2#471]
I need to know if this extension fits me, how can I know without screenshots in beforehand?

**Comment by Frank-Magmodules** [comment]
HI @Eddcapone ,

Thank you for opening this issue, for screenshots I want to refer you to our [Magento Marketplace plugin page](https://marketplace.magento.com/mollie-magento2.html) as GitHub is not the place for this. Hopefully, this helps you.

We are closing this issue now but please feel free to reopen the issue if you still have questions.

**Comment by Eddcapone** [comment]
Hello @Frank-Magmodules , you can also upload screenshots to github.

Your Marketplace site only shows screenshots from the backend, there is no single screenshot for the frontend.
