### ISSUE TITLE
Payment methods don't show up in Admin Order when Voucher is enabled

### ISSUE THREAD

**Issue by Quazz** [mollie/magento2#475]
**Describe the bug**
Payment methods don't show up when creating an Admin Order when you enable the Voucher payment type in the backend.

Error in system log: `array_filter() expects parameter 1 to be array, null given in vendor/mollie/magento2/Service/Quote/QuoteHasMealVoucherProducts.php on line 33`

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.3
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 2.4.0

**To Reproduce**
1. Go to mollie configuration and enable both Admin Payment link and Voucher payment methods
2. Go to customers and go to edit on a random customer
3. Click on "Create Order"
4. Add a product
5. Scroll down and see that payment methods is empty
6. Check system.log and find the error.

**Expected behavior**
Payment methods show up when creating order from backend and no error shows up in system.log

**Actual behavior**
No payment methods visible on create order from the backend.

**Comment by Frank-Magmodules** [comment]
HI @Quazz,

Thank you for opening this issue, we are happy to share that we've just released the new [2.5.0](https://github.com/mollie/magento2/releases/tag/v2.5.0) version where we covered this issue. Thank you for the detailed issue report. 

We are closing this issue now but please feel free to reopen the issue if this still occurs.
