### ISSUE TITLE
Add description for customer to payment methods

### ISSUE THREAD

**Issue by oneserv-heuser** [mollie/magento2#476]
# Describe the new feature
I'd like to be able to add descriptions to payment methods which are then shown to the customer/exposed via GraphQl to briefly explain payment methods to the customer.
## Describe the solution to be implemented

**Backend changes**
Each payment method has a `description` (must have another name as description is already in use for the transaction description) field which can be edited via adminhtml.

**Frontend changes**
The description is shown to the user/exposed via GraphQl (I think that the type `MolliePaymentMethodMeta` is the perfect place to add the field.).

**Comment by Frank-Magmodules** [comment]
Hello @oneserv-heuser ,

Thank you for opening this feature request. We discussed this with our team and decided to not implement this. We don’t think it adds enough value for other customers. Magento offers enough options to implement this for those who want to implement this themselves.  For example, you can add these additional details by overriding the different templates provided in `view/frontend/web/template/payment/`.

  
We are closing this issue now.
