### ISSUE TITLE
Surcharge combined Klarna together with extra fee plugin throws error

### ISSUE THREAD

**Issue by Ahmet-Djedovic** [mollie/magento2#479]
When using a surcharge combined with Mollie Klarna I receive an error 422, the surcharge is not showing and when trying to proceed the user interface hangs.
Problem we may have is related to the extra fees are not included in the product rules, but are included in the total price. From what we see Mollie Klarna only calculates the product lines, and finds that these do not match the order upon payment, and cancels it.

**Used versions**
- *Mollie Version number(v.1.30.0)*
- *Magento Open source ver. 2.4.3-p1*

**To Reproduce**
Enable Klarna Pay Later
Combined with a Extra Fee
1. Go to checkout and select a fee
2. Click on Klarna as a payment method
3. Proceed to pay

**Expected behavior**
The customer can complete a order with klarna pay later with a extra fee. The amount of the order does matches the total amount from the order lines. Expected order amount to be €92.89

**Actual behavior**
The amount of the order does not match the total amount from the order lines. Expected order amount to be €90.95 but got €92.89

**Screenshots**
![image](https://user-images.githubusercontent.com/62017184/149757228-a378871f-1e3d-4d34-935c-1bfce611be72.png)

**Comment by Frank-Magmodules** [comment]
Hi @Ahmet-Djedovic ,

Thank you for opening this issue, Klarna is using the order API where the order lines are sent to Mollie and it seems that you have additional fees for the Heatpack product (€1,94) that you add to the cart are not added as order line to the order which results in a not matching total order amount error.

Which third-party plugin are you using for these additional gifts/surcharges?

**Comment by Ahmet-Djedovic** [comment]
Hey @Frank-Magmodules ,

Thank you for the fast reply.
Your comment on the reason of the error seems correct to me.
Im currently using Extra Fee for Magento 2 by Amasty. It gives support for GraphQL so we choose this one.
This modules is responsible for the additional surcharges.

**Comment by Frank-Magmodules** [comment]
HI @Ahmet-Djedovic ,

Also together with the extra fee plugin by Amasty, we can't reproduce this so this seems to be another issue. Please feel free to contact us directly through our <a href="https://www.magmodules.eu/support-form.html">contact form</a> so we can investigate this issue further with you or close the ticket once you already found the solution.
