### ISSUE TITLE
Feature: If payment surcharge set, display this in smaller text next to/under the payment method on checkout

### ISSUE THREAD

**Issue by Quazz** [mollie/magento2#480]
# Describe the new feature
When the payment surcharge is set for a payment method then show the payment surcharge in smaller text (perhaps between brackets/different color) next to/under the payment method in question. 

Currently it's not clear which payment methods have a surcharge until they are selected. Implementing this feature would make it more clear to the customers which payment methods have a transaction fee. 
## Describe the solution to be implemented

**Backend changes**
Since some people may not want this enabled, a disable/enable toggle in admin panel might be desirable.

**Frontend changes**
Additional text next to relevant payment methods to indicate that there are transaction fees associated with it. (with the fees mentioned, eg +€3,00 transaction fees, or +3% transaction fees). This way customers can see the transaction fees without having to select the method and checking what changed in the total amount of the order.

**Comment by Frank-Magmodules** [comment]
Hi @Quazz , thank you for opening this issue, and sorry for the late response!  
We've discussed this internally and I think it is indeed logical to show the fees upfront to the customers to manage the right price expectation. But I'm not sure how this is different than just adding it to the payment method name, as, in that way, this will be displayed on all communication as invoice/emails/backend in the right way as well.

**Comment by Quazz** [comment]
@Frank-Magmodules Yes, I understand, that honestly makes sense as a solution to me. I didn't even think of that as an option. Thanks
