### ISSUE TITLE
"Sofort" Payment -> Language / Locale is Nederlands or English only

### ISSUE THREAD

**Issue by jdinse** [mollie/magento2#49]
Our Magento shop is in German only, so the locale and language of Magento is German. But when going to checkout in the fronted, selecting "Sofort" as payment and continuing to the payment, the whole page of sofort.com is in english.

![bildschirmfoto 2018-03-02 um 17 04 59](https://user-images.githubusercontent.com/2094378/36908809-a8158140-1e3c-11e8-8738-7d13a20bc682.png)

On bottom, I can only select "Netherlands" and "English". Looks like the the locale is not committed correctly to sofort.com.

![bildschirmfoto 2018-03-02 um 16 59 39](https://user-images.githubusercontent.com/2094378/36908783-91d30eca-1e3c-11e8-9652-9d3dc76f6c1a.png)

**Comment by Marvin-Magmodules** [comment]
How did you setup "Language Payment Page" in the module (Mollie » General » Language Payment Page)? Can you try and set this to "de_DE" to see if this changes the language on sofort.com?

**Comment by jdinse** [comment]
Yes, that works! Thanks! I didn't recognize that option after upgrading to Version 1.2.0.

Anyways, shouldn't that work with the option "autodetect" as well? What is the effect of this option?

**Comment by Marvin-Magmodules** [comment]
Yes it does. What this "autodetect" option does is removing the locale data in the request so that the Mollie platform will "autodetect" this. From the mollie api documentation: "When this parameter is omitted, the browser language will be used instead if supported by the payment method". Is your browser language set to German?

**Comment by jdinse** [comment]
Yes. In Google Chrome it is set to the highest order.

![bildschirmfoto 2018-03-03 um 19 27 36](https://user-images.githubusercontent.com/2094378/36937796-118acbe4-1f19-11e8-91fd-10331bef9890.png)

**Comment by Marvin-Magmodules** [comment]
Thanks for the extra information. As this issue is not directly related / can be fixed in the Magento extension, Mollie will follow up on your problem by email. We have forwarded your email to techsupport and they will reach out asap.
