### ISSUE TITLE
Payment method not correctly sent in combination with onestepcheckout/iosc

### ISSUE THREAD

**Issue by MichielVrins** [mollie/magento2#492]
**Describe the bug**
When using mollie with onestepcheckout/iosc version 1.2.053 (but also seen this bug on previous versions) the set-payment-information call sends the previously selected payment method in the api call. 
Request url: est/nl/V1/guest-carts/<key>/set-payment-information
Read this as, when you select paypal and then switch to ideal, it will send a request to select paypal.
This normally is not an issue as it gets sent again before you get redirected to mollie and then it will send the correct value. But it is a problem when the price depends on the payment method, when forinstance applying surcharge. 
**Used versions**
- *Magento Version number(2.4.3):
- *Open source
- *Mollie version number 2.5/2.6
- Onestepcheckout/iosc version 1.2.053

**To Reproduce**
1. Have onestepcheckout/iosc installed with mollie and onestepcheckout enabled. 
2. Select a different payment method and observe the set-payment-information api call in the network tab. 

**Expected behavior**
When using mollie in combination with onestepcheckout/iosc I except that the selected payment method gets correctly sent to magento and, when applicable, the surcharge is shown after selecting a payment method. 

**Actual behavior**
The previously selected payment method gets sent to magento and the surcharge does not show untill you press it twice. 

**Screenshots**
After selecting the ban-contact payment method, the set-payment-method clearly sends creditcard as payment method. 
![image](https://user-images.githubusercontent.com/10757347/155534337-c08f3fad-c1cf-4744-88de-c8ac96d5d4b2.png)

**Comment by Frank-Magmodules** [comment]
HI @MichielVrins ,

Thank you for opening this issue, we are happy to share that we've just released the new [2.7.0](https://github.com/mollie/magento2/releases/tag/v2.7.0) version where we have covered this. Thank you for the detailed issue report.

We are closing this issue now but please feel free to reopen the issue if this still occurs.
