### ISSUE TITLE
Payment Review Klarna when Using Reward Points (Mirasvit)

### ISSUE THREAD

**Issue by 6Ways** [mollie/magento2#494]
Hi,

When costumers try to checkout using reward points from Mirasvit the order gets stuck on Pending Review.
These order will not show in Mollie.log.
And you can not cancel these orders.

To implement this the proces of #483 can almost be repeated with a few adjustments:

The class to fetch the used reward points:
\Mirasvit\Rewards\Helper\Purchase $rewardsPurchase

The $rewardsTransaction object can then be fetched with $this->rewardsPurchase->getByOrder($order)

The total spendamount is in  $rewardsTransaction->getSpendAmount()

**Comment by Frank-Magmodules** [comment]
HI @jdereus87 ,

Thank you for opening this issue, we don't have this plugin in our environment. Can you please share your staging/development environment through our [support form](https://www.magmodules.eu/support-form.html) so we can take a look with you?

**Comment by donbloothoofddesign** [comment]
Hi, @Frank-Magmodules,

We have also this problem with the Mageplaza reward module. Please can you check these one also?

**Comment by Frank-Magmodules** [comment]
HI @6Ways  and @donbloothoofddesign ,

We are happy to share that we've just released the new [2.8.0](https://github.com/mollie/magento2/releases/tag/v2.8.0) version where we have made the Mirasvit compatible with the OrderAPI. Thank you again for the detailed issue report.  

We are closing this issue now but please feel free to reopen the issue if this still occurs.
