### ISSUE TITLE
Mark as Paid not working when insufficient stock

### ISSUE THREAD

**Issue by Goeny** [mollie/magento2#498]
**Describe the bug**
When order is placed for the final qty of a product (i.e: 1pc on stock, 1pc ordered) the new qty will become 0 - not in stock.
If customer decides to pay manually, not using the payment link we cannot use the "Mark as Paid" button because new order cannot be created due to "no-stock".

**Used versions**
- *Magento Version number(eg 2.3.5)*: Magento community 2.4.3
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 2.4.0

**To Reproduce**
1. Set product stock to 5
2. Create order with that product qty of 5, mollie payment link, etc.
3. Use "Mark as Paid" button
4. Error: "Product dat u probeert toe te voegen is niet beschikbaar." ("Product you are trying to add is unavailable")

**Expected behavior**
I expect the order to be replaced without error, and marked as paid.

**Actual behavior**
Order is not replaced with a new, paid order.

**Additional context**
I assume how this works is: The original order will be copied with a new payment method. Also using the current stock which means the virtual stock is temporarily lower then the actual stock.
After the order is recreated, the original order will be cancelled and the qty will return to stock making the actual stock to be correct again.
I think this issue can be fixed by adding the qty from the order to the product before recreating the order and remove that stock again after the order is recreated.

**Comment by Frank-Magmodules** [comment]
Hi @Goeny ,

We are happy to share that we've just released the new [2.8.0](https://github.com/mollie/magento2/releases/tag/v2.8.0) version where we have fixed this issue. 
Thank you for opening this issue and for the detailed issue report.  

We are closing this issue now but please feel free to reopen the issue if this still occurs.
