### ISSUE TITLE
Second chance email not working when Ideal disabled

### ISSUE THREAD

**Issue by anvanza** [mollie/magento2#499]
**Describe the bug**
It seems that because of Service/Order/Reorder.php L:93 that the second chance email forces 'mollie_methods_ideal' while the validation later fails because the method has not been setup.
The correct code should be mollie_methods_reorder

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.3-p1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.7

**To Reproduce**
1. Disable Ideal payment method
2. Enable Second Chance email
3. Click on a second chance email

**Expected behavior**
The user should be redirected to a new payment page.

**Actual behavior**
The user receives error "This payment method is not available" (thrown in vendor/magento/module-sales/Model/AdminOrder/Create.php L 2077)

**Screenshots**
<img width="1431" alt="Screenshot 2022-03-15 at 14 20 49" src="https://user-images.githubusercontent.com/2848347/158386678-6d25417d-52aa-4c17-8391-7549f015dc03.png">

**Comment by Frank-Magmodules** [comment]
Hi @anvanza ,

We are happy to share that we've just released the new \[2.8.0\](https://github.com/mollie/magento2/releases/tag/v2.8.0) version where we have fixed this issue. Thank you for opening this issue and the detailed issue report.  

We are closing this issue now but please feel free to reopen the issue if this still occurs.
