### ISSUE TITLE
Bepaalde betaalmethodes redirecten niet naar mollie.com/paymentscreen

### ISSUE THREAD

**Issue by pascaladriaansen** [mollie/magento2#5]
Hey,

Ondertussen wat verder getest. We lopen tegen het volgende aan zodra we een betaling proberen uit te voeren via iDeal of creditcard: in plaats van dat we naar 
```
https://www.mollie.com/paymentscreen/ideal/testmode?transaction_id=<transactionID>&bank_trxid=<bankTrxID>
```
worden geredirect worden we naar
```
https://www.SHOPDOMEIN.nl/paymentscreen/ideal/testmode?transaction_id=<transactionID>&bank_trxid=<bankTrxID>
```
geredirect.

We hebben niet alle betaalmethodes geprobeerd, dus kan niet zeggen of dit ook bij andere betaalmethodes dan iDeal en creditcard optreedt. Wel zien we dat als we de PayPal betaalmethode kiezen, we gewoon netjes naar PayPal geredirect worden.

Issue heb ik al eens eerder gemeld (zie #1 ).

**Comment by Magmodules** [comment]
Hi Pascal, had je daar toen over gemaild maar helaas nooit reactie op ontvangen. Draai je op production of developer modus? Verder geen andere Mollie extensies actief in de store?

**Comment by pascaladriaansen** [comment]
Hmm, heb toendertijd wel gereageerd, maar ging via een collega - dus daar is iets mis gegaan denk ik.
De store draait in production mode. Verder zijn er geen Mollie extensies actief.

**Comment by Magmodules** [comment]
Geen probleem! Ik mail je even over de urls.
