### ISSUE TITLE
Enterprise

### ISSUE THREAD

**Issue by pieterdc2** [mollie/magento2#50]
can i install this on the enterprise edition?

**Comment by Frank-Magmodules** [comment]
Thanks for your message. We've didn't tested this on the latest Enterprise version as we're not holding a license on this version. In case of any troubles or questions, we have the will and time to help you out with this.

**Comment by Frank-Magmodules** [comment]
Hi @pieterdc2 , Sorry for the long wait, but the latest release is finally tested in Magento Commerce (Enterprise) and have added this to our manual QA testing. From v1.6.2 we will have the module available on the Magento Marketplace. The current version can be installed using composer.
