### ISSUE TITLE
Support for Amasty Fee not working with Tax + Klarna 

### ISSUE THREAD

**Issue by Ahmet-Djedovic** [mollie/magento2#504]
**Describe the bug**
In 2.7.0 Support for Amasty Fee has been added. 
![image](https://user-images.githubusercontent.com/62017184/160416593-cc699097-dd68-44e2-a07c-2bc831c695ab.png)
My config of amasty Fee is setup in this way:
![image](https://user-images.githubusercontent.com/62017184/160417103-20cb6025-4858-4071-96ef-57bc5ca982e2.png)
But if i try to checkout with Klarna Pay Later Combined with a Tax class on the Amasty Fee. Klarna doesnt recieve the tax amount of the fee.
![image](https://user-images.githubusercontent.com/62017184/160420806-3750ee6c-509c-4897-9a20-6c9f56fdf367.png)
It shows Expected 17.00 but got 17.42, the **fee** is 2 euro. Then we add **21%** tax to 2 which is 0.42. Klarna doesnt recieve the tax in the total. And throws a error

If i remove the tax-settings from the fee i can happily proceed to succes page. The order total is 17.00 in this case.
 

**Used versions**
- *Magento Version number*: Magento ver. 2.4.3-p1
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: v2.8.0

**To Reproduce**
1. Setup a Amasty order fee of 2 euro
2.
![image](https://user-images.githubusercontent.com/62017184/160422326-e2fed9a5-dfd4-42de-8d21-e5cf681207a0.png)
3. Configure amasty Fee to use any tax above 1%
3. Proceed to checkout, and select a fee
4. Fill in all needed information
5. Click on Klarna Pay Later on payment screen
6. See error

**Expected behavior**
As a user i want to buy a fee combined with klarna pay later and proceed to succes page

**Actual behavior**
Currently you get a error and you cant proceed with klarna, all other mollie payment methods work.

**Additional context**
Paypal ideal and others work fine with amasty fee

**Comment by Ahmet-Djedovic** [comment]
Amasty Extra Fee Version 1.6.5

**Comment by Frank-Magmodules** [comment]
Hi @Ahmet-Djedovic , thank you for opening this issue. We will try to reproduce this based on your description so we can implement a solution for your issue in the upcoming release!
