### ISSUE TITLE
Unable to apply data patch on PHP8.1

### ISSUE THREAD

**Issue by anvanza** [mollie/magento2#516]
**Describe the bug**
Unable to apply data patch Mollie\Payment\Setup\Patch\Data\EncryptApiKeys for module Mollie_Payment. Original exception message: Deprecated Functionality: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/html/vendor/mollie/magento2/Setup/Patch/Data/EncryptApiKeys.php on line 67

**Used versions**
- *Magento Version number(eg 2.3.5)*: Magento 2.4.4
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.10.0

**To Reproduce**
1: Run bin/magento setup:upgrade

**Expected behavior**
It finishes without errors

**Actual behavior**
A clear and concise description of what actually happens.
It finishes with errors

**Screenshots**

**Additional context**

**Comment by Frank-Magmodules** [comment]
Hi @anvanza ,

We are happy to share that we've just released the new [2.11.0](https://github.com/mollie/magento2/releases/tag/v2.11.0) version where we have fixed this issue.  
Thank you for opening this issue and for the detailed issue report.

We are closing this issue now but please feel free to reopen the issue if this still occurs.
