### ISSUE TITLE
Second chance email doesn't work with Magento 2.4.3-p2

### ISSUE THREAD

**Issue by Epo123** [mollie/magento2#519]
**Magento 2.4.3-p2 changes how email variables work**
Variables in view/frontend/email/second_chance.html  such as:
{{layout handle="sales_email_order_items" order=$order area="frontend"}}
No longer work.
More information can be found here:
https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/templates/template-email-migration.html

**Used versions**
- *Magento Version number(2.4.3-p2)*:
- *Open source/Enterprise*:
- *Mollie version number (Latest)*:

**To Reproduce**
1. Get a second chance email

**Expected behavior**
All variables are working

**Actual behavior**
Variables are missing

**Comment by Frank-Magmodules** [comment]
Hi @Epo123 ,

We are happy to share that we've just released the new [2.11.0](https://github.com/mollie/magento2/releases/tag/v2.11.0) version where we have fixed this issue.  
Thank you for opening this issue and for the detailed issue report.

We are closing this issue now but please feel free to reopen the issue if this still occurs.
