### ISSUE TITLE
Feature request: sent payment info via mail for banktransfer.

### ISSUE THREAD

**Issue by quisse** [mollie/magento2#52]
I can't find a possibility to send the payment information which is supplied to the customer after selecting "Banktransfer" via mail. If i don't overlook something this would be a nice feature?

**Comment by Frank-Magmodules** [comment]
Thanks for the message. The banktransfer instruction e-mail is not sent from Magento but by Mollie as this payment should be wired to Mollie and not directly with the Merchant.

**Comment by quisse** [comment]
Ok, i didn't receive that mail whilst testing (in test mode). I'll contact the guys @ Mollie about this.
