### ISSUE TITLE
Install from magento + composer

### ISSUE THREAD

**Issue by sebfie** [mollie/magento2#524]
Hello, when trying to install the module : 

[Exception]                                                                                                        
  Higher matching version 2.11.0 of mollie/magento2 was found in public repository packagist.org                     
                               than 2.10.0 in private https://repo.magento.com. Public package might've been taken   
  over by a malicious entity,                                                                                        
                               please investigate and update package requirement to match the version from the priv  
 ate repository                                                                                                     
                 

Can you please update the version on repo.magento.com

**Comment by Marvin-Magmodules** [comment]
hi @sebfie, thank you for opening this issue! There were some issues with submitting packages to the Marketplace yesterday, so we were unable to submit new versions. Looks like there are resolved and we will push for an update!

**Comment by sebfie** [comment]
Yes please because I can not deploy my website anymore !

**Comment by Marvin-Magmodules** [comment]
Hi @sebfie it's in the queue, but this can take some time, as it will also involve a manual QA from Magento. 

Some background (/w temp. fix) on this issue: https://github.com/mollie/magento2/wiki/Higher-matching-version-was-found-on-packagist.org

**Comment by Marvin-Magmodules** [comment]
Hi @sebfie I see the version has been approved and is available on the Magento Marketplace. We are closing this issue now but please feel free to reopen if you still encounter any issues.

**Comment by sebfie** [comment]
I have a similar issue again :p 

  [Exception]                                                                                                                                    
  Higher matching version 2.12.0 of mollie/magento2 was found in public repository packagist.org                                                 
                               than 2.11.0 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,   
                               please investigate and update package requirement to match the version from the private repository     

Maybe it's a best way to release on packagist after Magento :p

**Comment by hostep** [comment]
@sebfie: or don't "purchase" this module from the magento marketplace, so composer only finds it in packagist. But that will only work with a new project I'm afraid because currently you [can't remove modules](https://github.com/magento/magento2/issues/34390#issuecomment-1137015466) [from the marketplace](https://magentocommeng.slack.com/archives/C7SL5CGDN/p1653471239522309) (yet?) 😞
