### ISSUE TITLE
[FEATURE REQUEST] Payment Method To Use For Second Change Payment using the payment method in de previous order

### ISSUE THREAD

**Issue by erwinschaap** [mollie/magento2#525]
# Describe the new feature
A clear and concise description of the new feature.
## Describe the solution to be implemented
Payment Method To Use For Second Change Payment using the payment method in de previous order. Now we must declare a static value for each store view eg: PayPal. The best solution would be to implement a so the customer can pay with all payment methods there are available OR pay with the payment method the customer chooses in the first initial order.

**Backend changes**
A clear and concise description of the new feature in the backend.
The implementation of the feature

**Frontend changes**
A clear and concise description of the new feature in the frontend.
Change the "Payment Method To Use For Second Change Payments" to add more options: Payment method from initial order and/or Payment method choice by customer 

**Additional context**
-

**Comment by Frank-Magmodules** [comment]
Hi @erwinschaap ,

We are happy to share that we've just released the new [2.14.0](https://github.com/mollie/magento2/releases/tag/v2.14.0) version where we implement this Feature request that makes it possible to use the previous method for second chance orders. Thank you for opening this issue/ feature request and for the detailed issue report.

We are closing this issue now but please feel free to reopen the issue if this still occurs.

**Comment by erwinschaap** [comment]
Thank you Frank. It would be even better if the customer can choose their payment method for the second change payment. Is that possible or not?

**Comment by Frank-Magmodules** [comment]
Hi @erwinschaap , I understand that but for now, that’s not possible. It would require us to create an interface where the user can select a different payment method. The effort for this is too big to invest in this single feature.
