### ISSUE TITLE
Environment emulation nesting is not allowed

### ISSUE THREAD

**Issue by simonmaass** [mollie/magento2#534]
**Describe the bug**
We are seeing the following error in sentry: "Environment emulation nesting is not allowed"

<img width="385" alt="image" src="https://user-images.githubusercontent.com/32599710/174628859-e1fe492e-1a84-4063-93de-6666d384eacd.png">

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.4
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.12.0

**To Reproduce**
Trigger Webhook via Mollie or Magento Backend

**Comment by Frank-Magmodules** [comment]
Hello @simonmaass,

Thanks for opening this issues. We investigated this and it looks like this is a core Magento bug, which is reported over here:  
[https://github.com/magento/magento2/issues/35603](https://github.com/magento/magento2/issues/35603)This isn’t something we can’t fix on our side so we are going to close this issue, but feel free to reopen if you have any further questions.

**Comment by simonmaass** [comment]
Just for the record... this patch works: https://github.com/magento/magento2/issues/35603#issuecomment-1419257643
