### ISSUE TITLE
No .travis.yml file

### ISSUE THREAD

**Issue by willemstuursma** [mollie/magento2#54]
Good morning @Marvin-Magmodules,

I noticed that there is no `.travis.yml` file in this repository. We use this a lot at Mollie to do some basic linting or run tests, and automatically release new versions to pip or rubygems for example.

I'd like to add this file to this repository so we can make sure no syntax errors are checked in.

Can you let me know which PHP versions are supported and then we can start off with that?

**Comment by Marvin-Magmodules** [comment]
HI @willemstuursma we always follow the Magento 2 requirements of the last two versions (for now 2.1 and 2.2). As this changes we will update the composer.json with the php requirements.

**Comment by willemstuursma** [comment]
Thanks, I created  #55.
