### ISSUE TITLE
Error update new version via composer

### ISSUE THREAD

**Issue by ngoducnhuiit** [mollie/magento2#553]
**Describe the bug**
I'm getting a warning when trying to update the extension through composer. Something unusual is happening in your code see the image below.
https://i.imgur.com/dylUHXp.png

**Used versions**
- *Magento Version number 2.4.4*:
- *Open source/Enterprise/B2b*:
- *Composer version 2.2.6 *
- *php 8.1*
- *Mollie version number (Check configuration)*: 2.10.0

**To Reproduce**
1. Go to ssh 
2. open terminal > go to site root Magento> run command  composer update mollie/magento2 or composer require mollie/magento2

**Screenshots**
https://i.imgur.com/dylUHXp.png

**Additional context**
[Exception]
  Higher matching version 2.15.0 of mollie/magento2 was found in public repository packagist.org
 than 2.14.0 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,
 please investigate and update package requirement to match the version from the private repository

**Comment by Frank-Magmodules** [comment]
Hi @ngoducnhuiit, please see mollie/magento2#524 and mollie/magento2#394.
