### ISSUE TITLE
Does Mollie Support Adobe Commerce Cloud versions on a stable note? Magento 2.4.3-p2

### ISSUE THREAD

**Issue by realadityayadav** [mollie/magento2#556]
We tried using the Mollie extension 2.13.0 but we have been experiencing syncing issues of order and payment status back to Magento after an order is placed either in the sandbox or live mode. 

All settings are used as default and there is no restriction upon any of the urls of extension but the webhook communication just doesn't happen and mollie support isn't able to help too much so I am posting it here to see if there is already a solution to this issue, please?

**Comment by Frank-Magmodules** [comment]
Hi @realadityayadav, yes it should support this version. To debug the webhook result, please log in to [https://my.mollie.com, open the transaction, and see the result from the webhook](https://my.mollie.com/) . Once you have that, please let us know the outcome of this so we can help you.

**Comment by realadityayadav** [comment]
@Frank-Magmodules I get a 302 on the webhook status
Webhook failed with status code 302 (Found)
26. August 2022, um 05:17

**Comment by realadityayadav** [comment]
Thanks @Frank-Magmodules you guided me in the right direction, we were using a url translation module which was translating the automatic webhook url from mollie/checkout/webhook to mollie/kasse/webhook inturn causing the magento 2 routing to hold on the 302 headers for webhook. 
Then your custom webhook url feature came handy and I supplied the complete url there and then this started to work correctly. Thanks for the quick help here. Cheers.
