### ISSUE TITLE
Cart is being restored when paymentStatus is equal to PENDING with PayPal

### ISSUE THREAD

**Issue by joggienl** [mollie/magento2#562]
**Describe the bug**
In test mode I noticed that when I do an order and select paypal as payment method the cart in magento gets restored if the payment status is "PENDING". I do not think that should happen.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.3-p1
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 2.11.0

**To Reproduce**

It is a bit hard to describe every possible step so I hope this helps. If not, let me know!

- Use the GraphQL api 
  - Set the PayPal as payment method on the cart object 
  - place an order with `placeOrder`
- Use the `mollie_redirect_url` to go to the mollie payment screen
- Choose "pending" as value for the payment

At this point your site will load the configured return url

- Use the `mollieProcessTransaction` GraphQL mutation to make sure the webhook has been called and the proper payment status is known. You will see `PENDING` as `paymentStatus` (at least, you should see that).

The cart_id that was previously used with `placeOrder` is restored and "active" (depending on how you use this).

**Expected behavior**

When `PENDING` is the state of a payment, the cart should not be restored. Just like the `OPEN` state with iDeal.

**Actual behavior**

The cart_id that you used for `place_order` will be restored and the customer is able to use the same cart to order again. This causes trouble in other systems.

**Screenshots**

**Additional context**

**Comment by Frank-Magmodules** [comment]
HI @joggienl 

We are happy to share that we've just released the new [2.17.0](https://github.com/mollie/magento2/releases/tag/v2.17.0) version where we have fixed this issue now. Thank you for opening this issue and for the detailed description in the comments. We are closing this issue now but please feel free to reopen the issue if you need any help on this.

**Comment by joggienl** [comment]
Thanks @Frank-Magmodules , we'll check the update!

**Comment by joggienl** [comment]
@Frank-Magmodules I've detected something weird after we upgraded to 2.17.0, could be related to this hence I am adding a comment here as well. I've created a new issue #573.
