### ISSUE TITLE
Can't create partial shipment

### ISSUE THREAD

**Issue by Quazz** [mollie/magento2#563]
**Describe the bug**
When trying to create a partial shipment you are returned to "Source selection" page for shipment.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.4
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.16.0

**To Reproduce**
When Mollie Order API is used for payment methods and multiple items are ordered each of which has their own sources related to them, it is impossible to create a partial shipment for them. 

edit: Now that I'm fairly certain I found the cause, I should clarify it only happens if additional Mollie Order Lines are generated in the table, still don't know why or how this happens, but the error won't happen without it.

Example: 
item1 - sources: source1, source2
item2 - sources: source4

Partial shipments must be created in order to close the order, but it brings you back to source selection instead.

So steps:
1. Set payment method to Mollie Order API
2. Assign a source to a product
3. Assign a different source to a different product 
4. Create an order with both products that share no sources
5. Wait 1h+ and verify additional lines are generated without line_id in mollie_order_lines
6. Try to create a shipment for the order

**Expected behavior**
The shipment is created successfully

**Actual behavior**
You are brought back to the source selection. After some debugging by logging exceptions, the exception logged is:
`Mollie API: [2022-09-27T11:22:38+0000] Error executing API call (422: Unprocessable Entity): Line 0 contains invalid data. The 'id' field is missing. Field: lines.0.id. Documentation: https://docs.mollie.com/overview/handling-errors`

**Screenshots**

**Additional context**

**Comment by Quazz** [comment]
It looks the problem is caused because of line_id no longer having NULL as default value

**Comment by Frank-Magmodules** [comment]
Hello @Quazz,

Thank you for opening this issue and for the additional comments. We’ve checked this but it seems to be working fine on a plain Magento 2.4.5 install with only Mollie installed. Could it be that you have some modules installed that invoke the creation of the shipment that collides? 

Especially step 5 is something we don’t recognize: As soon as the Mollie webhook marks the order as paid all order lines should be present. Next to that, a `line_id` with a value of `NULL` is something that shouldn’t happen in a regular installation.

**Comment by Quazz** [comment]
> Hello @Quazz,
> 
> Thank you for opening this issue and for the additional comments. We’ve checked this but it seems to be working fine on a plain Magento 2.4.5 install with only Mollie installed. Could it be that you have some modules installed that invoke the creation of the shipment that collides? 
> 
> Especially step 5 is something we don’t recognize: As soon as the Mollie webhook marks the order as paid all order lines should be present. Next to that, a `line_id` with a value of `NULL` is something that shouldn’t happen in a regular installation.

The correct lines are correctly generated.

I have found the problem in the mean time, 3rd party extension that's calling https://github.com/mollie/magento2/blob/master/Service/Order/Lines/Order.php#L87 

Not Mollie's fault, closing.
