### ISSUE TITLE
Payment method Paymentlink occurs in graphql storeconfig payment_methods field

### ISSUE THREAD

**Issue by oneserv-heuser** [mollie/magento2#565]
**Describe the bug**
When requesting all available payment methods via GraphQl in the store_config query, the payment method `mollie_methods_paymentlink` is returned which should not happen as it's no payment method that should exist outside the admin scope.

**Used versions**
- *Magento Version number*: 2.4.5
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 2.16.0

**To Reproduce**
Enable the payment method `mollie_methods_paymentlink`
Execute the following GraphQl query:
```GRAPHQL
query storeConfig {
    storeConfig {
        payment_methods {
            image
            title
        }
    }
}
```

**Expected behavior**
The payment method `mollie_methods_paymentlink` is not returned.

**Actual behavior**
The payment method `mollie_methods_paymentlink` is returned.

**Additional context**
I know that there is an extra query `molliePaymentMethods` but the problem with that query is that it doesn't care about anything I set in the adminhtml as configuration for the methods, the title is ignored, which payment methods are activated, etc. Is this another bug or intended behaviour?

**Comment by Frank-Magmodules** [comment]
Hello @oneserv-heuser, 

Thanks for opening this issue. Looking at [the documentation](https://devdocs.magento.com/guides/v2.4/graphql/queries/store-config.html) and checking the code for this specific attribute, I can’t seem to find any reference to this. Could it be that this field is provided by some custom code?

**Comment by oneserv-heuser** [comment]
@Frank-Magmodules Uff, you're absolutely right, I completely forgot about that module we have that does exactly this.
Thanks for your quick answer, I'm gonna stand in the corner to be ashamed of myself and fix the issue :laughing:
