### ISSUE TITLE
Mollie 1.3 not yet available on composer.

### ISSUE THREAD

**Issue by marcwales** [mollie/magento2#57]
Hi, 

I'm trying to install the latest mollie plugin for magento but i get "Nothing to install or update" on composer.

Thanks in advance for your help.

Cdt, 
Marc

**Comment by willemstuursma** [comment]
`composer require mollie/magento2:^1.3` will update the version.

**Comment by marcwales** [comment]
Hi Willem,

Thank your for your response. I’ve tried you solution but it gives me the same error :

php composer.phar update mollie/magento2:^1.3
Package "mollie/magento2:^1.3" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
Generating autoload files


Regards,
Marc


Le 9 mai 2018 à 14:09, Willem Stuursma-Ruwen <notifications@github.com<mailto:notifications@github.com>> a écrit :

mollie/magento2:^1.3

**Comment by willemstuursma** [comment]
You should use `require` not `update` @marcwales .

**Comment by marcwales** [comment]
I’ve tried but it gives an another error :

php composer.phar require mollie/magento2:^1.3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: mollie/mollie-api-php[v2.0.0, v1.9.6].
    - Can only install one of: mollie/mollie-api-php[v2.0.0, v1.9.6].
    - Can only install one of: mollie/mollie-api-php[v2.0.0, v1.9.6].
    - mollie/magento2 1.3.0 requires mollie/mollie-api-php ^2.0 -> satisfiable by mollie/mollie-api-php[v2.0.0].
    - Installation request for mollie/magento2 ^1.3 -> satisfiable by mollie/magento2[1.3.0].
    - Installation request for mollie/mollie-api-php (locked at v1.9.6) -> satisfiable by mollie/mollie-api-php[v1.9.6].


Installation failed, reverting ./composer.json to its original content.


Le 9 mai 2018 à 14:16, Willem Stuursma-Ruwen <notifications@github.com<mailto:notifications@github.com>> a écrit :


You should use require not update @marcwales<https://github.com/marcwales> .

**Comment by willemstuursma** [comment]
First, remove the old version of the plugin then: 

`php composer.phar remove mollie/magento2`

Then try the install again.

**Comment by marcwales** [comment]
That did the trick. Here is the output :

php composer.phar require mollie/magento2:^1.3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing guzzlehttp/promises (v1.3.1)
    Downloading: 100%

  - Installing guzzlehttp/psr7 (1.4.2)
    Downloading: 100%

  - Installing guzzlehttp/guzzle (6.3.3)
    Downloading: 100%

  - Installing mollie/mollie-api-php (v2.0.0)
    Downloading: 100%

  - Installing mollie/magento2 (1.3.0)
    Downloading: 100%

mollie/mollie-api-php suggests installing mollie/oauth2-mollie-php (Use OAuth to authenticate with the Mollie API. This is needed for some endpoints. Visit https://docs.mollie.com/ for more information.)
Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead.
Writing lock file
Generating autoload files

Thanks for your help.

Regards,
Marc





Le 9 mai 2018 à 14:28, Willem Stuursma-Ruwen <notifications@github.com<mailto:notifications@github.com>> a écrit :


First, remove the old version of the plugin then:

php composer.phar remove mollie/magento2

Then try the install again.
