### ISSUE TITLE
[FEATURE REQUEST] Error Message not shown on checkout

### ISSUE THREAD

**Issue by HenKun** [mollie/magento2#572]
**Describe the bug**
When cancelling the payment on Mollie and returning to Magento, the generated error or notice messages or not shown on checkout page, but on a consecutive page. This might result in confusing behavior, since the notice message `Payment canceled, please try again.` is shown on success page if another payment method is successfully chosen

**Used versions**
- *Magento Version number(eg 2.4.1)*:
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.17.0

**To Reproduce**
1. Go to checkout
2. Choose a Mollie method and click 'Place order'
3. Click 'Back to payment methods' at the bottom of the Mollie Payment page (do not use back button, this is not the same behavior)

**Expected behavior**
'Payment canceled, please try again.' is shown on checkout page after returned from Mollie Payment 

**Actual behavior**
No message is shown on the checkout page. However, the message is shown on the next page the customer visits. That can be the success page if chosen another method successfully or any other page the customer visits.

**Screenshots**

**Additional context**

**Comment by Frank-Magmodules** [comment]
HI @HenKun ,

We are happy to share that we've just released the new [2.18.0](https://github.com/mollie/magento2/releases/tag/v2.18.0) version where we have covered this feature request!  
Thank you for opening this issue and for the detailed feature request report.

We are closing this issue now but please feel free to reopen the issue if this still occurs.
