### ISSUE TITLE
Set meta title for intermediate loading redirect page

### ISSUE THREAD

**Issue by HenKun** [mollie/magento2#574]
**Describe the bug**
This is a minor flaw, but simple to fix. The meta title on the "use loading screen" page is empty. This might result in confusion if the customer looks at the history (e.g. long press on mobile back button, or right click on desktop back button).
The cutomer might return to the last page that was named "Checkout", instead of to the intermediate page.
I propose setting the meta title to "Checkout".

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.1
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: 2.17.0

**To Reproduce**
1. Go to Checkout
2. Choose mollie method
3. Click "Place order"
4. On the mollie page, have a look at the browser history

**Expected behavior**
The last entry is called "Checkout" or something similar

**Actual behavior**
The last entry is empty, or, if a title suffix is configured, only the title suffix is shown.

**Screenshots**

**Additional context**
In `Controller/Checkout/Redirect.php`, after line 
```
$resultPage->getLayout()->getBlock('mollie_loading')->setMollieRedirect($redirectUrl);
```
add
```
$resultPage->getConfig()->getTitle()->set(__('Checkout'));
```

**Comment by Frank-Magmodules** [comment]
Hi @HenKun ,

We are happy to share that we've just released the new [2.18.0](https://github.com/mollie/magento2/releases/tag/v2.18.0) version where we actually have removed the loading screen as it is obsolete within the later Magento versions.  
  
Thank you for opening this issue and for the detailed issue report.  
We are closing this issue now but please feel free to reopen the issue if you still have questions.
