### ISSUE TITLE
Error with mollie 1.3 on magento 2.1.x ?

### ISSUE THREAD

**Issue by wimnok** [mollie/magento2#58]
After upgrading to version 1.3.0 (with the correct api version), this error occurs

`Uncaught TypeError: Argument 1 passed to Mollie\Api\MollieApiClient::__construct() must be an instance of GuzzleHttp\ClientInterface, instance of Magento\Framework\ObjectManager\ObjectManager given, called in /Users/wim/Sites/profijt/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93 and defined in /Users/wim/Sites/profijt/vendor/mollie/mollie-api-php/src/MollieApiClient.php:129`

Is this a known condition ?

tx,
w

**Comment by Marvin-Magmodules** [comment]
Can you test the following:
* empty var/generation & var/di 
* run: "bin/magento setup:di:compile" 

to see if this fixes the issue?

**Comment by wimnok** [comment]
Yes - tried this repeated.
* Clearing the var/generation and var/di folders is part of the bin/magento setup:upgrade task
* after this task, i double checked whether these directories were empty
* bin/magento setup:di:compile shows no errors
* error occurs on frontend, when going to checkout page

Also, in the backend, the same errors occurs when testing the api and/or enabling/disabling logging

From my composer.json
`"mollie/magento2": "^1.3",
  "mollie/mollie-api-php": "^2.0"`

**Comment by Marvin-Magmodules** [comment]
Can you share us some login details (at: https://www.magmodules.eu/contact-us.html) if possible, so we can investigate this issue?

**Comment by wimnok** [comment]
That will be difficult.. have tried this over and over on a local dev environment.
(Allthough, it might be possible on a public staging server - but this can only be done tomorrow in late afternoon)

**Comment by Marvin-Magmodules** [comment]
Sure, please let me know once you have details of the public staging, so we can check this issue.

**Comment by wimnok** [comment]
Login details have been sent.

**Comment by wimnok** [comment]
thanks - would be great to have this fixed somewhere the coming days ?

**Comment by Marvin-Magmodules** [comment]
Just pushed the edits to branch [1.3.1](https://github.com/mollie/magento2/tree/1.3.1) Can you confirm this on your installation?

**Comment by wimnok** [comment]
It is working fine... thanks for the quick solution.
