### ISSUE TITLE
v2.18.0 error at checkout page

### ISSUE THREAD

**Issue by gino2014** [mollie/magento2#580]
Dear Support Team,

after ugdaring to latest v2.18.0 version we got the following error when you go to the checkout. Cart page is still working. 
We are using Magento 2.4.3-p3 with PHP 7.4.30.

Here ist the error we see at frontend:

<script type="text/x-magento-init">
{
    "*": {
        "Mollie_Payment/js/model/checkout-config": TypeError: Return value of Mollie\Payment\Block\Checkout\CheckoutConfig::getDefaultSelectedMethod() must be of the type string, null returned in /home/xxxx/test.xxxx.com/vendor/mollie/magento2/Block/Checkout/CheckoutConfig.php:43
Stack trace:
#0 /home/xxxx/test.xxxx.com/vendor/mollie/magento2/view/frontend/templates/checkout/checkout-config.phtml(12): Mollie\Payment\Block\Checkout\CheckoutConfig->getDefaultSelectedMethod()
#1 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/xxxx...')
#2 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Mollie\Payment\Block\Checkout\CheckoutConfig\Interceptor), '/home/xxxx...', Array)
#3 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Element/Template.php(303): Magento\Framework\View\Element\Template->fetchView('/home/xxxx...')
#4 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Element/AbstractBlock.php(1114): Magento\Framework\View\Element\Template->_toHtml()
#5 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Element/AbstractBlock.php(1118): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#6 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Element/AbstractBlock.php(678): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#7 /home/xxxx/test.xxxx.com/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock->toHtml()
#8 /home/xxxx/test.xxxx.com/vendor/magento/framework/Interception/Interceptor.php(138): Mollie\Payment\Block\Checkout\CheckoutConfig\Interceptor->___callParent('toHtml', Array)
#9 /home/xxxx/test.xxxx.com/vendor/magento/framework/Interception/Interceptor.php(153): Mollie\Payment\Block\Checkout\CheckoutConfig\Interceptor->Magento\Framework\Interception\{closure}()
#10 /home/xxxx/test.xxxx.com/generated/code/Mollie/Payment/Block/Checkout/CheckoutConfig/Interceptor.php(23): Mollie\Payment\Block\Checkout\CheckoutConfig\Interceptor->___callPlugins('toHtml', Array, Array)
#11 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(578): Mollie\Payment\Block\Checkout\CheckoutConfig\Interceptor->toHtml()
#12 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('before.body.end...')
#13 /home/xxxx/test.xxxx.com/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('before.body.end...')
#14 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('before.body.end...')
#15 /home/xxxx/test.xxxx.com/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('before.body.end...', false)
#16 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('before.body.end...', false)
#17 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('before.body.end', false)
#18 /home/xxxx/test.xxxx.com/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('before.body.end')
#19 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('before.body.end')
#20 /home/xxxx/test.xxxx.com/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('before.body.end', false)
#21 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('before.body.end', false)
#22 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#23 /home/xxxx/test.xxxx.com/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#24 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#25 /home/xxxx/test.xxxx.com/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#26 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#27 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false)
#28 /home/xxxx/test.xxxx.com/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('root')
#29 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#30 /home/xxxx/test.xxxx.com/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('root', true)
#31 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#32 /home/xxxx/test.xxxx.com/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#33 /home/xxxx/test.xxxx.com/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#34 /home/xxxx/test.xxxx.com/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#35 /home/xxxx/test.xxxx.com/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#36 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#37 /home/xxxx/test.xxxx.com/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#38 /home/xxxx/test.xxxx.com/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#39 /home/xxxx/test.xxxx.com/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#40 /home/xxxx/test.xxxx.com/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#41 /home/xxxx/test.xxxx.com/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(23): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#42 /home/xxxx/test.xxxx.com/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#43 /home/xxxx/test.xxxx.com/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#44 /home/xxxx/test.xxxx.com/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#45 {main}

The backend configuration from mollie is working without problem.  

Kind Regards
Gino

**Comment by Aquive** [comment]
I have the very same issue.

**Comment by Frank-Magmodules** [comment]
Hi @Aquive & @gino2014 ,   
  
The issue seems to be appearing in case the default payment method is set to -_none_ (`null`) within the Mollie module configuration. We've just released a [2.18.1](https://github.com/mollie/magento2/releases/tag/v2.18.1) new version with a fix specific to this issue. Sorry for the inconvenience and thank you for opening this issue including the detailed issue report.

We are closing this issue now but please feel free to reopen the issue if this still occurs.
