### ISSUE TITLE
Cannot create shipment when using payment link / admin payment

### ISSUE THREAD

**Issue by mikehenze** [mollie/magento2#582]
**Describe the bug**
Cannot create shipment when using payment link / admin payment.
Throws error: Mollie-API: [2022-11-09T09:47:52+0000] Error executing API call (422: Unprocessable Entity): This order cannot be shipped.. Documentation: https://docs.mollie.com/reference/v2/shipments-api/create-shipment

**Used versions**
- Magento 2.4.5-p1
- Open source
- Mollie 2.18.1

**To Reproduce**
1. Create admin order
2. Use mollie payment method: admin payment
3. Create invoice manually
4. Create shipment manually

**Expected behavior**
Shipment is created and order is set to complete

**Actual behavior**
Error and no shipment is created.
Order stays at "processing"

**Comment by Frank-Magmodules** [comment]
HI @mikehenze ,

Thank you for opening this issue, do you still encounter this issue? As it seems that Mollie had some disruption on the platform around the time that you opened this issue and we are not able to reproduce the issue.

**Comment by mikehenze** [comment]
Yes still occurs

**Comment by mikehenze** [comment]
Can I email you with the login details from our staging site so you can have a look?

**Comment by Frank-Magmodules** [comment]
It could be that on `step 3` of your steps to reproduce, you are not using Mollie to confirm the payment but you manually invoice this, which results in trying to create a Shipment on Mollie's side without a connected payment, which is not allowed. Did you have used the "`Allow to manually mark as paid?`" function to set this to paid?

But please [sent](https://www.magmodules.eu/support-form.html) me your staging details so we can have a look with you indeed!

**Comment by mikehenze** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/10600315/201295523-0f3fb369-0e7e-401c-9ee5-e57b8e054b8a.png)

Yes I have but this is exactly what I use it for.
Manual admin payments, for example when customers pay in our showroom and we create the order in the webshop after.

**Comment by mikehenze** [comment]
Nevermind, it seems Mollie will not allow this payment method to be used for manual payments. So I will use a third party extension to create it. Thanks
