### ISSUE TITLE
Missing button "mark as paid" after invoice creation

### ISSUE THREAD

**Issue by simonmaass** [mollie/magento2#587]
**Describe the bug**
Order cannot manually be marked as paid after an invoice in generated.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: 2.18.1

**To Reproduce**
1. Create Order with mollie payment link in magento admin
2. Generate Invoice and send invoice to client
3. "Mark as paid" is not possible anymore

**Expected behavior**
The button "mark as paid" should still be visible, because sending the invoice to the customer with the payment link is necessary!

**Comment by Frank-Magmodules** [comment]
Hi @simonmaass ,

Thank you for opening this new issue. As we can't reproduce this issue, I want to refer to my comment from yesterday on the other issue with the question if you could contact us directly through our [secured form](https://www.magmodules.eu/support-form.html) so e can take a look with you on this.

Thanks Simon!
