### ISSUE TITLE
REST - Creditcard Vault is shown, even when disabled

### ISSUE THREAD

**Issue by evs-xsarus** [mollie/magento2#597]
**Describe the bug**
When loading the payment methods for the checkout using REST, the creditcard_vault is returned. This shouldn't be happening because it's set to disabled in the configuration.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-p1
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 2.20.0

**To Reproduce**
1. Go to 'rest/nl/V1/guest-carts/xxx/payment-information'

with a correct quote token on xxx.

Make sure setting payment/mollie_general/enable_magento_vault is set to 0.
And payment/mollie_methods_creditcard/active is set to 1.

**Expected behavior**
Only the normal creditcard is returned.

**Actual behavior**
Both creditcard and creditcard_vault are returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/44158071/210231625-918bf0a4-f970-4a8a-b925-b15378beb907.png)

![image](https://user-images.githubusercontent.com/44158071/210231656-89c009fe-51c0-4d1f-a982-49d83d2e07f4.png)

**Additional context**
-

**Comment by Frank-Magmodules** [comment]
Hi @evs-xsarus,

We are happy to share that we’ve just released the new [2.21.0](https://github.com/mollie/magento2/releases/tag/v2.21.0) version where we have fixed this issue.  
Thank you for opening this issue and for the detailed issue report. 

We are closing this issue now but please feel free to reopen the issue if this still occurs.
