### ISSUE TITLE
Invalid version or invalid tag

### ISSUE THREAD

**Issue by martijn-bigbridge** [mollie/magento2#602]
```
composer require mollie/magento2:2.21.0
```

  Problem 1
    - Root composer.json requires mollie/magento2 2.21.0, found mollie/magento2[dev-master, ..., dev-ZsoltMollie-patch-1, v0.9.5, v0.9.6, 0.9.7, 0.9.8, 1.0.0, ..., 1.30.0.x-dev, 2.0.0, ..., 2.20.0] but it does not match the constraint.
    
The latest version inside composer.json is 2.20.1
https://github.com/mollie/magento2/blob/master/composer.json

But the latest tag is 2.21.0
So you need to create a tag 2.20.1 (like the composer.json version) or change the composer.json version into 2.21.0

**Comment by Frank-Magmodules** [comment]
Hi @martijn-bigbridge ah yes sorry about that, we've just fixed this!   
We were debating about 2.21.0 and 2.20.1, so by accident, it got a bit of both. ;-)

Thanks for opening this issue!
