### ISSUE TITLE
Klarna Pay Later option webhook is called twice

### ISSUE THREAD

**Issue by patricksteenks** [mollie/magento2#604]
**Describe the bug**
We see that for Klarna Pay Later payments the webhook is called twice. I'm not sure way. This way we receive two requests for an order update in our shop, which processes the order two times. It seems like a bug in Mollie? The webhook should only be called once upon successfull payment.

**Used versions**
- Magento 2.4.5 Open Source
- Mollie 2.17.0

**To Reproduce**
1. Order with payment option Klarna Pay Later
2. Authorize payment
3. In mollie.log you will see to calls to the webhook of payment succes. There is usually 1 minute between them.

**Expected behavior**
I expect the webhook to be called only once when successfulll.

**Actual behavior**
The webhook is called twice.

**Comment by GioDeGruyter** [comment]
We are having the same issue since today. I'm afraid this is quite urgent since this is the case for all projects that offer "Klarna Pay Later" as payment method with the M2 mollie modules.

**Comment by Frank-Magmodules** [comment]
Hi @patricksteenks  and @GioDeGruyter ,

We are collaborating with Mollie to investigate this matter and will keep you informed of our progress.

**Comment by HenKun** [comment]
Same issue here. The two webhook calls are also visible in the Mollie backend in the order history.

Although it mixes up something in Magento (a second invoice with total of 0 is created and after shipping the order history entry states the captured amount is 0) within Mollie everything seems to work fine regarding the captured and settled amounts.

**Comment by sfritzsche** [comment]
Same issue here. (second invoice with total of 0 for pay later orders)

**Comment by GioDeGruyter** [comment]
Some extra info: the second invoice contains the store credit used for an order.

**Comment by litsher** [comment]
Same issue!

**Comment by patricksteenks** [comment]
We also see multiple calls to webhooks with other payment methods. Do more people experience this?

**Comment by sfritzsche** [comment]
Yes. Found also multiple invoices for Klarna pay now.

**Comment by ZIPITRO** [comment]
Same issue here!

**Comment by ZIPITRO** [comment]
Indeed we notices this with Klarna first, now we also see with iDeal for exmaple

**Comment by LonoMollie** [comment]
Hi all, 

we wanted to inform you that our engineering team is currently working on this.

We will get back to you with an update as soon as possible. 

Have a good day.

Kind regards, 

Lono

Integration Manager - Mollie

**Comment by LonoMollie** [comment]
Hi all, 

just got confirmation that the issue should be resolved. 

Please let us know if you encounter any further problems.

Will close the ticket until further notice.

Have a great evening.

Kind regards,

Lono

Integration Manager - Mollie
