### ISSUE TITLE
Using Apple Pay direct from minicart doesn't set order to processing

### ISSUE THREAD

**Issue by ThomasMW** [mollie/magento2#606]
**Describe the bug**
We are using Apple Pay with the direct integrator. We followed the instructions from Mollie, uploading the verification file to our server to be able to use Apple Pay directly from the minicart.

Paying for the order using this method works and the orders is created and Mollie processes the payment. However, the success page is never called and the order is never set to processing even though the payment status is 'paid'.

Is there a setting we are missing to fully process the order?

**Used versions**
- Magento 2.4.2-p2
- Open Source
- Mollie v2.20.1

**To Reproduce**
1. Put an item in your cart
2. Use Apple Pay directly from the minicart
3. Use preferred authentication for Apple Pay on your Apple device
4. Order is placed 

**Expected behavior**
Order is processed and set to 'processing'.

**Actual behavior**
Order is created and stuck on 'Pending Payment' even though the Mollie payment status is 'paid'.

**Comment by Frank-Magmodules** [comment]
HI @ThomasMW ,

We are happy to share that we’ve just released the new [2.21.1](https://github.com/mollie/magento2/releases/tag/v2.21.1) version where we have fixed this issue.  
Thank you for opening this issue and for the detailed issue report. 

We are closing this issue now but please feel free to reopen the issue if this still occurs.
