### ISSUE TITLE
Klarna After Pay Not Able to create Credit Memo

### ISSUE THREAD

**Issue by Margero** [mollie/magento2#609]
**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-P1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: v2.21.0

**To Reproduce**
1. Place an order using Klarna after pay
2. Go to admin
3. Go to invoice and create a credit memo
4. Enter the qty of the products you want to refund and click on update qty's

**Expected behavior**
The qty should be updated and allow you to create an credit memo

**Actual behavior**
You get an error stating that "We found an invalid quantity to refund item "Product name".

**Screenshots**
![Credit memo Klarna error](https://user-images.githubusercontent.com/31563367/216339068-4da2c27a-98a9-4490-8475-e8244e9ca8fa.PNG)
![Credit memo Klarna](https://user-images.githubusercontent.com/31563367/216339099-a8f71c0f-589d-4e98-923d-5f7fd25d3ce9.PNG)

**Additional context**
There are enough of the products left to create a credit memo. But the system does not allow it to be created. When you open the credit memo normally the qty are already filled in. But when you open the credit memo of Klarna the qty are all showing 0 (zero).

**Comment by Frank-Magmodules** [comment]
Hi @Margero , thank you for opening this issue, we will investigate this and come back to you shortly.

**Comment by Frank-Magmodules** [comment]
Hi there @Margero,

We've exchanged some emails about this issue, but we haven't received a response yet regarding our latest messages about the [new release](https://github.com/mollie/magento2/releases/tag/v2.22.0), which we believe will prevent this issue from occurring. Based on the issue title and the shared screen above, we assume that the latest release resolves your issue. So, for now, we're closing this issue. If you still encounter the same problem, feel free to respond to our emails or reopen this issue.
