### ISSUE TITLE
Order status should change to closed or cancelled when order is fully refunded - Klarna

### ISSUE THREAD

**Issue by Margero** [mollie/magento2#610]
When you refund the full order using Klarna the status should change to close.

![Credit memo klarna Complete](https://user-images.githubusercontent.com/31563367/216343800-1d39d869-b933-4514-828d-48e9ccb10512.PNG)

**Comment by Frank-Magmodules** [comment]
Hi there @Margero,

We've exchanged some emails about this issue, but we haven't received a response yet regarding our latest messages about the [new release](https://github.com/mollie/magento2/releases/tag/v2.22.0), which we believe will prevent this issue from occurring. Based on the issue title and the shared screen above, we assume that the latest release resolves your issue. So, for now, we're closing this issue. If you still encounter the same problem, feel free to respond to our emails or reopen this issue.
