### ISSUE TITLE
Error executing API call (422: Unprocessable Entity): The payment was declined due to suspected fraud

### ISSUE THREAD

**Issue by jorgb90** [mollie/magento2#622]
[2023-03-13T20:39:26.171231+00:00] main.CRITICAL: Exception message: [2023-03-13T20:39:26+0000] Error executing API call (422: Unprocessable Entity): The payment was declined due to suspected fraud.. Documentation: https://docs.mollie.com/overview/handling-errors

Is this call perhaps something thats new within Mollie? They recently upgraded their fraud module.

**Comment by fjbender** [comment]
We did indeed update our fraud prevention module a bit. However, this is nothing totally new, as we had fraud prevention before of course. 

Is this raising any specific issue in the Magento plugin for you? Our tests didn't show anything unusual. If your query is about fraud prevention in general and why a specific transaction has been flagged, our support team is better equipped to help you out.

**Comment by Frank-Magmodules** [comment]
Assuming Florian's answer is sufficient, I will close this issue for now.
