### ISSUE TITLE
Adding index to db table mollie_payment_transaction_to_order - improving performance

### ISSUE THREAD

**Issue by dpotkoc** [mollie/magento2#624]
In version 2.22.0 you have logic for load by transaction_id from db table: **mollie_payment_transaction_to_order**.

https://github.com/mollie/magento2/blob/7553c8a9bd7ec4a4302449c026aa9145f4731fc3/etc/db_schema.xml#L115

It will be good if you can add index for column: **transaction_id**.

**Comment by Frank-Magmodules** [comment]
Hi There @dpotkoc , I've talked with the development team on this and indeed that could be a good idea!  
We have added it to our feature request roadmap, I will update you once I have a sight on the ETA.

**Comment by Frank-Magmodules** [comment]
Hello @HenKun,

We're pleased to inform you that the [latest version](https://github.com/mollie/magento2/releases/tag/v2.24.0) of the Mollie plugin now includes the feature you requested. We hope this solution meets your requirements. For now, we will mark this issue as resolved. However, if you require further assistance, please feel free to reopen the issue.
