### ISSUE TITLE
Partial Refunds not possible

### ISSUE THREAD

**Issue by azngeek** [mollie/magento2#626]
**Describe the bug**

When doing a partial refund when a refund with the same item has been processed before, Mollie will throw a " A duplicate refund has been detected." error. 

**Used versions**
- Magento Version 2.4.2 Enterprise
- Mollie v2.11.0 -> But can also be reproduced with the latest version on my local development environment

**To Reproduce**

1. Create an order with one item with multiple quantities
2. Do the refund using the API and this payload
3. Only substract one quantity
4. The refund will work
5. Do it again with the same payload. 
6. You will now get an duplicated refund error.

```
{
	"items": [
		{
			"order_item_id": <order_item_id>,
			"qty": 1
		}
	],
	"notify": true,
	"isOnline": true,
	"arguments": {
		"shipping_amount": 0,
		"adjustment_positive": 0,
		"adjustment_negative": 0
	}
}

```

**Expected behavior**

It is expected that you can do as many refunds as possible until there are no more items left. An item which has been refunded partially should not trigger an "A duplicate refund has been detected." error

**Actual behavior**

Fo a given item, for example if i do have  ITEM B with a sold quantity of two, if i do multiple refunds with each having a quantity of one, the last refund will fail.

**Screenshots**

This is an example of one item where only one was refunded. 

![image](https://user-images.githubusercontent.com/213429/229846462-2efcfd0c-e792-4cea-a262-8ebe34ac317c.png)

This is the error i get when i try to refund the same item again. That should be possible as only one was refunded yet.

![image](https://user-images.githubusercontent.com/213429/229846560-dc5f2499-c213-44a7-8e76-e158f6904a3d.png)

This is the error in the server log:

![image](https://user-images.githubusercontent.com/213429/229846780-a6feb9d8-3a8b-43d0-8c2f-0533eb5e8d56.png)

**Comment by fjbender** [comment]
Hi @azngeek,

Thank you for your report! This is actually [platform behavior](https://docs.mollie.com/payments/refunds#possible-errors) but can be controlled by our support team. 

Please reach out to them (or me) to get this setting right for your affected merchant(s).
