### ISSUE TITLE
Add BCC to second chance e-mail

### ISSUE THREAD

**Issue by tropilex** [mollie/magento2#627]
**# Describe the new feature**

Add BCC to second chance e-mail. 

This way you can 100% check what is mailed and also when it is mailed. 

For example, whether mistakes have been made in the template, translations and/or other settings.

Magento's native preview feature is not complete enough. The data such as customer name, products and prices are not loaded. So you can't check this for errors.

**## Describe the solution to be implemented**

Same solution as "Config --> Sales --> Sales Emails".

**Comment by tropilex** [comment]
Thanks for adding this to the lastes version. Awesome!

**Comment by Frank-Magmodules** [comment]
Dear @tropilex,

You are welcome, indeed happy to announce that your feature request has been incorporated into our latest release, version [2.25.0](https://github.com/mollie/magento2/releases/tag/v2.25.0). You can now find this option under the “Second Chance Email” tab within the plugin configuration.

We will mark this issue as resolved for now, but if you have any further questions or concerns, please don’t hesitate to reopen the issue or contact us for additional assistance.
