### ISSUE TITLE
[Feature Request] Transfer used payment method to Magento when payment link is used

### ISSUE THREAD

**Issue by HenKun** [mollie/magento2#631]
# Describe the new feature
If a customer pays via payment link, the info about what exact payment method the customer has chosen, is transferred to Magento in a way.

## Describe the solution to be implemented
The used payment method could be stored in table `sales_order_payment` in column `additional_information`

**Additional context**

For most of the payment methods this info is not really required. 
However, if PayPal was chosen, this has influcence on the accounting / bookkeeping.
If customer choses PayPal, our actual PayPal account is credited with the total amount. Unlike the other payment methods, the amount is not disbursed by Mollie, but by PayPal itself. 
For accounting reasons, it would be necessary for us to know where we should expect the amount is coming from, so orders can be assigned to disbursements.

**Example**

Customer choses PayPal --> We know money is coming to PayPal account
Customer choses PayPal via Mollie --> We know money is coming to PayPal account
Customer choses Sofort via Mollie --> We know money is disbursed by Mollie
Customer choses PayPal via Mollie Payment Link --> We do not know if money is coming to PayPal account or disbursed via Mollie

**Comment by Frank-Magmodules** [comment]
Hi @HenKun , thank you for submitting this request. I will review the feasibility of implementing this feature and will provide you with an update shortly.

**Comment by Frank-Magmodules** [comment]
Hello @HenKun! I'm happy to inform you that we have successfully implemented your requested feature in the latest release, [2.26.0](https://github.com/mollie/magento2/releases/tag/v2.26.0), of the plugin. As a result, I will be closing this issue for now. However, please feel free to reopen or comment on the issue if you require any further assistance or have additional feedback. Thank you for your contribution!
