### ISSUE TITLE
[ISSUE] Several Orders keep recieving Webhook failed with status code 302 (Found)

### ISSUE THREAD

**Issue by litsher** [mollie/magento2#636]
**Describe the bug**
We have been getting several orders which will not be seen as "Payed" in magento.
The orders are payed and verified in Mollie, but it doesn't show up as payed in Magento.
The logs in Mollie show the following:

Webhook failed with status code 302 (Found)
4 mei 2023 om 05:16

Webhook failed with status code 302 (Found)
4 mei 2023 om 03:16

Webhook failed with status code 302 (Found)
4 mei 2023 om 02:16

Webhook failed with status code 302 (Found)
4 mei 2023 om 01:47

Webhook failed with status code 302 (Found)
4 mei 2023 om 01:31

Webhook failed with status code 302 (Found)
4 mei 2023 om 01:23

Webhook failed with status code 302 (Found)
4 mei 2023 om 01:19

Webhook failed with status code 302 (Found)
4 mei 2023 om 01:17

Webhook failed with status code 302 (Found)
4 mei 2023 om 01:16

Payment of type iDEAL paid
4 mei 2023 om 01:16

Webhook failed with status code 302 (Found)
4 mei 2023 om 01:16

Payment of type iDEAL created
4 mei 2023 om 01:15

Payment created
4 mei 2023 om 01:15

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.3.7
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*:  2.24.1

**To Reproduce**
1. Get an order
3. Check the status in Mollie
4. Go back to the Order, it's cancelled after a while.

**Expected behavior**
A fully payed order

**Actual behavior**
The order gets cancelled

**Comment by litsher** [comment]
Hi Frank,
The contact form has been filled in, love to hear back about it!

**Comment by sedero** [comment]
> We've reported a similar issue to Mollie which they're still investigating (reported on 15-04-2023).
> 
> This describes the problem we reported:
> 
>     * Order getting placed with payment method iDeal.
> 
>     * Payment X getting started.
> 
>     * Payment Y getting started.
> 
>     * Payment Y finishes and completes the order.
> 
>     * Payment X expires and changes the order to cancelled.
> 
> 
> Screenshot mollie.log 	Screenshot backend
> ![hw-order-issue-ideal-2](https://user-images.githubusercontent.com/6707410/236797310-ffe4a183-423c-4487-b742-e4b17734245a.png) 	![hw-order-issue-ideal-1](https://user-images.githubusercontent.com/6707410/236797315-3e8a8394-1805-4167-8ea0-94c57295757d.png)

We have the same issue with random iDeal payments as described. The order of the Payments can also be the otherway arround

**Comment by joachimVT** [comment]
We are facing similar issues. Customer pays, webhook is successfully called, yet the status from the order is stated as 'Canceled' in Magento. No error logs in Mollie.log
Screenshots:
[screenshot-1](https://ibb.co/pjVX4BV)
[screenshot-1](https://ibb.co/T039kzB)
[screenshot-3](https://ibb.co/TKBV6y9)

**Used versions:**
Magento 2.4.4
Open source
Mollie version number 2.20.1

**Comment by Frank-Magmodules** [comment]
Hi @sedero and @gjportegies, we’re still unable to reproduce the issue in the latest version. Could you please contact us directly and provide a staging/development environment where the issue is reproduced? We’ll debug and work on this together with you.

**Comment by sedero** [comment]
@Frank-Magmodules With the latest patch no issues so far!
