### ISSUE TITLE
Quote not restored when Back Button is used

### ISSUE THREAD

**Issue by HenKun** [mollie/magento2#637]
**Describe the bug**
Since fixing #592 the quote is not restored anymore, if the customer uses the hardware/browser back button on a Mollie related page to return to Magento. This is because the newly created field `mollie_success` in `RestoreQuoteOfUnsuccessfulPayment::execute` on line 53 is `null`. This field is only set to `false`, if the payment really failed, e.g. after processing or via webhook. I think the use case of hitting the back button occures more often than a customer ordering twice within 5 minutes, so the priority for those both conflicting desires is on the "back button" issue, imho.
Alternatively, initializing `mollie_success` with `false` could be an option, however, there might be other side effects by doing this which would bypass the fix of #592 

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.1
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: 2.24.1

**To Reproduce**
1. Go to checkout
2. Choose Mollie payment method
3. Place Order
4. On Mollie payment page hit hardware/browser back button (not the "return to payment methods" link)
5. Cart is empty

**Expected behavior**
Quote is restored and customer is on Checkout Payment Page

**Actual behavior**
Quote is not restored and customer is redirected to empty cart

**Screenshots**

**Additional context**

**Comment by Frank-Magmodules** [comment]
Hello @HenKun, we appreciate you creating this clearly outlined problem. We will make an effort to reproduce the issue and address it in the upcoming release. Thank you for your patience!

**Comment by HenKun** [comment]
Fast as always. You guys make a great job with this module!

**Comment by Frank-Magmodules** [comment]
Thanks @HenKun , we indeed covered this issue in the latest release, [2.26.0](https://github.com/mollie/magento2/releases/tag/v2.26.0), of the plugin. I will be closing this issue for now. Cheers!
