### ISSUE TITLE
Update requirement documentation

### ISSUE THREAD

**Issue by dverkade** [mollie/magento2#641]
The documentation describes that the Mollie API needs to be installed in the root composer.json. However this package is already required by the payment module and does not need to be required separately. Please check documentation here: 
https://github.com/mollie/magento2/wiki/Installation-using-Composer#requirements

**Comment by Frank-Magmodules** [comment]
Hello @dverkade, we appreciate you taking the time to raise this issue and provide clear details on how things should be. We want to inform you that we have made the necessary updates to the relevant wiki page and believe the issue has been resolved. Thank you for bringing this to our attention. We will now close this issue, but please don't hesitate to comment or re-open the issue if you have any further feedback.
