### ISSUE TITLE
[FEATURE] Don't send Magento invoice for Klarna orders

### ISSUE THREAD

**Issue by Jeroen999** [mollie/magento2#646]
Magento version: 2.4.4 open source
Mollie version: v2.14.0

I have enabled the Mollie configuration option to send the Magento invoice email. This email must not be sent for Klarna orders, because these customers receive an invoice from Klarna.

**Comment by Frank-Magmodules** [comment]
Hello there, @Jeroen999! I appreciate you bringing up this issue and your patience. I will delve into it and be back shortly with our idea or vision in response to your request.

**Comment by Frank-Magmodules** [comment]
Good news @Jeroen999 , I've talked with the team and we are going to put this on the roadmap.  
I will update this ticket once a release date is known.

**Comment by Frank-Magmodules** [comment]
Hey there, @Jeroen999  Good news! We’ve recently launched a [new version](https://github.com/mollie/magento2/releases/tag/v2.28.0) that includes the feature you’ve been waiting for. Now you can easily disable the Invoice email for Klarna.  Just head over to the Advanced section and look for the “Send Invoice Email For Klarna Orders” option. It’s all there for you! 

If you have any more questions, don’t hesitate to reopen the request. Enjoy!

**Comment by Jeroen999** [comment]
I have tried this feature, but I had to enable the Magento invoice email again for Klarna orders because Klarna doesn't include the company name in the billing address.

**Comment by patriciavieveen** [comment]
Ls,

Helaas ben ik op dit moment ziek en daardoor niet in de gelegenheid om mijn mail te lezen.

Mijn collega's Matthijs en Marcel zullen mijn werkzaamheden oppakken totdat ik weer hersteld ben. Hieronder staan hun contactgegevens.

Matthijs Burki
***@***.***
010 - 753 60 90

Marcel van Wijk
***@***.***
010 - 753 60 93


Met vriendelijke groet,

Patricia Vieveen
Cream
