### ISSUE TITLE
[ISSUE] Payment fee is calculated wrong in different currency

### ISSUE THREAD

**Issue by tropilex** [mollie/magento2#648]
Hello,

The payment fee is calculated wrong when store view has a different currency than the base. 
I cannot find the logic but it's way more then the 2% that should be calculated.

Mollie version: 2.24.1
Magento version: 2.4.4-P3

![Screenshot 2023-06-06 at 10 53 39](https://github.com/mollie/magento2/assets/53861858/46a2affe-1c17-405a-83cb-244e61b54f84)
![Screenshot 2023-06-06 at 10 50 22](https://github.com/mollie/magento2/assets/53861858/7a2cc8a6-fab9-4926-a7bf-8243320d2836)
![Screenshot 2023-06-06 at 10 47 40](https://github.com/mollie/magento2/assets/53861858/fe231ea3-79e3-433f-b7ca-fdcdcc896b58)

**Comment by Frank-Magmodules** [comment]
Hello @tropilex, thank you for bringing this up.   
I will attempt to reproduce the issue on our end and provide you with an update shortly.

**Comment by Frank-Magmodules** [comment]
Hello, @Tropilex! I’m excited to inform you that we’ve addressed the issue you reported in the [latest release](https://github.com/mollie/magento2/releases/tag/v2.28.0) of the Mollie plugin. Thank you for your patience throughout this process.  I’ll be closing this matter for now, but please feel free to reopen it if you require any further assistance or have additional requests.
