### ISSUE TITLE
[ISSUE] Error The issuer is invalid. Field: issuer

### ISSUE THREAD

**Issue by ithuis** [mollie/magento2#651]
1. When someone first tries to pay with a vvvcard, 
2. then cancelles  ( goes back to payment selection ) 
3. then tries to pay with ideal 
4. the mollie api throws the error "Error executing API call (422: Unprocessable Entity): The issuer is invalid. Field: issuer."

This is probably because there still is a "issuer":"vvvgiftcard" is the json from the request

**versions**
Magento Version number(eg 2.4.5-p2
Open source
Mollie version number (v2.26.0)

**Comment by Frank-Magmodules** [comment]
Hello, @ithuis ,  I wanted to inform you that we’ve recently released the [latest version](https://github.com/mollie/magento2/releases/tag/v2.28.0) that addresses the problem you mentioned regarding the issuer being cleared after a cancellation. Rest assured, this issue has been resolved. 

I’ll go ahead and close this matter for now, but please don’t hesitate to reopen it if you require any further assistance.
