### ISSUE TITLE
Default bank selected

### ISSUE THREAD

**Issue by GetMagented** [mollie/magento2#66]
When you select iDeal as a payment method, the customer has to select their bank with the drop down selector.

In the Magento 1 extension there was no default bank selected. The default option is 'Please select'. 
If the customer did not select a bank, the customer can still checkout and will see the Mollie Checkout payment screen where he or she can select a bank.

In the Magento 2 extension, there is no 'please select' option, the default bank is ABN-Amro. In my opinion the flow in Magento 1 is better, because if a customer forgets to select a bank they will end up at the ABN-Amro payment screen. Chances are their bank is not ABN-Amro, and in that case they have to cancel the order, and go back to Magento again. 

Would it be possible to change the flow?

**Comment by Frank-Magmodules** [comment]
Hi @GetMagented ,

Thanks for your input on this, seems you are right here, good idea to add a "please select" value as first option in the dropdown. We will implement this in the next release.

Frank

**Comment by Frank-Magmodules** [comment]
HI @GetMagented ,

We've just implemented this in the new release; https://github.com/mollie/magento2/releases/tag/v1.3.6

Have a good day!

Frank
