### ISSUE TITLE
Cart empty after cancel Klarna Payment

### ISSUE THREAD

**Issue by aurel5542** [mollie/magento2#675]
Hello,
when I use Klarna Pay Later (or "Rechnungskauf") and get redirected to the Klarna website but then cancel because I want to use another payment method it returns to the home page and the cart is empty. 

When I then put another item to the cart it shows only this item in minicart and cart, when I then go to checkout again this item is gone and the originally products are back in cart again

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.3.6-p1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.28.0

**To Reproduce**
Steps to reproduce: Put items in checkout, checkout useing Klarna Pay Later (Maybe other Klarna also affected), on Klarna Page click on return to payment methods

**Expected behavior**
Expected: Items still in cart and you can choose another payment methods

**Actual behavior**
Actual: Cart empty

Thank you

**Screenshots**

**Additional context**

**Comment by aurel5542** [comment]
One more important thing: 
When I then put another item to the cart it shows only this item in minicart and cart, when I then go to checkout again this item is gone and the originally products are back in cart again

**Comment by Frank-Magmodules** [comment]
Hi There [@aurel5542](https://github.com/aurel5542) , it seems I can’t reproduce this issue on the latest version of the plugin with Klarna in Live and/or Testmode. Is this really only happening with Klarna Pay Later? Are you using a non-default checkout, theme, or frontend? As I can't break it on a vanilla-magento instance.

**Comment by aurel5542** [comment]
Hello, after apply the patch https://gist.github.com/Frank-Magmodules/579b252a75ceb4b1aa0a1c4239254f16 the issue is gone, thank you
