### ISSUE TITLE
Wrong order status on Klarna Pay Later

### ISSUE THREAD

**Issue by danielMikicevic** [mollie/magento2#678]
**Describe the bug**
The customer pays with "Klarna Pay Later", but magento set the status to "pending" until I manually go to the order and click send. If I don't do that, the order will be canceled by magento. Magento received the payment.

**Used versions**
- *Magento Version number*: 2.4.6
-  Open source
- *Mollie version number*: v2.23.0

**Expected behavior**
If the customer has paid, the status should be set to: processing

**Comment by Frank-Magmodules** [comment]
Hello @danielMikicevic, thank you for opening this issue. Could you please proceed with updating the Mollie plugin to its most recent version? This is in response to a recent modification in the `transaction_IDs` for the orderAPI (Klarna), which might be the potential cause of this issue.

**Comment by danielMikicevic** [comment]
Thanks for the quick reply @Frank-Magmodules. The status is now on processing after payment.
Current Mollie Version: v2.29.1

**Comment by Frank-Magmodules** [comment]
Perfect, thanks @danielMikicevic , glad it's solved.

**Comment by ted101media** [comment]
We noticed some Klarna orders are still being cancelled by the Magento cron job to cancel expired orders. But when we check the comment log it says they've been put to processing but is this actually the case?
