### ISSUE TITLE
Apple Pay errors:  Error executing API call (409: Conflict): Your are using an idempotency key that you used before 

### ISSUE THREAD

**Issue by jamieolney** [mollie/magento2#679]
**Describe the bug**

**Used versions**
- *Magento Version number(eg 2.3.5)*:  2.4.3-p1 
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.30.0

**To Reproduce**
Using Payment API and Apple Pay enabled
1. Add item to basket
2. Use Apple Pay button on basket page
3. choose options and press pay

**Expected behavior**
Payement should go through and order confirmation page should show

**Actual behavior**
A clear and concise description of what actually happens.
Error message appears:
[2023-08-09T08:04:48+0000] Error executing API call (409: Conflict): Your are using an idempotency key that you used before. The previous request with the same key is still being executed. Please try again in a few seconds.. Documentation: https://docs.mollie.com/overview/handling-errors
However order is in Magento backend, payment is taken and order confirmation email is sent. 
If looking in Mollie, there is also a message in the history to suggest an error with a webhook. 
Webhook failed with status code 503 (Service Unavailable)

**Screenshots**
Checkout issue for customer
![image](https://github.com/mollie/magento2/assets/7457106/fb0e62f6-66af-40e4-94a4-1995906c00c4)
Webhook 503 in mollie
![image](https://github.com/mollie/magento2/assets/7457106/1a278598-21c4-49c2-afdb-a9cba15d6eec)
order history in Magento
![image](https://github.com/mollie/magento2/assets/7457106/d6e01762-dbf2-4864-b320-abfb4eb85fc6)

**Additional context**

**Comment by Frank-Magmodules** [comment]
Hello @jamieolney, we appreciate you bringing up this matter. Currently, we are actively looking into your concern and will provide you with an update as soon as we gather more information. Thank you for your patience!

**Comment by Frank-Magmodules** [comment]
HI There @jamieolney , Thank you for your patience. I’m happy to share the release of our [latest version](https://github.com/mollie/magento2/releases/tag/v2.30.1), which includes enhancements to prevent any potential order locking and/or timing issues when using Apple Pay. For now, we will consider this matter resolved, but please don’t hesitate to reopen it if you encounter any further problems.
