### ISSUE TITLE
Use Mollie Components field ignored

### ISSUE THREAD

**Issue by lukawefocus** [mollie/magento2#681]
Just upgraded to the latest version 2.30.0 from 1.29.* and I see credit card details can be entered in Magento Checkout. This was set to enter credit card details once redirected to Mollie after pressing the Pay Now button. 
I assume the field responsible for this is "**Use Mollie Components**" under **Configuration > Mollie > Payment Methods > Credit Card**
as it says: _With Components the customer can enter their credit card details within your webshop._

I've checked the default value of the field and it's still set to "No". Checked the value under each scope and it's set to use the Default value which is still "No". Tried to override the field in the storefront scope (last level), it doesn't change in the checkout.

Is this the right field responsible for the credit card details form on checkout and is this a bug?

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.3.5-p1
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.30.0

**To Reproduce**
1. Go to Configuration > Mollie > Payment Methods > Credit Card
2. Enable option "Credit Card" and set the value of the field "Use Mollie Components" to "No"
3. Save the settings and make sure the value of the field is set to "No" in all scopes
4. Go To Store Front
5. Add a product in the cart
6. Go To Checkout and Select the payment option "Credit Card"
7. It shows the form to enter credit card details

**Expected behavior**
Just like before the update to this version I expect the Credit Card option in the checkout to only be a select field and to have the credit card details entered after redirect to Mollie in Mollie's environment

**Actual behavior**
Credit Card details are asked in Magento Checkout

**Screenshots**
[Magento Checkout](https://ibb.co/cbXNHwL)

**Additional context**

**Comment by Frank-Magmodules** [comment]
HI @lukawefocus , thank you for opening this issue, I actually think this is something going wrong in your configuration somehow, can you maybe contact us [directly](https://www.magmodules.eu/support-form.html) so we can take a look with you here?

**Comment by Frank-Magmodules** [comment]
Hello @lukawefocus, Please inform us if you are still experiencing this issue or if you require our assistance as i have not yet seen a support ticket submitted to address your concerns.

**Comment by Frank-Magmodules** [comment]
Hello @lukawefocus, do you have any updates on this? I haven't received any direct communication from you.

**Comment by Frank-Magmodules** [comment]
Hi there @lukawefocus , Due to the lack of a response, I assume that this issue is no longer relevant. If it is still relevant, please feel free to contact us anytime.
