### ISSUE TITLE
Error executing API call (403: Forbidden)

### ISSUE THREAD

**Issue by HenKun** [mollie/magento2#689]
**Describe the bug**

Since using Mollie 2.30.1 (Magento 2.4.6-p2) the following error is logged several times a day in mollie.log

```
Mollie.ERROR: terminals: [2023-09-08T08:01:18+0000] Error executing API call (403: Forbidden): You are not allowed to use the Terminals API.. Documentation: https://docs.mollie.com/overview/handling-errors [] []
```

I can't tell where this error occurs or what impact this error has.

Test of Live API key in config succeeds and we get orders with Mollie payment methods.

**Used versions**
- *Magento Version number(eg 2.3.5)*: Magento 2.4.6-p2
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: 2.30.1 

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Additional context**

**Comment by Frank-Magmodules** [comment]
Hello @HenKun, we're aware of this issue, and for the time being, you can deactivate the POS as a payment method in the backend. Rest assured, the error won't cause any harm, but we're committed to resolving it in an upcoming release.
