### ISSUE TITLE
[ISSUE] No payment link

### ISSUE THREAD

**Issue by tropilex** [mollie/magento2#693]
**Describe the bug**
If you choose in the back-end for the Admin Payment Link method there is no payment link added to the e-mail or visible in the back-end.

This is after updating Magento and Mollie. It's was first working fine.

**Used versions**
- Magento Version: 2.4.6-p2
- Open source
- Mollie version number: 2.30.1

**To Reproduce**
1. Create new order in back-end.
2. Choose Admin Payment Link

**Expected behavior**
- A payment link in the e-mail.
- A payment link in the back-end.

**Actual behavior**
No payments links.

**Screenshots**
There should be a payment link here to copy:
![Screenshot 2023-09-25 at 13 05 31](https://github.com/mollie/magento2/assets/53861858/a14dfc0d-6e72-49c3-ba55-a53fe49a24e2)

Settings:
![Screenshot 2023-09-25 at 13 09 19](https://github.com/mollie/magento2/assets/53861858/7221673a-708c-4e0a-ada0-b96df381322b)

**Comment by Frank-Magmodules** [comment]
Hello @tropilex, we've recently released a [new version](https://github.com/mollie/magento2/releases/tag/v2.31.0) of the Mollie plugin, in which we believe we have addressed and resolved the issue you've encountered. Could you please update the plugin to the latest available version and let me know if this problem has indeed been resolved? Your feedback will help us confirm the fix and close this issue. Thank you!

**Comment by tropilex** [comment]
@Frank-Magmodules I'm waiting on the update from the developers. It's ready but not live yet.

**Comment by Frank-Magmodules** [comment]
HI There @tropilex , 

I wanted to inform you that we've recently developed a new version of the Mollie plugin, which includes an additional fix related to the payment link. However, I believe the previous release already resolved the issue you had raised. Could you please confirm if the update has been applied, and if so, kindly update this ticket accordingly?

**Comment by tropilex** [comment]
Yes it’s working since the last update.



Op di 24 okt 2023 om 16:18 schreef Frank Tiggelman ***@***.***

**Comment by Frank-Magmodules** [comment]
Perfect, thanks for your confirmation, closing this issue now.
