### ISSUE TITLE
Error in mollie.log with No RedirectUrl found, and not update of status on successfull webhook call

### ISSUE THREAD

**Issue by patricksteenks** [mollie/magento2#694]
**Describe the bug**
For some ideal orders the webhook is not called correctly. In de Mollie Orders dashboard we see the order, the payment of the order and a successfull webhook request. However, if we turn to magento for the same order, we still see status pending payment.

When visiting the log we see an error:  Mollie.ERROR: error: RedirectUrl: No redirect url found for order xxx [] []

**Used versions**
- Magento version 2.4.6-p2
- Open-Source
- 2.30.1

**To Reproduce**
Difficult to say, as this not appears for all orders, only some. We don't see any remarkable differences with "normal" mollie orders, although the error seems to occur only on ideal payments. About 0,5% of our orders are inflicted by this bug.

**Expected behavior**
A successfull webhook call for paid orders and status update in Magento, without the error of No Redirect url found.

**Actual behavior**
The status of the order is not updated in magento from "pending_payment" to "processing".

**Comment by simonmaass** [comment]
I can confirm this... we have found about 2-3% of order with this... very difficult to debug...

**Comment by Frank-Magmodules** [comment]
Hi There @patricksteenks and @simonmaass , This doesn’t seem to come from the webhook response but from the initial communication between Mollie and Magento. Could you please provide the logs from orders that are affected? That way we can take a closer look at what is going on exactly.

Thanks!

**Comment by patricksteenks** [comment]
Off course, but I do not feel comfortable sharing this information publicly. Can I mail them to you?

**Comment by Frank-Magmodules** [comment]
I understand, my apologies for not mentioning our support form earlier. We did receive your information via direct email. I will look into your response and provide a follow-up shortly.

**Comment by Frank-Magmodules** [comment]
Goodmorning @patricksteenks ,, 

We're happy to inform you that we've successfully resolved the bug you reported in the most recent release of the Mollie Magento 2 plugin, [version 2.32.0](https://github.com/mollie/magento2/releases/tag/v2.32.0#:~:text=Throw%20an%20error%20when%20the%20order%20is%20locked%20so%20the%20webhook%20gets%20retried%20%23694). As a result, I'm closing this issue, confident that it will solve your issue. However, if you have any further questions or require additional help with this matter, please don't hesitate to reopen this issue or create a new one.
