### ISSUE TITLE
Credit Memo cannot be executed Order Status Processing

### ISSUE THREAD

**Issue by in-session** [mollie/magento2#696]
**Describe the bug**
When the order status is Processing, and you go into the invoice of the order, it is not possible to create a Credit Memo. 

We receive the following message:
- Order can only be refunded after Klarna has been captured (after shipment)
- Mollie API: Order can only be refunded after Klarna has been captured (after shipment)

**Used versions**
- *Magento Version 2.4.6-p2*
- *Open source*
- *Mollie version number 2.31.0 with Payments API*

**To Reproduce**

1. Add item to shopping cart
2. Checkout with Klarna Pay Now
3. Go to the admin in the order
4. Open the invoice view
5. Create a credit memo within the invoice with refound

**Expected behavior**
Generate the credit memo and change the order to Closed. Cancel the order with the payment providers and refound the current amount if it is already collected. 

**Actual behavior**
You would have to create a delivery bill here so that you can cancel the order.

**Comment by Frank-Magmodules** [comment]
Hi There @in-session ,

Thank you for opening this issue. It is indeed not possible to refund an order when it’s paid with Klarna and the invoice is created. You can change the behavior when the invoice is created to prevent this. 

You can change this under “Stores -> Configuration -> Mollie -> Advanced -> Triggers & Languages -> When to create the invoice?” and then change the setting to “_On Shipment_”.

**Comment by Frank-Magmodules** [comment]
Hi There @in-session , can you let me know if my comment above answers solves your issue?

**Comment by Frank-Magmodules** [comment]
Goodmorning @in-session,

Because of inactivity and the belief that this issue may be related to a configuration problem rather than a plugin issue, I am closing this matter for the time being. If you have any further questions or concerns regarding this issue, please don't hesitate to reopen this ticket or reach out to us directly.
