### ISSUE TITLE
Payment Surcharge as additional cost like shipment

### ISSUE THREAD

**Issue by in-session** [mollie/magento2#697]
**Describe the bug**
I think it is legally a problem to make a payment surcharge without making this clear. As soon as you set the payment surcharge to 3%, for example, the total price is only increased without any further information.

**Used versions**
- *Magento Version 2.4.6-p2*
- *Open source*
- *Mollie version number 2.31.0*

**To Reproduce**
1. Go to admin > mollie > Payment Methods
2. Click on Klarna Slice > Payment Surcharge > percent + Payment Surcharge percentage > 3

**Expected behavior**
Showing an additional total segment for additional fees. Also, the fee of 3 percent should already be noted with the respective payment provider.
![image](https://github.com/mollie/magento2/assets/16542619/1776545b-3587-440b-a6ce-a1cc4d639988)

**Actual behavior**
Only a price increase in the Grand total without seeing why the price increases.
![image](https://github.com/mollie/magento2/assets/16542619/d61aeec2-1678-4e09-905e-1747a8152ce6)

**Comment by Frank-Magmodules** [comment]
Hello @in-session ,

Thank you for opening this issue. The payment fee is already labeled as such, but when looking at the screenshot I noticed that you changed the title to something more generic. You can always change this back to make it more clear for the customer.

For the title of the payment method: This is already discussed in the issue; https://github.com/mollie/magento2/issues/634#issuecomment-1588883090
