### ISSUE TITLE
iDeal issuer dropdown list is sometimes empty

### ISSUE THREAD

**Issue by dverkade** [mollie/magento2#698]
**Describe the bug**
iDeal issuer dropdown list is sometimes empty, see screenshot

![image](https://github.com/mollie/magento2/assets/1058480/95b0fd7e-0380-4fe3-8efa-1fec5ae43696)

**Used versions**
- *Magento Open Source: 2.4.6-p2
- *Open source/Enterprise/B2b*:
- *Mollie version number (Check configuration)*: [v2.30.1](https://github.com/mollie/magento2/releases/tag/v2.30.1)

**To Reproduce**
1. Currently not known, it works and after a certain period the list is empty. This happened in 3 separate occasions
2. Issue is fixed when emptying the cache, which leads me to think it has something to do with retrieving and caching the issuer list
3. Could it be that the issuerlist is empty as the dropdown box also doesn't show "Please select" and that it returns on this line: https://github.com/mollie/magento2/blob/master/Model/Mollie.php#L601 and the result is being cached

**Expected behavior**
Always show the issuer list

**Actual behavior**
Sometimes issuer list is empty.

**Comment by dverkade** [comment]
After loading for a day the issue is now appearing again: 
![image](https://github.com/mollie/magento2/assets/1058480/0daf1895-2c2a-4049-8d3a-f5ee86a43b25)

And after flushing the cache is showing the issuers again: 
![image](https://github.com/mollie/magento2/assets/1058480/334e2841-520a-437a-ab3a-4d57f8455055)

**Comment by Frank-Magmodules** [comment]
Hello, @dverkade! thank you for opening his issue. I've already reached out to you via email to discuss it further since we're currently unable to replicate the issue.

**Comment by Frank-Magmodules** [comment]
Hi @dverkade, Goodmorning over there,

We're delighted to report that we've implemented a solution that involves reattempting to retrieve the issues in case no value is returned in the latest release of the Mollie Magento 2 plugin, [version 2.32.0](https://github.com/mollie/magento2/releases/tag/v2.32.0#:~:text=Retry%20to%20retrieve%20the%20issuers%20when%20no%20value%20is%20returned%20%23698). 

As a result, I'm closing this issue, confident that it will solve your issue. However, if you have any further questions or require additional help with this matter, please don't hesitate to reopen this issue or create a new one.
