### ISSUE TITLE
Second Chance Email does not take salable quantity in account

### ISSUE THREAD

**Issue by gjportegies** [mollie/magento2#699]
**Describe the bug**
The second chance email is being send while a product became out of stock.

**Used versions**
- *Magento Version number*: **2.4.6**
- *Open source/Enterprise/B2b*: **Open Source**
- *Mollie version number*: **2.29.1**

**To Reproduce**
1. Enable second chance emails.
2. Add a product to the cart that has a stock quantity of 1.
3. Go through the checkout process but cancel the payment.
4. Complete a different order with the same product.
5. The quantity of the product is now 0.
6. The second chance email is still being send and the customer is able to complete the order while the product is out of stock.

**Expected behavior**
The second chance email should not be send.

**Actual behavior**
The second chance email is being send while the product became out of stock. This makes it possible for the customer to still order an out of stock product.

**Comment by Frank-Magmodules** [comment]
Hi There @gjportegies , 

Thank you once more for submitting this issue! We're happy to inform you that we've successfully resolved the bug you reported in the most recent release of the Mollie Magento 2 plugin, [version 2.32.0](https://github.com/mollie/magento2/releases/tag/v2.32.0). As a result, I'm closing this issue, confident that it will solve your issue. However, if you have any further questions or require additional help with this matter, please don't hesitate to reopen this issue or create a new one.
