### ISSUE TITLE
this module seem incompatible with magento 2.4.6-p2

### ISSUE THREAD

**Issue by mcs-jonasvanderhaegen** [mollie/magento2#700]
**Describe the bug**
errors with webhook, unable to fetch status when editing order as admin.

When placing order with payment method Paypal, in access logs:

200  1.518 BE 185.174.184.98  GET /fr/mollie/checkout/redirect/paymentToken/bqaHd3LFyy11ZzSida9wBJR4yKYSRGg2 HTTP/2.0

503  0.499 US 34.76.90.110    POST /fr/mollie/checkout/webhook/?isAjax=1&orderId%5B%5D=MDozOmJ4OWQrbzl6Q3VZU3BIT0VWZUxybnJmVm5hSW9mTEVpKzBKZVltOS9tdz09 HTTP/1.1

200  0.475 US 34.76.90.110    POST /fr/mollie/checkout/webhook/?isAjax=1&orderId%5B%5D=MDozOmJ4OWQrbzl6Q3VZU3BIT0VWZUxybnJmVm5hSW9mTEVpKzBKZVltOS9tdz09 HTTP/1.1

302  0.687 BE 185.174.184.98  GET /fr/mollie/checkout/process/?order_id=168&payment_token=bqaHd3LFyy11ZzSida9wBJR4yKYSRGg2&utm_nooverride=1 HTTP/2.0

when doing fetch status on edit order:

503  3.420 BE 185.174.184.98  POST /admin_ohp5p3/mollie/action/fetchOrderStatus/key/645f105df40d63c2e20515e4e9505a69c86159e6d1a4f1ec313b10a738820201/?isAjax=true HTTP/2.0

Error while fetching:
Unable to unserialize value. Error: Parameter must be a string type, null given.

I do see logs in mollie.log.

**Used versions**
- *Magento Version number(ver. 2.4.6-p2)*:
- *Open source*:
- *Mollie version number (v2.31.0)*:

**To Reproduce**
have magento 2.4.6-p2 running.

**Expected behavior**
Everything works, orders get updated with status processing.

**Actual behavior**
Errors

**Comment by mcs-jonasvanderhaegen** [comment]
It appears it might be due to a different custom module of ours. I'll close this issue for time being.

**Comment by Frank-Magmodules** [comment]
Thanks @mcs-jonasvanderhaegen , let me know if you need help on that!
