### ISSUE TITLE
Mollie 2.32.1 : Invoice View issue in backend

### ISSUE THREAD

**Issue by jigardhaduk** [mollie/magento2#707]
**Describe the bug**
When we open the Invoice View page.

**Used versions**
- *Magento Version number(eg 2.4.6-p3)*:
- *Open source*:
- *Mollie version number (2.32.1)*:

**To Reproduce**
1. Go to Backend
2. View some Invoice under Sales -> Invoice menu
3. See error as below screenshot

**Expected behavior**
An invoice page should open without error.

**Actual behavior**
It is showing error as below screenshot.

**Screenshots**
![image](https://github.com/mollie/magento2/assets/15403998/48563a2e-8478-4d24-a7f6-7582a24d73d0)

**Comment by stm-hamburg** [comment]
Hello Frank,
When can we expect the bug to be fixed?
It is very urgent as we cannot process invoices.

Thanks,
Jan
www.toneart-shop.de

**Comment by Frank-Magmodules** [comment]
HI There @jigardhaduk , @stm-hamburg  and @Melleschepers , thank you for opening and commenting on this issue.

We’ve just released a [new version](https://github.com/mollie/magento2/releases/tag/v2.32.2) where we have removed the helper file regarding the payment fees and taxes. 
It seems that there are too many scenarios and vital functions that can lead to issues in this case. 

We are taking a look at this functionality and how we can prevent any more errors. We will do so by adding more tests to this section, either end-to-end or integration tests, whatever is required to make this code behave without bugs.

We’ll mark this issue as resolved for now, but please don’t hesitate to respond or reopen the ticket whenever necessary. Thank you!
