### ISSUE TITLE
Error: htmlParseEntityRef: expecting ';' in Entity, line: 1

### ISSUE THREAD

**Issue by gerben86** [mollie/magento2#71]
Zodra ik een order in de admin open verschijnt deze regel in de exception.log:
`[2018-08-27 11:30:20] main.CRITICAL: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1 {"exception":"[object] (Exception(code: 2): DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1 at ......./vendor/magento/framework/Escaper.php:71)"} []
`
Volgens mijn ontwikkelaar ligt hem dat aan het volgende:

> It is caused by order note information like - 
![image](https://user-images.githubusercontent.com/17478858/44672693-777f1b80-aa29-11e8-89f2-f5430d73d512.png)
Before save this string should have parsed html special characters.

Oftewel, het opslaan van deze informatie zorgt voor exceptions bij het openen van de order in de backend. Zouden jullie hiernaar kunnen kijken?

Magento 2.2.4

**Comment by Frank-Magmodules** [comment]
Hi @gerben86 ,

Also see Magento issue: https://github.com/magento/magento2/issues/13269
Can be reproduced by adding a comment with just: "&".  Same exception will show up in the logfile.

**Comment by GuiltyNL** [comment]
Do we need to wait for Magento to fix this? It is not a stopper, but it is a bit annoying that it floods the logfiles with this error message.

**Comment by Marvin-Magmodules** [comment]
Hi @GuiltyNL what version of the Mollie module are you using at this moment? As since version 1.4 no url is saved to the order comments.

**Comment by GuiltyNL** [comment]
@Marvin-Magmodules The most recent version, but maybe the error in the log is not because of your module. I'll investigate.
