### ISSUE TITLE
[ISSUE] Vowel mutation not properly escaped in basked product name

### ISSUE THREAD

**Issue by simonmaass** [mollie/magento2#714]
**Describe the bug**
Vowel mutation for product names in basket not properly escaped

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6-p3
- *Open source/Enterprise/B2b*: OS
- *Mollie version number (Check configuration)*: 2.32.2

**To Reproduce**
1. Create product with name including vowel mutation e.q. "Orthopädische Einlagen für Alltagsschuhe"
2. Create order including this product with mollie payment 
3. Check basket description in mollie dashboard

**Expected behavior**
The product name is "Orthopädische Einlagen für Alltagsschuhe"

**Actual behavior**
The product name is "Orthopdische Einlagen fr Alltagsschuhe"

**Screenshots**
<img width="329" alt="image" src="https://github.com/mollie/magento2/assets/32599710/10042dea-3108-4f01-9134-a356946c5e8e">

**Comment by Frank-Magmodules** [comment]
Hi There @simonmaass , We've just released version [2.33.0](https://github.com/mollie/magento2/releases/tag/v2.33.0), including a fix for this issue. We're currently closing this matter, but please don't hesitate to reopen the issue if necessary.
