### ISSUE TITLE
Admin Payment Link Expiring Too Soon

### ISSUE THREAD

**Issue by jorgb90** [mollie/magento2#718]
**Describe the bug**
When creating an order in the admin using a Payment Link as payment the link is successfully created but doesn't adhere the Days to expire. It expires almost directly instead of the set 5 days (for us) or default 28 days.

**Used versions**
- Magento 2.4.6-p2
- Open source
- *Mollie version number (Check configuration)*: 2.32.3

**To Reproduce**
1. Go to admin
2. Create admin order
3. Use Mollie Payment Link as payment option
4. Wait until Mollie decides to expire it

**Expected behavior**
Adhere days set

**Actual behavior**
Few hours

**Comment by Frank-Magmodules** [comment]
Hello @jorgb90, thanks once again for raising this issue! I'm delighted to inform you that we've just released a [new version](https://github.com/mollie/magento2/releases/tag/v2.32.4), addressing the problem you described. Should you have any additional questions or comments regarding this issue, please feel free to respond within the issue thread.

**Comment by mikemoooo** [comment]
Hi @Frank-Magmodules ,
I've updated the module and cannot create payment links anymore.
Receiving the error below. Could you please look into this?

Order saving error: Warning: count(): Parameter must be an array or an object that implements Countable in .../vendor/mollie/magento2/Service/Order/MethodCode.php on line 37

Thanks a lot!

**Comment by Frank-Magmodules** [comment]
Hi There @mikemoooo , 

We investigated the error you're experiencing and found that it occurs when no payment methods are selected in the multiple-select field designed to limit method options. To temporarily resolve the issue, please do select some payment methods to proceed or apply [this](https://patch-diff.githubusercontent.com/raw/magmodules/mollie-magento2/pull/697.diff?token=ABMWLCMY5M2VHVANRCZ46CLFMRIEK) patch file. Surely, we will include this fix in our upcoming release!

**Comment by mikemoooo** [comment]
Hey @Frank-Magmodules ,
Thanks for looking into this.
I cannot open the patch file, but selecting the methods currently works for us.
We'll keep an eye out for the next release!

**Comment by Frank-Magmodules** [comment]
Hello @mikemoooo, you're correct. It was initially in our private repository, but I've now made it publicly available. Thanks for bringing it to my attention. I'll keep this issue open until the release is complete. Have a great day!

**Comment by Swahjak** [comment]
I'm sure there is no intent here, but could we please stop breaking stuff, expand on testing capabilities or use proper semantic versioning. I get the feeling that every time I update one of our most essential modules, something breaks.

**Comment by Frank-Magmodules** [comment]
Hello @swajhak, we've introduced several nice features and enhancements recently.
However, we acknowledge that certain changes have had some adverse effects. We take this matter seriously and are actively enhancing our manual testing processes while also working to add more scenarios to our automated tests. I will reach out to you directly for a conversation about this and to gather your opinion on how we can enhance semantic versioning from your perspective.

**Comment by simonmaass** [comment]
Today we deployed the new version and are experiencing the exact same issue... this is quite bad for us!

**Comment by Frank-Magmodules** [comment]
Hey @simonmaass , are you referring to this particular issue? If so, feel free to check out the solution above, and if you require further help, you know where to reach me. Thanks!

**Comment by simonmaass** [comment]
yeah i just saw the patch... would be great if you would add the patch file more visible? maybe in the release notes https://github.com/mollie/magento2/releases/tag/v2.32.4

**Comment by mikemoooo** [comment]
Hi @Frank-Magmodules

I've applied the patch, so there is no more error creating the payment link.
However, I've created a payment link for an order yesterday and it's already expired.
The expiration time is set to 28 days in the config.

From the mollie dashboard it shows that the order was cancelled and then the webhook was called to update the order in Magento:

History
- Webhook called successfully, it took 1.2 seconds 4 December 2023 at 21:00
- Order ord_1.z1xj1o has been canceled from status created 4 December 2023 at 21:00
- Order created 4 December 2023 at 12:05

Can you check what this is related to?

Cheers,
Mike

**Comment by jorgb90** [comment]
Same issue here. Its still not working correctly.

**Comment by Frank-Magmodules** [comment]
Hello all,

Thank you all for your patience. We are currently under a release freeze as it’s the busiest time of the year for most webshops. This release stop is here for the rest of the month, thank you for understanding that.

**For this payment link issue.**
There are a few scenarios at play here:

1. Creating a payment link order with a single payment method selected.
2. Creating a payment link order with multiple methods selected (or none, or all).

Both these scenarios have also the option to set a manual expiry date on the order. In our latest release ([v2.32.4](https://github.com/mollie/magento2/releases/tag/v2.32.4)), we release a fix for scenario one. Upon investigation, it looks like the problem still exists when a payment link order is placed with multiple methods selected. Could you please confirm this @mikemoooo and/or @jorgb90 ?

We already tackled this problem. You can find the patch for this [here](https://gist.github.com/Frank-Magmodules/3ff3e2f466cd4aa937dd06f948258046). For reference, the previous patch can be found [here](https://gist.github.com/Frank-Magmodules/3b908b149c1032bdcbcad9c67bb35929#file-gistfile1-diff). That one was to fix the `Parameter must be an array or an object` error.

**Comment by Frank-Magmodules** [comment]
HI @mikemoooo ,
It seems you are right. The `expiresAt` date is now being sent correctly to Mollie, but it turns out that for some payment methods, this time is not honored. This does make sense for some types of payments, i.e. iDeal, but from the payment link context, this is way too soon. We are going back to the drawing board to see if we can fix this issue once and for all.

**Comment by mikemoooo** [comment]
Hi @Frank-Magmodules,
any news on this? We are still experiencing the issues

**Comment by dragonfly4** [comment]
We also have issues so looking forward for an update.

**Comment by Frank-Magmodules** [comment]
Hi There @mikemoooo  and @dragonfly4 , I appreciate your patience as you await the release. I'm pleased to inform you that we will be releasing an update, including the awaited feature/fix, no later than upcoming Wednesday. Thank you for your understanding.

**Comment by Frank-Magmodules** [comment]
Hi @mikemoooo  and @dragonfly4 , finally we have released the new [2.33.0](https://github.com/mollie/magento2/releases/tag/v2.33.0) version with a solution to this issue, let me explain a bit about what we have developed/changed within the payment-link process.

The situation before was that, when the admin created an order, we placed an order or payment in Mollie's systems. The Orders within Mollie have a Payment attached, but that payment expired within 15 minutes after creation, causing issues with orders that were canceled too soon.

We now have changed this behavior. Now, when the admin created the payment link order, nothing happened on Mollie's side. The link in the email now points to a controller within the webshop. We are only creating the transaction in the Mollie system the moment the customer clicks on the link in the email. This way, the transaction can’t expire before the customer clicks the link.

The new version can be found [here](https://github.com/mollie/magento2/releases/tag/v2.33.0), and will probably cover all your needs.
I'm closing this issue now, but please don't hesitate to reopen the issue if necessary.

**Comment by simonmaass** [comment]
@Frank-Magmodules just to clarify... 
Your comment "The link in the email now points to a controller within the webshop. " -How does this affect customers that use magento as backend and have a custom PWA webshop?

**Comment by Frank-Magmodules** [comment]
Created an issue for that @simonmaass https://github.com/mollie/magento2/issues/732! 
Thanks for bringing this in.

**Comment by mikemoooo** [comment]
@Frank-Magmodules  The issue seems to be resolved for us. Thanks for the updates!
