### ISSUE TITLE
{{var order.mollie_transaction_id}} 

### ISSUE THREAD

**Issue by Sendurrr** [mollie/magento2#719]
Hello,

We use the following var for sending emails with a pay button in it with the {{var order.mollie_transaction_id}}  variable in it:

{{var order.mollie_transaction_id}}

like this: https://www.mollie.com/checkout/order/{{var order.mollie_transaction_id}}

This always worked, but since a few days it stopped working

The variable gives this link: https://www.mollie.com/checkout/order/ord_xxxxxxxx which always worked, but now is giving a 404 error.

If we change the url to: https://www.mollie.com/checkout/order/xxxxxxxx it works. So if we remove "**ord_**" in the url it works. How can we fix this so that "ord_" is not being returned by the {{var order.mollie_transaction_id}} variable ?

**Comment by Frank-Magmodules** [comment]
Hi There @Sendurrr , Thank you for opening this issue. In which email are you using this variable? Or is this a custom email? In the case of a custom e-mail, we are saving the dashboard URL in the additional information column of the payment. You can use that to get the link to the transaction.

**Comment by Sendurrr** [comment]
we use it in custom emails. but this has always worked. Somehow mollie does not accept the ord_ prefix in the link anymore which is given by the var order.mollie_transaction_id

how can we get ridof this ord_ prefix which is named by the variable ?

**Comment by Sendurrr** [comment]
Found it here on Mollie.php

![image](https://github.com/mollie/magento2/assets/46919920/7e07c551-d9db-4a3a-8e57-16f4f9ad6dcd)


I am no developer, but this ord_ prefix causes the 404 page at mollie. Can we remove this ?

**Comment by Sendurrr** [comment]
Herre an example:

![image](https://github.com/mollie/magento2/assets/46919920/326f7f60-a9fb-4724-b2f3-432863505f18)

So in the email we just do this:

https://www.mollie.com/checkout/order/{{var order.mollie_transaction_id}}

Which makes it:

https://www.mollie.com/checkout/order/ord_1.909wec

which does not work anymore since a week. This link works though:
https://www.mollie.com/checkout/order/1.909wec


so we want to get rid of this ord_ prefix. How can we do this.

**Comment by Frank-Magmodules** [comment]
HI, There @Sendurrr ,

Thank you for providing additional comments on this matter. However, it seems that you are using the information in the database in a way that it is not intended for. That it worked up until now seems to be luck and it seems, but I can't tell this without knowledge of your exact implementation.

Anyway, to have the correct URL you can use something like this:
`$order->getPayment()->getAdditionalInformation('dashboard_url')`

But as you are running this in custom code I can’t say where and how to place this peace of code. 
For that, you need to contact your developer.

**Comment by Sendurrr** [comment]
ok will do. strange though that the variable is defined, but is actually useless for use to send a customer to the payment page .....

**Comment by Sendurrr** [comment]
By the way, we use this for Mollie backend payments. So we when create the order from the backend, the customer gets an email with a mollie payment button which sends them to the mollie payment page. We don't have a dashboard_url in additionalinformation. We got a checkout_url though. Must this be so difficult? Why doesnt just the {{var order.mollie_transaction_id}} work. Why is this transaction id different in magento than it is on the mollie site (the ord_ prefix)?

**Comment by Sendurrr** [comment]
we fixed it by creating a custom extension based on this piece of code $order->getPayment()->getAdditionalInformation('dashboard_url')


thanks

**Comment by Sendurrr** [comment]
Hello @Frank-Magmodules we also want to call the {{var link}} for the SecondChanceEmail from another email extension within magento2 (it is not recognized in that extension). how can we call this variable correctly? can you help us? thanks
