### ISSUE TITLE
Mollie order refund not creating when shipping is zero 

### ISSUE THREAD

**Issue by mageget-info** [mollie/magento2#720]
**Describe the bug**
Mollie order refund not creating when shipping cost is zero, its issue from version 2.31.1, i have added the detail in Additional context.  

**Used versions**
- *Magento Version number(eg 2.4.6-p3)*:
- *Open source*:
- *Mollie version number (v2.32.3)*:

**To Reproduce**
1. Created a order with shipping cost zero
2. try to refund the order, then credit memo creating but refund not creating in mollie dashboard 
3. Make sure placing the order with IDeal Payment and API Method is Order API
![image](https://github.com/mollie/magento2/assets/121968995/93d3db61-10dd-4b1b-951c-d19fb8c3823b)

**Expected behavior**
Its should create online refund in Mollie

**Actual behavior**
Its not creating online refund in Mollie

**Screenshots**

**Additional context**
Also, after debugging  we have found the new chainage in 
![image](https://github.com/mollie/magento2/assets/121968995/c6d30ba4-1703-446e-9579-416d9134c480)

https://github.com/mollie/magento2/blob/296a5a221e682416fdf3d528ed6c6da4aefdca50/Model/Client/Orders.php#L760 if we rollbacking to  release/2.31.0, its working as expected.

![image](https://github.com/mollie/magento2/assets/121968995/66d6e82c-a9d0-4e99-a52f-7a26122347d8)

**Comment by Frank-Magmodules** [comment]
Hello @mageget-info, appreciate your complete and clear description of the issue. I'm happy to share that we've just released [version 2.32.4](https://github.com/mollie/magento2/releases/tag/v2.32.4), addressing the problem you mentioned. I'm marking this issue as closed. However, should you have any further questions or comments on this matter, please feel free to respond within the issue thread.
