### ISSUE TITLE
[FEATURE REQUEST] Add Profile ID validation

### ISSUE THREAD

**Issue by shawnvdp** [mollie/magento2#726]
# Describe the new feature
Profile ID validation in the admin.

## Describe the solution to be implemented
Like the API keys, validate the Profile ID similarly.
The Profile ID has a requirement of starting with `pfl_`, but nothing informs the user when this isn't the case.
In our case, a space was accidentally included at the start of the Profile ID, which wasn't immediately obvious until a breakpoint was set on the frontend.

**Backend changes**
Ability to validate the Profile ID like the frontend during checkout.

**Frontend changes**
N/A

**Additional context**
N/A

**Comment by Frank-Magmodules** [comment]
HI There @shawnvdp ,

Thank you for opening this issue. We just released a [new version](https://github.com/mollie/magento2/releases/tag/v2.35.0) which addresses this issue. There is no validation in this field. Instead, the profile id is fetched from Mollie. So now you don’t have to fill this in manually, eliminating the risk of wrong user input.

We're currently closing your request, but you're welcome to reopen it or leave a comment if required.
