### ISSUE TITLE
Something went wrong.

### ISSUE THREAD

**Issue by vadim-shulyak** [mollie/magento2#73]
Hi there! I have the notice message: "Something went wrong." during the checkout.

Magento 2.2.3

Steps to reproduce:
- use "Mollie" in the test mode
- add any product to the cart, go to checkout
- use "iDeal" method
- fill all required fields with valid data 
- place order
- at the redirected page (https://www.mollie.com/paymentscreen/testmode/?method=ideal) choose the "canceled" option

**Result:** 
Redirected to the cart page with the notice:
"Something went wrong."
Creates an order with the status "Pending Payment"

The order was created 
**Expected result:** 
No errors, notices
Redirect to the success page
Creates an order with the status "Canceled"

============================

Possible cause of the issue:
vendor/mollie/magento2/Controller/Checkout/Success.php
Line 98: 
if (isset($status['status']) && $status['status'] == '**cancel**') {

There is no "cancel" value at the **sales_order_status** table, there is **canceled**

Thanks for reply!

**Comment by Frank-Magmodules** [comment]
Hi @vadim-shulyak ,

Thank you for the detailed issue. What version of the module are you using in this sample?

**Comment by vadim-shulyak** [comment]
Hi @Frank-Magmodules,
<module name="Mollie_Payment" setup_version="1.3.6" />

**Comment by Frank-Magmodules** [comment]
Hi @vadim-shulyak , 

Strange, can you please contact us directly on https://www.magmodules.eu/contact-us.html so we can take a look with you on the log files and help you out on this?

Thanks!

**Comment by vadim-shulyak** [comment]
@Frank-Magmodules, I've reproduced the same issue on the new (empty) Magento 2.2.3 project, please, just follow described steps and try to reproduce. It seems that you don't need my logs, you are able to reproduce it and fix on the new (empty) Magento v2.2.3.

Thanks!

**Comment by Frank-Magmodules** [comment]
@vadim-shulyak ,

Sure, i will try to reproduce this asap and let you know my experiences.

Frank

**Comment by Marvin-Magmodules** [comment]
@vadim-shulyak just pushed a fix for the cancellation message to the [1.3.7](https://github.com/mollie/magento2/tree/1.3.7) branch, can you confirm the workings? About the status not being updated; is your webhook accessible or are you running a local environment? The status is updated by the webhook, so this should be accessible by Mollie.

**Comment by vadim-shulyak** [comment]
@Marvin-Magmodules , thank you! You were right it works, it was the base authentication enabled.
