### ISSUE TITLE
[FEATURE REQUEST] PWA Support for the new PaymentLink flow

### ISSUE THREAD

**Issue by Frank-Magmodules** [mollie/magento2#732]
We introduced a controller for payment link users to address expiration issues. 
To optimize for PWAs, we must:

- Configure the URL, as PWAs may have different URLs.
- Enable triggering the process via GraphQL and/or REST, retrieving the redirect URL for the customer.

**Comment by Frank-Magmodules** [comment]
Hello @simonmaass,

I'm happy to share that we've included your request in the [latest plugin](https://github.com/mollie/magento2/releases/tag/v2.34.0) version, and you can find details about PaymentLink and PWA support in the technical wiki right [here](https://github.com/mollie/magento2/wiki/GraphQL-integration#extra-payment-link-for-pwas). Since it seems like your request is now addressed, I'm closing this issue. However, feel free to respond or reopen it if necessary. Thanks for your input!

**Comment by simonmaass** [comment]
@Frank-Magmodules thank you for adressing this issue!

Would you kindly point me to the wiki part for the REST api version... I can only find the graphql endpoint... we are using REST.... thank you!

**Comment by Frank-Magmodules** [comment]
HI There @simonmaass , sure, we will add the REST API support to the next release as well!
