### ISSUE TITLE
"Magento Discount", "Adjustment" | Naming & Translations

### ISSUE THREAD

**Issue by mvenghaus** [mollie/magento2#733]
In your module you create two order lines: "Magento Discount" and "Adjustment" . These order lines are visible to the customer.

**Magento Discount**
- is this the correct naming!? .. because it lives in ShippingDiscount.php
- there is no translation in the module for this

**Adjustment**
- the name is not translatable

**Comment by Frank-Magmodules** [comment]
Hi There @mvenghaus ,

Thank you for opening this issue. You are correct about the shipping discount naming, that is wrong. But these names shouldn’t be visible to customers of the webshop. Can you tell me where you can see those? These should only be visible in the Mollie dashboard.

Thank you!

**Comment by mvenghaus** [comment]
Hey @Frank-Magmodules,

I have only screenshots from customers, so I don't know exactly. But I think it is visible in the Klarna App (or Website).

**Comment by fjbender** [comment]
I can confirm we submit these lines to Klarna. It would make sense to have them translateable.

**Comment by Frank-Magmodules** [comment]
Gotcha, on the list for the next release, thanks @fjbender and @mvenghaus !

**Comment by Frank-Magmodules** [comment]
Hi There @mvenghaus, I'm glad to inform you that we have addressed the issue you reported in our [latest release](https://github.com/mollie/magento2/releases/tag/v2.35.0). As a result, I will now close this issue. Thank you for bringing it to our attention!
