### ISSUE TITLE
Webapi broken after upgrade from v2.31.0 to 2.33.0

### ISSUE THREAD

**Issue by jvkranenburg** [mollie/magento2#735]
**Describe the bug**
After upgrading from v2.31.0 to v2.33.0 we get errors (and no date back) from the webapi.

**Used versions**
- *Magento Version number*: 2.4.6-p2
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 2.33.0

**To Reproduce**
1. Upgrade plugin from v2.31.0 to v2.33.0
2. Try to retrieve something by webapi
3. Cannot connect
4. See error below.

**Expected behavior**
Can connect to webapi and retrieve data.

**Actual behavior**
Cannot connect

**Error in Log**
See file 
[exception.txt](https://github.com/mollie/magento2/files/14026373/exception.txt)

**Issue in file**
Api/Webapi/PaymentInformationMetaInterface.php

`namespace Mollie\Payment\Api\Webapi;

interface PaymentInformationMetaInterface
{
    /**
     * @return \Mollie\Payment\Api\Data\MethodMetaInterface[]
     */
    public function getPaymentMethodsMeta(): array;
}`

**Comment by Frank-Magmodules** [comment]
Hello @jvkranenburg,
We're delighted to inform you that we've recently launched a [new version](https://github.com/mollie/magento2/releases/tag/v2.34.0v2.34.0) of the plugin, addressing the issue you raised. Thanks for bringing it to our attention. I'm closing this issue for now, but feel free to reopen it whenever necessary. Appreciate your contribution!

**Comment by jvkranenburg** [comment]
Dank je wel Frank. We gaan het asap testen.

--
Met vriendelijke groet,

Jerry van Kranenburg

Dream Hosting
De Weide 50
3993 DX  Houten

WWW : www.dream-hosting.net
Tel: +31 (0) 30 60 42 797

KvK : 30185280
BTW : NL1705.57.534.B.01
