### ISSUE TITLE
Payment status stays on pending or canceled while the customer has paid.

### ISSUE THREAD

**Issue by MageShop57** [mollie/magento2#740]
**Describe the bug**
Payment status stays on pending or canceled while the customer has paid.

**Used versions**
- *Magento Version 2.4.5*:
- *Open source community version*:
- *Mollie version number 2.34.0*:

I'm getting this issue when customer use the credit cart payment on our Magento 2 multi stores.
If I click the button "Fetch Status", the payment status is updated.

![Screenshot_4](https://github.com/mollie/magento2/assets/103524485/f69d2919-64e3-4266-b591-8c4600ea6e21)
![image](https://github.com/mollie/magento2/assets/103524485/9c44a99d-3566-4f3a-b29d-ed4b896fda2e)

**Comment by Frank-Magmodules** [comment]
Hi There @MageShop57 , can you please [contact us](https://www.magmodules.eu/help) directly about this issue? As it seems we are not able to reproduce this, we need to take a look with you on the configuration, logfiles, and setup.

**Comment by fjbender** [comment]
@MageShop57 Can you also check (e.g. in your Mollie Dashboard) whether you see any issues around webhook delivery for that particular payment?

**Comment by MageShop57** [comment]
Hi Florian, hope you are keeping well.

I've noticed that the payment issue is occurring when enabling cloudflare.

The mollie is working fine once disabling the cloudflare.

Can you please explain me how to sort it?

Kind regards

**Comment by fjbender** [comment]
This sounds like something that is better analyzed with our tech support team, as it's not a bug in the plugin - could you please contact them directly at info@mollie.com? Thanks!

**Comment by Frank-Magmodules** [comment]
[like]  Frank Tiggelman reacted to your message:
________________________________
