### ISSUE TITLE
[BUG] Multiple Invoices are created with Klarna Pay Later

### ISSUE THREAD

**Issue by erwinromkes** [mollie/magento2#756]
**Describe the bug**
We have updated multiple Magento shops to the latest 2.35.1 version. Since then we see on multiple shops the same behavior: Multiple invoices are created with the amount of 0,00 and a empty product overview.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.4-p6 & 2.4.6-p4
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 2.35.0 & 2.35.1

**To Reproduce**
1. Place an Order with the payment method **Klarna Pay Later**
2. Go to the order in the Magento backend and click on the tab Invoices

**Expected behavior**
What we expect is 1 invoice that is created.

**Actual behavior**
Multiple invoices are created, the amount is different each time. Sometimes we see 2 extra invoices, in the screenshot you see 8. 

**Screenshots**
![Screenshot_20240306_110021](https://github.com/mollie/magento2/assets/61180307/889803ae-f2a2-4127-a1a5-44089d5d2669)

**Additional context**
If you downgrade the module to 2.34.0 the problem does not occur.

**Comment by i6media** [comment]
Same issue here, downgraded to 2.34.0 resolves the matter

**Comment by codebase-md** [comment]
Confirming the issue for multiple Magento Shops(all 2.4.6-p4).

**Comment by Frank-Magmodules** [comment]
hi There @codebase-md , @i6media and @erwinromkes , thank you for your patience while we addressed this issue. I'm pleased to announce that we've resolved the problem you reported in our [latest release](https://github.com/mollie/magento2/releases/tag/v2.36.0). As I'm confident this resolves the issue, I'll be closing it for now. However, if you have any other relevant questions or comments regarding this matter, please feel free to share them on this ticket. Thanks again!
