### ISSUE TITLE
Payment link url Can use the wrong base url

### ISSUE THREAD

**Issue by Sental** [mollie/magento2#758]
**Describe the bug**
When creating an order with payment link as the payment method it intermittently uses the admin scope instead of the store view scope for the base url in the order confirmation email.

The module must be configured to include the payment link url in the order confirmation email and be a multistore environment.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6-p3
- *Open source/Enterprise/B2b*: open source
- *Mollie version number (Check configuration)*: >= 2.34.0

**To Reproduce**
1. Create an order in the admin
2. Choose payment link as the payment method
3. Place the order
4. Check the link in the order confirmation email

**Expected behavior**
The link is created using the base url from the store of the order. eg. https://www.website.nl/mollie/checkout/paymentlink/

**Actual behavior**
The url in the order confirmation email is based on the base url of the admin environment. eg. https://admin.website.nl/mollie/checkout/paymentlink/

**Screenshots**

**Additional context**
A pull request will be opened with the fix for this issue.

**Comment by Frank-Magmodules** [comment]
Hi @Sental , Thank you for your continuous support here. We'll dive into the matter you've raised and review the [PR](https://github.com/mollie/magento2/pull/759) you've submitted. Your efforts are much appreciated. If everything checks out during our testing phase, we'll merge it into the upcoming release. I'll ensure this issue remains open until then.

**Comment by Frank-Magmodules** [comment]
Hi There @Sental , I'm pleased to inform you that we've addressed the issue you reported in our [latest release](https://github.com/mollie/magento2/releases/tag/v2.36.0). Thank you once again for bringing it to our attention. I'm closing this for now, but please feel free to reopen it if you have any further concerns or if you find it necessary.
