### ISSUE TITLE
Infinite money glitch: Additional store credit being added to initial amount after order cancel

### ISSUE THREAD

**Issue by KathiD303** [mollie/magento2#761]
**Describe the bug**
If a customer uses Magento store credit in the checkout, gets redirected to Mollie and then cancels the payment by using the "previous page" link, the used store credit gets added to the initial store credit value every time this is done resulting in a severe money glitch.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-p6
- *Open source/Enterprise/B2b*: Commerce Cloud
- *Mollie version number (Check configuration)*: 2.35.1

**To Reproduce**
1. Go to Magento checkout, use store credit for payment (do not pay 100% via store credit but only a partial value)
2. Click on any Mollie payment and get redirected to Mollie
3. Click on "previous page"
4. check cart: store credit was added to initial value

**Expected behavior**
Store credit stays the same after order cancellation

**Actual behavior**
used store credit gets added to inital store credit amount with every cancellation

**Screenshots**

_Used store credit_
![image](https://github.com/mollie/magento2/assets/89870175/496b7ff9-5309-4825-91bf-9994531395cb)

_Go back to cart_
![image](https://github.com/mollie/magento2/assets/89870175/380a8f5d-502b-434a-a4a8-4d1aefda555b)

_Used store credit was added to initial store credit_
![image](https://github.com/mollie/magento2/assets/89870175/adbab4b8-318c-4de1-9988-bf4f933ec1a6)

I am unsure if this can be reproduced in a M2 vanilla instance.

**Comment by Frank-Magmodules** [comment]
Hey @KathiD303, thanks for bringing up this issue. 
Are you using the [Adobe Commerce Store Credit](https://experienceleague.adobe.com/en/docs/commerce-admin/customers/customer-accounts/store-credit/store-credit) feature for this, or are you using a third-party plugin?

**Comment by Frank-Magmodules** [comment]
Thank you, @KathiD303. We're currently looking into this matter and will provide an update shortly.

**Comment by KathiD303** [comment]
@Frank-Magmodules : is there something new about this issue?

**Comment by Frank-Magmodules** [comment]
Hi @KathiD303 , unfortunately, we don't have something usable at the moment. However, we're in the final stages of completing a pending release. Once that's done, we'll be able to dive into this right away. But, your assistance could accelerate the process. Could you kindly share the details of your store/environment with us [here](https://www.magmodules.eu/help#:~:text=contact%40magmodules.eu)? This will enable us to promptly collaborate and resolve any issues together. Thanks a lot!

**Comment by Frank-Magmodules** [comment]
Hi There @KathiD303, I believe we've addressed your reported issue. Could you please reach out to me directly so we can review it together? Thank you!

**Comment by Frank-Magmodules** [comment]
Hello @KathiD303 , as per our email conversation, I wanted to inform you that we've just rolled out version [2.37.0](https://github.com/mollie/magento2/releases/tag/v2.37.0). This update includes a fix for the reported issue and adds support for Reward Points on your Adobe Commerce store. Hopefully, everything is now working as expected! I'll go ahead and close this issue for now, but don't hesitate to get in touch if you require further assistance. Thanks again for your cooperation!
