### ISSUE TITLE
Cannot use reward points when paying with Klarna Pay Now

### ISSUE THREAD

**Issue by KathiD303** [mollie/magento2#765]
**Describe the bug**
When using reward points in the checkout and proceeding the payment with Klarna Pay Now, the following error is shown: 

[2024-04-03T12:46:05+0000] Error executing API call (422: Unprocessable Entity): The amount of the order does not match the total amount from the order lines. Expected order amount to be €19.98 but got €17.48. Field: amount. Documentation: https://docs.mollie.com/overview/handling-errors

Please note that the amount difference in the error message corresponds to the bonus points applied (2,50€).

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5-p6
- *Open source/Enterprise/B2b*: Magento 2 Commerce Cloud
- *Mollie version number (Check configuration)*: 2.36

**To Reproduce**
1. Go to the checkout and use reward points on your order (only pay a partial amount of the order with reward points)
2. Click on pay with Klarna Pay Now and try to proceed with the payment
3. See error above

**Expected behavior**
Reward points can be used when paying with Klarna Pay Now

**Actual behavior**
Error message is displayed in cart

**Screenshots**
See screencast: https://go.screenpal.com/watch/cZfelHVslIX

**Comment by Frank-Magmodules** [comment]
Hey again @KathiD303! Thanks for bringing up this issue. Just to confirm, you're using the native function for Reward Points coming with Adobe Commerce here too, correct? This will help us reproduce and investigate further.

**Comment by Frank-Magmodules** [comment]
Clear, @KathiD303. I'll follow up with you either here or via email. Thanks!

**Comment by Frank-Magmodules** [comment]
As noted in https://github.com/mollie/magento2/issues/761, we've also addressed this issue in the [latest release](https://github.com/mollie/magento2/releases/tag/v2.37.0). I'll mark this as closed too, but don't hesitate to contact us if you have any further concerns! :)
