### ISSUE TITLE
Not saving correct shipping_method in sales order table

### ISSUE THREAD

**Issue by jamieolney** [mollie/magento2#768]
**Describe the bug**
Orders placed with Apple Pay where customer chooses different shipping method in Magento, does not get saved to Magento correctly. 

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.5p1
- *Open source/Enterprise/B2b*: Open source
- *Mollie version number (Check configuration)*: 2.36.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Have more than one shipping method in Magento
2. Use Apple Pay at cart page and select a shipping method different from the default
3. Pay and checkout
4. In Magento, the shipping_description is correct, but the shipping_method in the  sales_order table is incorrect and is the default instead

**Expected behavior**
Order saved in Magento database with correct shipping_method and shipping_description as per the customer chose
**Actual behavior**
Order saved in magento database with incorrect default shipping_method but correct shipping_description
**Screenshots**
![image](https://github.com/mollie/magento2/assets/7457106/c7d26a58-d7ff-4d7a-9375-d972d6cd00db)

should be
![image](https://github.com/mollie/magento2/assets/7457106/417f005b-d663-4916-9c75-e7b0003bca9b)

**Additional context**
Using apple pay direct from cart page, using payments api. 
Worked fine on 2.30.1

**Comment by Frank-Magmodules** [comment]
Hey there @jamieolney , good news! We've rolled out [v2.37.0](https://github.com/mollie/magento2/releases/tag/v2.37.0) and addressed the issue you mentioned. Your detailed issue report template really helped us pinpoint the problem quickly—thanks for that! I'll go ahead and close the issue for now, but don't hesitate to reopen or reply if you need further assistance.

**Comment by jamieolney** [comment]
Hi @Frank-Magmodules  I have tried the new plugin on magento2.temptationgifts.com - however I am getting the Apple Pay popup close by itself when it loads the shipping methods - this was not the case on 2.36.0 and below.
Nothing is being logged which is annoying!
Can you look into this please?

**Comment by Frank-Magmodules** [comment]
Hey @jamieolney, could you please reach out to us [directly](https://www.magmodules.eu/help#:~:text=Support%20by%20e,contact%40magmodules.eu)? We'd like to investigate your environment together. It's unfortunate indeed that ApplePay lacks a seamless sandbox flow for easy reproduction, but let's collaborate to find a solution!
