### ISSUE TITLE
Transaction ID missing for orders with Mollie: Payment Link payment method

### ISSUE THREAD

**Issue by nkikkertyouwe** [mollie/magento2#770]
**Describe the bug**
When creating an order using the "Mollie: Payment Link" payment method through the admin, the Transaction ID is not saved for the order (the field mollie_transaction_id in the sales_order table is null).

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.4-p6
- *Open source/Enterprise/B2b*: Enterprise
- *Mollie version number (Check configuration)*: 2.36.0

**To Reproduce**
1. Create an order through the admin (Customers -> All Customers -> [Select customer] -> Create order)
2. Select one or multiple items and fill in the address details if needed
3. Select "Mollie: Payment Link" payment method
4. Choose any Shipping Method and click on "Submit Order"
5. In the order details view in the admin, click on "Fetch Status", notice the error "Transaction ID not found":

**Expected behavior**
The Transaction ID is saved for the order, and the latest status can be retrieved by clicking on the "Fetch Status" button.

**Actual behavior**
An error message "Transaction ID not found" is shown, as the Transaction ID is not saved for the order when the order is created.

**Screenshots**
![-000000153-Orders-Operations-Sales-Magento-Admin](https://github.com/mollie/magento2/assets/105205819/362ef0a2-1fc8-43de-8385-9e8b90c96087)

**Additional context**
This works correctly until version 2.31.0

**Comment by nkikkertyouwe** [comment]
Hi @Frank-Magmodules, thanks for your reply. I am aware that this payment link method works differently than the other "pay immediately" payment methods like iDEAL, but I do see that in the v2.31.0 version, as Transaction ID is created immediately for these orders, even though the customer did not click on the link yet. 

In 2.31.0 I see this in the admin for an example order:
![image](https://github.com/mollie/magento2/assets/105205819/82f8505d-d8f7-416a-baf3-a4f4ebcb5bb0)

As you can see, the link to the checkout URL already contains the mollie_transaction_id: ord_1.pgg79p

**Comment by nkikkertyouwe** [comment]
Hi @Frank-Magmodules, did you check out my latest question? Just want to make sure we're talking about the same issue.

**Comment by Frank-Magmodules** [comment]
Hi @nkikkertyouwe,

Apologies for the delayed reply. Yes, we are aware that this behavior is different in the latest versions compared to earlier versions. This is intended and solve a few issues that existed with the payment link. 

In earlier versions, the transaction is created directly within Mollie, while in later versions this is not the case. There is the creation of the transaction postponed to the moment the customer clicks on the “`pay now`” link.

**Comment by Frank-Magmodules** [comment]
Hi There @nkikkertyouwe , we have just released a [new version](https://github.com/mollie/magento2/releases/tag/v2.38.0) of the plugin where we've added this as an improvement, it now indicates that the payment has not started yet and therefore there is no TransactionID available yet. I'm closing this issue for now. Thanks again!
