### ISSUE TITLE
[IMPROVEMENT] UX Flaw: Enabled Flag Hidden Behind Version Group

### ISSUE THREAD

**Issue by sprankhub** [mollie/magento2#776]
At the moment, the "Enabled" flag is hidden behind the "Version" group. So if the "Version" group is closed, you don't see it:

![image](https://github.com/mollie/magento2/assets/930199/5e753858-9f6d-472c-af89-09a876267891)

Only if you open the "Version" group, you can see the "Enabled" flag:

![image](https://github.com/mollie/magento2/assets/930199/8576b19c-4cb9-4edd-901b-887b7fc91f0e)

This has already led to the situation, where developers said "the extension doesn't work", even though the extension was simply disabled.

IMHO, the "Enabled" flag should be more visible. Either in a separate group or in the "API Details" group or by renaming the "Version" group. However, it is just very unexpected having to open a "Version" group in order to enable the extension.

**Comment by Frank-Magmodules** [comment]
Thanks for bringing up this point, @sprankhub. I agree with your point and it could be that simply changing the tab name to "General" might suffice. I'll touch base with the team to ensure we improve on this. Thanks!

**Comment by Frank-Magmodules** [comment]
Hi There @sprankhub , happy to share that we have implemented your request into this [new](https://github.com/mollie/magento2/releases/tag/v2.39.0) release. 
Thank you for sharing this improvement, it made perfect sense. I'm closing this issue for now, talk soon :)
