### ISSUE TITLE
mollie_transaction_id gets overriden

### ISSUE THREAD

**Issue by Quazz** [mollie/magento2#780]
**Describe the bug**
I'm not 100% sure what the client experienced, but they completed a succesful payment for the order and then got redirected to mollie payment gateway again somehow which created a second transaction (I can see 2 transactions and one has redirected set 1)  that then overrid the mollie_transaction_id which then resulted in the webhook cancelling the order.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6-p3
- *Open source/Enterprise/B2b*: Open Source
- *Mollie version number (Check configuration)*: 2.38.0

**To Reproduce**
Unsure how to reproduce this actually!
You need to somehow have a not executed transaction after a succesful transaction

**Expected behavior**
No transactions possible after succesful payment for the order

**Actual behavior**
A second transaction is created that overrides the link to mollie with incorrect data

**Screenshots**
![image](https://github.com/mollie/magento2/assets/1630369/95bc47d4-aec4-454d-88ba-7e103a3d17b1)

![image](https://github.com/mollie/magento2/assets/1630369/bbf4df82-655c-47e7-b1c7-56d4f0d6b59f)
(not showing transaction_ids for security reason)

Workaround:
Manually update sales_order table with correct transaction id and click "Fetch status" on order view

Additional context:
Has since happened a few more times to other clients.

**Comment by Frank-Magmodules** [comment]
Hi @Quazz,

Thank you for raising this issue. Could you please reach out to us [directly](https://www.magmodules.eu/help#:~:text=products%20and%20services.-,Support%20by%20e%2Dmail,-contact%40magmodules.eu) through our contact form to provide us with the necessary logs? Additionally, could you let us know which payment method was used for these transactions? Was it a payment link or another method?

**Comment by Quazz** [comment]
Hello, upon closer investigation it was an issue with a 3rd party module interfering in the checkoutsession. Apologies for the false report.

**Comment by Frank-Magmodules** [comment]
Thanks for sharing @Quazz , have a good weekend!
