### ISSUE TITLE
Kan geen vergrendeling krijgen voor mollie.order

### ISSUE THREAD

**Issue by jdereus87** [mollie/magento2#782]
I have a client who is running into the following error: 
[2024-06-04 08:34:22] main.CRITICAL: Exception message: Kan geen vergrendeling krijgen voor mollie.order.7067

I cant seem to be able to reproduce this in my local machine (difference being testmode & no webhooks). 

I was looking into class where the errors are coming from: vendor/mollie/magento2/Service/OrderLockService.php & vendor/mollie/magento2/Service/LockService.php

Could you explain what the purpose of this OrderLockService class & LockService class is? Maybe I can solve the problem with some extra info

Magento 2.4.2-p1
Mollie: 2.37

**Comment by Frank-Magmodules** [comment]
Hi @jdereus87 ,

Thank you for opening this issue. The locking mechanism is introduced to prevent race conditions that can occur sometimes when multiple updates for an order come in at the same time. We see the error that you are getting especially on busy systems, where the first update isn’t processed before the next update comes in. 

For this, we can recommend trying to enable this setting:
`Stores` -> `Configuration` -> `Mollie` -> `Advanced` -> `Triggers & Languages `-> `Process transactions in the queue `(experimental). The message can be considered as a debug line, only if you are experiencing other issues it is good to debug

**Comment by Frank-Magmodules** [comment]
Due to inactivity, I'm closing this issue. 
If you feel it is necessary, please feel free to reopen or comment on the issue.
