### ISSUE TITLE
button "refund" in the M2 backend

### ISSUE THREAD

**Issue by Septembermann** [mollie/magento2#785]
Currently, after a credit note has been created, the payment can only be refunded via "offline refund" in the M2 backend. This means that the refund must be made via the Mollie portal.
Will there be a way in the future for the refund to be triggered directly via the M2 backend and not via Mollie?

**Backend changes**
Button "refund"

**Comment by Frank-Magmodules** [comment]
Hi There @Septembermann ,

Thank you for bringing this issue to our attention. We have investigated but were unable to reproduce the problem. Based on our findings, it seems this might not be an issue with the plugin itself. It appears you might be following an incorrect procedure for creating an online refund in Magento.

To create an online refund within Magento, you need to refund the invoice, not the order. You can refer to the official documentation for detailed instructions: [Magento Credit Memo Creation](https://experienceleague.adobe.com/nl/docs/commerce-admin/stores-sales/order-management/credit-memos/credit-memo-create#:~:text=Klikken%20Invoices%20in%20het%20linkerdeelvenster).

**Here's a quick guide:**

- Open the order where Mollie is used.
- Navigate to the invoice.
- You will see the 'Credit Memo' button. Click on it.
- The option for an online refund will then be available like below;

![image-1](https://github.com/mollie/magento2/assets/24823946/ec36d5c8-5e28-4136-9d4e-4484f098c14c)

That's the process, but if you have a different workflow or encounter another issue, please describe the exact steps you took to reproduce the problem. This will help us better understand and assist you.

**Comment by Septembermann** [comment]
Thanks a lot for your help. A classic operating error on our part.

**Comment by Frank-Magmodules** [comment]
Welcome, have a good weekend ahead!
