### ISSUE TITLE
Order status will be set to pending payment after it is paid and had processing

### ISSUE THREAD

**Issue by henkvalk** [mollie/magento2#791]
**Describe the bug**
Because customers open the payment twice there were two orders created in Mollie dashboard, Customer will pay and the Webhook will set status to Processing. But the second payment will be overwrite the latest processing status to pending Payment. 

**Used versions**
- *Magento ver. 2.4.6-p5*
- *Open source*:
- *Mollie v2.39.0*:

**To Reproduce**
1. Go to checkout
2. Click twice on the place order button
3. Pay normal at mollie

**Expected behavior**
Order status is Processing and will stay Processing till it is shipped 

**Actual behavior**
Order status will be processing, but the second payment will be set status to pending payment

**Screenshots**
![image](https://github.com/mollie/magento2/assets/8955854/dff71ea6-1922-4bf1-9ff3-b08d45c6feb6)

![image](https://github.com/mollie/magento2/assets/8955854/978e7eb5-c7d0-4dd6-aabf-c69ebfa0c77f)

![image](https://github.com/mollie/magento2/assets/8955854/604c3e32-9b73-40f5-b95d-8962818b8bde)

![image](https://github.com/mollie/magento2/assets/8955854/5a18132b-af6a-42dd-9cfe-58282f838ec5)

**Additional context**

**Comment by Frank-Magmodules** [comment]
Hi @henkvalk, 

It seems that we have found a configuration where we could reproduce the issue you mentioned. The good news is that we have created a fix, which is currently being tested in different configurations/environments. If approved, it will be included in the release scheduled for later this week! Thank you for sharing this complete report!

**Comment by Frank-Magmodules** [comment]
Hi there, @henkvalk!

I'm happy to inform you that we've fixed this issue in the [latest release](https://github.com/mollie/magento2/releases/tag/v2.40.0). Thank you for your report. I'm closing this issue for now, but feel free to reopen it or comment whenever needed.

Have a great weekend!
