### ISSUE TITLE
[ISSUE] Paymentlink breaks when order cannot be reordered

### ISSUE THREAD

**Issue by Swahjak** [mollie/magento2#795]
**Describe the bug**

Example; sell the last product with a payment link. The product won't be available anymore which means it cannot be reordered.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6
- *Open source/Enterprise/B2b*: Commerce
- *Mollie version number (Check configuration)*: 2.40.0

**To Reproduce**
1. Order a product with 1 stock with payment link
2. Use the payment link

**Expected behavior**

A order that has been accepted by the system at the time of ordering should always be allowed to be paid, mollie should not intervene in our sales.

**Actual behavior**

When a payment link is opened it checks if the order can be reordered on `Service/Magento/PaymentLinkRedirect.php:78` `if ($this->isPaymentLinkExpired->execute($order) || !$order->canReorder()) {`. This prevents orders to be paid regardless of the state of the stock (or other issues) at the time of using the payment link.

**Screenshots**

**Additional context**
We allow sales to basically do what they see fit. Not necessarily a pretty solution (ignoring out of stocks etc), but it works for us and prevents sales to have to go through hoops to get an order sold when the customer is still hot.

**Comment by Swahjak** [comment]
As a side note; since the orders are pending payment, why check if the order can be reordered? Should there be an extra condition? (aside from whether or not Mollie should check this)

**Comment by Swahjak** [comment]
@Frank-Magmodules

**Comment by Frank-Magmodules** [comment]
Hi there, @Swahjak! Thank you for raising the issue. I will get back to you shortly.

**Comment by Frank-Magmodules** [comment]
Hi there @Swahjak, I’m happy to share that we’ve debugged the issue you described. The fix will be included in the next release, which will be available in a couple of weeks. Thank you for your patience!

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak,  Just a quick update to let you know that we've released version [2.40.1](https://github.com/mollie/magento2/releases/tag/v2.40.1), which includes the fix. I'll go ahead and close the issue for now, but feel free to reopen it or add comments whenever you need.
