### ISSUE TITLE
[ISSUE] Paymentlink does not honor "Days to expire"

### ISSUE THREAD

**Issue by Swahjak** [mollie/magento2#796]
**Describe the bug**
A paymentlink does not expire based on the setting, but rather on the selected payment method. If the payment link was not limited to a specific method, it will fallback to the default expiry of 28 days.

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.6
- *Open source/Enterprise/B2b*: Commerce
- *Mollie version number (Check configuration)*: 2.40.0

**To Reproduce**
See `Service/Order/MethodCode.php:46` this method attempts to get a specific payment method, but if none was set it will return a blank string. That blank string will then result in the expiry not being honored.

**Expected behavior**
Paymentlinks should honor the configuration "Days to expire" on the payment link configuration

**Actual behavior**
Payment links will expire either on the day of the specific selected method or will fallback to the default 28 days.

**Comment by Swahjak** [comment]
Also I'm pretty sure that `Service/Mollie/Order/IsPaymentLinkExpired.php::checkWithDefaultDate` will never say it is expired, since we're comparing a date in the future to the order created date. Also it does not take time into account. Something like this should / would work:

```php
    private function checkWithDefaultDate(OrderInterface $order): bool
    {
        $date = $this->timezone->scopeDate($order->getStoreId(), null, true);
        $date = $date->sub(new \DateInterval('P1D'));
        
        return $date->format('Y-m-d H:i:s') > $order->getCreatedAt();
    }
```

Looking into it, isn't the same thing happening for on https://github.com/mollie/magento2/blob/49565b2b526e1af8ccfa922fe5f0ae3502487b04/Service/Mollie/Order/IsPaymentLinkExpired.php#L49. The order date is compared to a date in the future, which is always going to be true(?)

**Comment by Frank-Magmodules** [comment]
Hi @Swahjak,

Good news! We've addressed your use case with a fix, and it will be included in the upcoming release after some advanced testing. Thank you for your clear report on this issue; it's much appreciated as always!

**Comment by Frank-Magmodules** [comment]
Hi again @Swahjak,  Just wanted to let you know that this issue is also covered in the [2.40.1](https://github.com/mollie/magento2/releases/tag/v2.40.1) release. Thank you for bringing it up! We're closing the issue for now. Have a great evening!
