### ISSUE TITLE
Multiple Order comments for each "Fetch Status"

### ISSUE THREAD

**Issue by simonmaass** [mollie/magento2#798]
**Describe the bug**
Every time you click on "Fetch Status" the same comment is written in the comment history. 

<img width="383" alt="image" src="https://github.com/user-attachments/assets/00c3209a-1cdb-465a-9eb4-9f4cc6722af3">

**Used versions**
- *Magento Version number(eg 2.3.5)*: 2.4.7-p1
- *Open source/Enterprise/B2b*: 3.40.0
- *Mollie version number (Check configuration)*:

**To Reproduce**
1. Open Completed order
2. Click on Fetch Status in the Payment Information section
3. Scroll down to comment history

<img width="483" alt="image" src="https://github.com/user-attachments/assets/891202fe-8157-4c04-9592-8aff4970c050">

**Comment by Frank-Magmodules** [comment]
Thanks for sharing this improvement, @simonmaass. We will include this in the upcoming release!

**Comment by Frank-Magmodules** [comment]
Hi @simonmaass, Just letting you know that this issue is also addressed in the 2.40.1 release. Have a great evening!​
