### ISSUE TITLE
[ISSUE] Customer address duplication on every payment method click

### ISSUE THREAD

**Issue by etdevhub** [mollie/magento2#800]
**Describe the bug**
If the customer has no addresses at all, fills out the address form at checkout page, and chooses the payment method, it leads to saving the address in the database again and again - each time he clicks on the payment method (billing and shipping address should be the same). So, it leads to duplication...

**Used versions**
Magento ver. 2.4.6-p6
Open source
Mollie v2.40.0

**Steps to reproduce the behavior:**
1. Create new customer
2. Add any product to the cart
3. Go to the checkout page
4. Fill out the shipping address form, choose shipping method and click "Next" button
5. Click on Mollie payment method (creditcard for example)

**Expected behavior**
I guess the customer address should not be saved, since it happens after the customer placed order?

**Actual behavior**
It saves the customer address as many times as you click on the Mollie payment method...

**Screenshots**
![Screenshot from 2024-08-05 16-18-19](https://github.com/user-attachments/assets/341356c6-c22c-4dc9-9d4d-16b626df71de)

**Additional context**
[Screencast from 08-05-2024 04:23:04 PM.webm](https://github.com/user-attachments/assets/b0ee639f-e596-4208-8799-9068c5e8942d)

**Comment by Frank-Magmodules** [comment]
Thank you for opening this issue and following our report template; it's very helpful. 
I was able to reproduce the problem as you described, so we will investigate further to resolve this for you.

**Comment by Leone** [comment]
Hi,

We have the same issue in our shop.
This issue will be fixed in the next release, right?

When should the new version be released?

**Comment by Frank-Magmodules** [comment]
Indeed, @Leone, the new release will be available at the beginning of next month!

**Comment by Frank-Magmodules** [comment]
Hi @etdevhub and @Leone,   I’m happy to inform you that this issue has been addressed in the latest Mollie release, version [2.41.0](https://github.com/mollie/magento2/releases/tag/v2.41.0). I’ll close this issue for now, but feel free to reopen or comment if needed.
