### ISSUE TITLE
Klarna not activating in checkout when not using base currency

### ISSUE THREAD

**Issue by jdereus87** [mollie/magento2#803]
**Describe the bug**
We have created a new store in Swedish. The prices are calculated using the currency implementation (thus using the exchange rate). When we set Use Base Currency to Yes, Klarna appears and works as expected. When we tick this option to no, Klarna does not appear as a payment method in the checkout.

**Used versions**
Magento 2.4.6-p6
Hyva theme
mollie hyva checkout 1.3.2

**To Reproduce**
Use base currency Yes -> Klarna in checkout
Use base currency No -> No Klarna in checkout

**Expected behavior**
We expected Klarna to especially be working when the used currency (though not the base currency) is SEK. The creditcard payment method seems to be working just fine with the SEK currency even though the base currency is EUR.

**Comment by Frank-Magmodules** [comment]
Hi @jdereus87,

Thanks for bringing this to our attention! We’ll investigate the issue right away. According to the [Mollie documentation](https://docs.mollie.com/docs/klarna), SEK should indeed be compatible. I’ll follow up with you shortly.

**Comment by jdereus87** [comment]
@Frank-Magmodules this problem has somehow solved itself. Maybe Mollie changed something in their configuration for this particular client. We have not received any info on this (yet).

**Comment by Frank-Magmodules** [comment]
Gotta love it when issues resolve themselves—what a world we live in. ;-)
Thanks, @jdereus87! Catch up with you later!
