### ISSUE TITLE
Backend Payment payment link not created anymore

### ISSUE THREAD

**Issue by Sendurrr** [mollie/magento2#806]
In the past versions we used the Backend Payment Link to create orders for customers whom then would receive an email with the link to the payment. We took this Url from the additional_information column in the Sales_Order_Payment table. But since we update we've noticed that this payment Url is not created anymore in the additional_information"*until* we manually click the "click here to pay" link in the backend order...

Is there a way that this link is created immediately together with the order (as before) and not only *after*  we hit that link on the backend order?

**Comment by dragonfly4** [comment]
Let me know if you prefer a separate issue. We have also issues with the backend payment link so maybe it's related.

Version 2.4.0 with Magento 2.4.6-p6

The link goes to
`https://ourwebsite.be/nl/mollie/checkout/paymentlink/order/MDozOnIxUEdkNGRRTTRjcVFIT015dFptK3RJQlp5NkhUQ0daZ1JoMGxxxxxxx/`

which does not exist so it redirects to the root folder. Same link is sent in the e-mail to the customer.

![Mollie_backend](https://github.com/user-attachments/assets/b32b3787-2686-4bf8-bae4-9290bb7794d3)

**Comment by Sendurrr** [comment]
The link is fine for us, but we need it to be pre-filled in the additional_information column so we can fetch it there for our manual emails to our customers for payment instructions...

**Comment by Sendurrr** [comment]
Well, this in inconvient. Not only is this link not pre-created anymore. If we don't click on it immediately, it get's expired (within 10 minutes!). What a downfall in functionality this is man. I shouldn't have updated. Worked perfect, now it is a pain in the ass module.

**Comment by Frank-Magmodules** [comment]
Hi @Sendurrr,

I completely understand your frustration, which is perfectly reasonable. Currently, the payment link logic is designed to work with both the Payment API and Order API from Mollie, adding some complexity. Here’s what happens: for instance, with [iDeal](https://docs.mollie.com/docs/status-change#expiry-times-per-payment-method), the payment expires after 15 minutes, but only the payment itself is canceled, not the related order. 

If a customer clicks the payment link after, say, 2 hours, a new payment is automatically created to avoid issues with the expired one. The order itself will only be canceled in Magento when it is explicitly canceled.

**All of this logic is handled by the link created by the module, and we’ll ensure that this link becomes available again in the `additional_information` column in the next release!**

I understand that you might prefer a simpler approach, and we plan to streamline this once Mollie merges the [Payment API](https://docs.mollie.com/reference/payments-api) and [Order API](https://docs.mollie.com/reference/orders-api).

Thank you for your understanding, @Sendurrr!

**Comment by Sendurrr** [comment]
#All of this logic is handled by the link created by the module, and we’ll ensure that this link becomes available again in the additional_information column in the next release!

perfect. looking forward to this release. It is now not working for us unfortunately (we create a lot of b2b orders on a daily basis in which our email system took this information from the additional_information column.

**Comment by Frank-Magmodules** [comment]
Thanks for understanding @Sendurrr , keep you posted!

**Comment by Frank-Magmodules** [comment]
Hi @Sendurrr,  I'm happy to share that we’ve released a [new version](https://github.com/mollie/magento2/releases/tag/v2.41.0) of the Mollie plugin, where we’ve reset the `checkout_url` for payment link orders so you can now retrieve it from the database. I hope this meets your needs! I’ll close this issue for now, but feel free to comment or reopen it if necessary. Thanks for your patience and for bringing this to our attention!
