### ISSUE TITLE
question: Klarna support

### ISSUE THREAD

**Issue by albsa** [mollie/magento2#81]
Hi guys,

When will we support Klarna in this module?

**Comment by Frank-Magmodules** [comment]
Hi @albsa,

Thanks for your message on this. The new release with Klarna support is about 95% ready, but we are waiting for some final edits on the Mollie API. Once these edits are done, we can start testing and create an release. If everything works out correctly the release will be available by the beginning of next week.

Frank

**Comment by albsa** [comment]
Can we already use the 1.4.0 branch for Klarna Support @Frank-Magmodules ?
