### ISSUE TITLE
Capture the payment upon authorization

### ISSUE THREAD

**Issue by LucaGallinari** [mollie/magento2#818]
I have a local installation of Magento 2.4.4, i have installed this plugin and i have enabled it as sandbox with a test account. I cannot find a way to authorize and capture the payment "immediately", it seems only to allow to capture the payment upon shipping or manually (there is a config for this).
Is there a way to do it without a customization?

**Comment by fjbender** [comment]
Heyo, this depends a bit on the payment method (and it might be with your local setup that you don't receive webhook updates, which might lure you into a false sense of "non-shipping" - so make sure to double check that as well).

* For all Klarna-like types, manual shipment is mandatory
* For cards, you can optionally configure manual capture
* For all other methods, the amount is transferred immediately without shipping/capturing

This list of [payment methods in the docs](https://docs.mollie.com/docs/payment-methods) will have more details whether auto-capture is the default.

**Comment by LucaGallinari** [comment]
You are right, it's only Klarna that requires the shipment in order to capture the payment ([source](https://docs.klarna.com/payments/web-payments/additional-resources/use-cases/automatic-capture/)). I read it quickly but it seems to be a policy of their contracts, so it's not something that should be easily configurable by the merchant (or from the Magento admin).
The other methods (i tried Credit Cards and MyBank) instantly capture the amount.
I close this as there are no real issue or changes that could be made.
Thank you!

----

> and it might be with your local setup that you don't receive webhook updates, which might lure you into a false sense of "non-shipping" - so make sure to double check that as well

Yes, i am bypassing this by using the "Fetch status" button in the detail of the order on the admin.
