### ISSUE TITLE
Dynamic pricing fees

### ISSUE THREAD

**Issue by Webunity** [mollie/magento2#86]
I am exploring Magento 2 as an alternative to our current shop and also switching to Mollie; Question i have is:

Based on the payment selection i would like to apply different extra fees, e.g. bank transfer is EUR 0.25 but Paypal is also a percentage etc.  PSD2 law mentions it is not allowed to charge for example for iDEAL, but they don't mention anything about Paypal.

For example; for an order worth 10 EUR in goods i want the customer to pay the fees so that i will get 10 euro for the product in the end. This would mean (if paying by PayPal) 10 EUR + EUR 0.1 + PP Fee; assuming the paypal fee is 3.4%, this boils to (10/0.966)+0.1=EUR 10.45

Is this supported by the plugin?

**Comment by ndijkstra** [comment]
Hi, our plugin doesn't support surcharging payment costs. Because of the PSD2 law it's really complicated so we've decided to not add this functionality to our plugins.

**Comment by Webunity** [comment]
Hey @ndijkstra would it be difficult to add it myself in an override class? any pointers would help :)

**Comment by willemstuursma** [comment]
@Webunity You should find a dedicated Magento plugin to add fees to payment methods.

**Comment by Maketoire** [comment]
@Webunity Thanks for the inquiry. There are several plugins within the Magento community that solve your issue, however most of them are focused on non-EU markets. 

We understand the issue your encountering, so let’s find a way to make it work with Mollie. Contact me at mike@mollie.com and we’ll find a solution together.
