### ISSUE TITLE
payment options not showing for guesta

### ISSUE THREAD

**Issue by phagens** [mollie/magento2#87]
I use version 1.3.4 and everything works ok with registered users. But when a guest checks out not all the payment options are shown. F.i. It does not show EPS when the country is Austria altough it is set correctly in the backend
[setting.pdf](https://github.com/mollie/magento2/files/2521804/setting.pdf)
[frontend.pdf](https://github.com/mollie/magento2/files/2521805/frontend.pdf)

**Comment by Frank-Magmodules** [comment]
Hi @phagens. Do you encounter the same issue when using the default Magento checkout? It Looks like the payment method block is not updated after inserting the shipping address, can you confirm this?

**Comment by Frank-Magmodules** [comment]
@phagens , any updates on this?
Thx!

**Comment by phagens** [comment]
No,

I think it must be somewhere in our checkout page. For some payment methods it is working ok, others will only show on mobile devices.


m.vr.gr. - greetings


Piet Hagens
Jukebox Revival
Florijnstraat 6 C
4879 AH  Etten-Leur

Website: www.jukebox-revival.nl
Webshop: www.jukebox-revival.eu

[logo]
P Please consider the environment before printing this e-mail


The information sent with this e-mail message is only for the strict use of the intended recipient. In the event that this e-mail message is incomplete in any way, the recipient is kindly requested to contact the sender of this message. It is not permitted to publish, copy, circulate and/or disclose any of this information to third parties without the permission of Jukebox Revival. If you are not the intended recipient of and are in possession of this e-mail message, please notify us immediately, delete the e-mail message from your inbox, and do not use it for any purpose or disclose the contents of this message to third parties, or publish, copy or store this information on an information carrier.




Van: Frank Tiggelman <notifications@github.com>
Verzonden: donderdag 1 november 2018 10:50
Aan: mollie/magento2 <magento2@noreply.github.com>
CC: Jukebox Revival <info@jukebox-revival.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [mollie/magento2] payment options not showing for guesta (#87)


@phagens<https://github.com/phagens> , any updates on this?
Thx!

**Comment by Frank-Magmodules** [comment]
HI @phagens , OK, for now i close this issue, if you need further help, please re-open the issue or sent us a direct e-mail.
