### ISSUE TITLE
Compilation Error: Incorrect dependency in class Mollie\Payment\Block\Info\Base

### ISSUE THREAD

**Issue by jdinse** [mollie/magento2#92]
I tried to upgrade from Magento CE 2.1.12 to 2.1.15. After that, I got this compilation error with mollie/magento2 version 1.3 as well as with version 1.4.:

	Errors during compilation:
		Mollie\Payment\Block\Info\Base
			Incorrect dependency in class Mollie\Payment\Block\Info\Base in /home/jmmshop/beta/vendor/mollie/magento2/Block/Info/Base.php
	\Magento\Framework\Stdlib\DateTime\TimezoneInterface already exists in context object
	Total Errors Count: 1

**Comment by Marvin-Magmodules** [comment]
Fixed in [v1.4.1](https://github.com/mollie/magento2/releases/tag/v1.4.1)
