### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getStreet() 

### ISSUE THREAD

**Issue by GetMagented** [mollie/magento2#96]
After updating to the newest version of Mollie (1.4.2) we get an error when checking out. We are in testmode. We use virtual products so do not have a shipping address, only a billing address. 

I just tested with a normal product, and then the checkout does work. So perhaps the extension is not compatible with virtual/downloadable products? Is there any way to use the billing address instead of shipping address?

`Fatal error: Uncaught Error: Call to a member function getStreet() on null in /data/web/magento2_staging/vendor/mollie/magento2/Model/Client/Payments.php:131 Stack trace: #0 /data/web/magento2_staging/vendor/mollie/magento2/Model/Client/Payments.php(97): Mollie\Payment\Model\Client\Payments->getAddressLine(NULL) #1 /data/web/magento2_staging/vendor/mollie/magento2/Model/Mollie.php(237): Mollie\Payment\Model\Client\Payments->startTransaction(Object(Magento\Sales\Model\Order\Interceptor), Object(Mollie\Api\MollieApiClient)) #2 /data/web/magento2_staging/vendor/mollie/magento2/Controller/Checkout/Redirect.php(89): Mollie\Payment\Model\Mollie->startTransaction(Object(Magento\Sales\Model\Order\Interceptor)) #3 /data/web/magento2_staging/vendor/magento/framework/App/Action/Action.php(107): Mollie\Payment\Controller\Checkout\Redirect->execute() #4 /data/web/magento2_staging/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #5 /data in /data/web/magento2_staging/vendor/mollie/magento2/Model/Client/Payments.php on line 131`

**Comment by willemstuursma** [comment]
The shipping address is optional in the Mollie API. If it is empty in Magento, it should not be sent.
@Marvin-Magmodules.

**Comment by Marvin-Magmodules** [comment]
Hi @GetMagented just pushed a fix to the [1.4.3 branch](https://github.com/mollie/magento2/commit/ca3735bd3193236eabcb09399afd38d9127f6d14) for virtual orders. Street could not be loaded as for virtual orders there is no shipping address object. Can you confirm this on your staging?

**Comment by Marvin-Magmodules** [comment]
Hi @GetMagented fixed and tested it in Magento 2.2 & Magento 2.3. Just released the new [v1.4.3](https://github.com/mollie/magento2/releases/tag/v1.4.3) version. Closing this issue now as this seems resolved, but please feel free to reopen this if you encounter any problems related to this issue.

**Comment by GetMagented** [comment]
Hi Marvin, sorry didn't have time yet to test the new release, but looks like it will work fine. If we have any more issues with this I will let you know. Thanks!
