### ISSUE TITLE
Creditmemo with Orders API

### ISSUE THREAD

**Issue by FreekVandeursen** [mollie/magento2#99]
When using the Orders API, it is not possible to create a creditmemo in Magento for orders that contain a shipping amount including tax.

Reason: the `createOrderRefund` method will compare the `getShippingAmount` from the creditmemo (which is excl. tax) with the `getTotalAmount` from the Mollie order line (which is incl. tax).

**Comment by Frank-Magmodules** [comment]
Fixed in [v1.4.4](https://github.com/mollie/magento2/releases/tag/v1.4.4).
